# Local configuration for orion-server3
server:
  identity:
    id: orion-server3
    certificatePath: /etc/orion-server/crypto/server3/server3.pem
    keyPath: /etc/orion-server/crypto/server3/server3.key
  network:
    address: 0.0.0.0
    port: 6001
  database:
    name: leveldb
    ledgerdirectory: /var/orion-server/ledger
  queueLength:
    transaction: 1000
    reorderedTransactionBatch: 100
    block: 100
  logLevel: info
  tls:
    enabled: false

blockCreation:
  maxBlockSize: 2
  maxTransactionCountPerBlock: 1
  blockTimeout: 50ms

replication:
  walDir: "/var/orion-server/ledger/etcdraft/wal"
  snapDir: "/var/orion-server/ledger/etcdraft/snapshot"
  auxDir: "/var/orion-server/ledger/auxiliary"
  network:
    address: 0.0.0.0
    port: 7050
  tls:
    enabled: false

bootstrap:
  method: genesis
  file: /etc/orion-server/config/3node-shared-config-bootstrap.yml
