// Code generated by protoc-gen-go. DO NOT EDIT.
// source: block_and_transaction.proto

package types

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Flag int32

const (
	Flag_VALID                                      Flag = 0
	Flag_INVALID_MVCC_CONFLICT_WITHIN_BLOCK         Flag = 1
	Flag_INVALID_MVCC_CONFLICT_WITH_COMMITTED_STATE Flag = 2
	Flag_INVALID_DATABASE_DOES_NOT_EXIST            Flag = 3
	Flag_INVALID_NO_PERMISSION                      Flag = 4
	Flag_INVALID_INCORRECT_ENTRIES                  Flag = 5
	Flag_INVALID_UNAUTHORISED                       Flag = 6
)

var Flag_name = map[int32]string{
	0: "VALID",
	1: "INVALID_MVCC_CONFLICT_WITHIN_BLOCK",
	2: "INVALID_MVCC_CONFLICT_WITH_COMMITTED_STATE",
	3: "INVALID_DATABASE_DOES_NOT_EXIST",
	4: "INVALID_NO_PERMISSION",
	5: "INVALID_INCORRECT_ENTRIES",
	6: "INVALID_UNAUTHORISED",
}

var Flag_value = map[string]int32{
	"VALID":                              0,
	"INVALID_MVCC_CONFLICT_WITHIN_BLOCK": 1,
	"INVALID_MVCC_CONFLICT_WITH_COMMITTED_STATE": 2,
	"INVALID_DATABASE_DOES_NOT_EXIST":            3,
	"INVALID_NO_PERMISSION":                      4,
	"INVALID_INCORRECT_ENTRIES":                  5,
	"INVALID_UNAUTHORISED":                       6,
}

func (x Flag) String() string {
	return proto.EnumName(Flag_name, int32(x))
}

func (Flag) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_8098d268f52aac08, []int{0}
}

// Block holds the chain information and transactions
type Block struct {
	Header *BlockHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	// Types that are valid to be assigned to Payload:
	//	*Block_DataTxEnvelopes
	//	*Block_ConfigTxEnvelope
	//	*Block_DBAdministrationTxEnvelope
	//	*Block_UserAdministrationTxEnvelope
	Payload              isBlock_Payload   `protobuf_oneof:"Payload"`
	TxValidationInfo     []*ValidationInfo `protobuf:"bytes,6,rep,name=tx_validation_info,json=txValidationInfo,proto3" json:"tx_validation_info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Block) Reset()         { *m = Block{} }
func (m *Block) String() string { return proto.CompactTextString(m) }
func (*Block) ProtoMessage()    {}
func (*Block) Descriptor() ([]byte, []int) {
	return fileDescriptor_8098d268f52aac08, []int{0}
}

func (m *Block) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Block.Unmarshal(m, b)
}
func (m *Block) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Block.Marshal(b, m, deterministic)
}
func (m *Block) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Block.Merge(m, src)
}
func (m *Block) XXX_Size() int {
	return xxx_messageInfo_Block.Size(m)
}
func (m *Block) XXX_DiscardUnknown() {
	xxx_messageInfo_Block.DiscardUnknown(m)
}

var xxx_messageInfo_Block proto.InternalMessageInfo

func (m *Block) GetHeader() *BlockHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

type isBlock_Payload interface {
	isBlock_Payload()
}

type Block_DataTxEnvelopes struct {
	DataTxEnvelopes *DataTxEnvelopes `protobuf:"bytes,2,opt,name=data_tx_envelopes,json=dataTxEnvelopes,proto3,oneof"`
}

type Block_ConfigTxEnvelope struct {
	ConfigTxEnvelope *ConfigTxEnvelope `protobuf:"bytes,3,opt,name=config_tx_envelope,json=configTxEnvelope,proto3,oneof"`
}

type Block_DBAdministrationTxEnvelope struct {
	DBAdministrationTxEnvelope *DBAdministrationTxEnvelope `protobuf:"bytes,4,opt,name=DB_administration_tx_envelope,json=DBAdministrationTxEnvelope,proto3,oneof"`
}

type Block_UserAdministrationTxEnvelope struct {
	UserAdministrationTxEnvelope *UserAdministrationTxEnvelope `protobuf:"bytes,5,opt,name=user_administration_tx_envelope,json=userAdministrationTxEnvelope,proto3,oneof"`
}

func (*Block_DataTxEnvelopes) isBlock_Payload() {}

func (*Block_ConfigTxEnvelope) isBlock_Payload() {}

func (*Block_DBAdministrationTxEnvelope) isBlock_Payload() {}

func (*Block_UserAdministrationTxEnvelope) isBlock_Payload() {}

func (m *Block) GetPayload() isBlock_Payload {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *Block) GetDataTxEnvelopes() *DataTxEnvelopes {
	if x, ok := m.GetPayload().(*Block_DataTxEnvelopes); ok {
		return x.DataTxEnvelopes
	}
	return nil
}

func (m *Block) GetConfigTxEnvelope() *ConfigTxEnvelope {
	if x, ok := m.GetPayload().(*Block_ConfigTxEnvelope); ok {
		return x.ConfigTxEnvelope
	}
	return nil
}

func (m *Block) GetDBAdministrationTxEnvelope() *DBAdministrationTxEnvelope {
	if x, ok := m.GetPayload().(*Block_DBAdministrationTxEnvelope); ok {
		return x.DBAdministrationTxEnvelope
	}
	return nil
}

func (m *Block) GetUserAdministrationTxEnvelope() *UserAdministrationTxEnvelope {
	if x, ok := m.GetPayload().(*Block_UserAdministrationTxEnvelope); ok {
		return x.UserAdministrationTxEnvelope
	}
	return nil
}

func (m *Block) GetTxValidationInfo() []*ValidationInfo {
	if m != nil {
		return m.TxValidationInfo
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Block) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Block_DataTxEnvelopes)(nil),
		(*Block_ConfigTxEnvelope)(nil),
		(*Block_DBAdministrationTxEnvelope)(nil),
		(*Block_UserAdministrationTxEnvelope)(nil),
	}
}

// BlockHeaderBase holds the block metadata and the chain information
// that computed before transaction validation
type BlockHeaderBase struct {
	Number uint64 `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"`
	// Hash of (number - 1) BlockHeaderBase
	PreviousBaseHeaderHash []byte `protobuf:"bytes,2,opt,name=previous_base_header_hash,json=previousBaseHeaderHash,proto3" json:"previous_base_header_hash,omitempty"`
	// Hash of BlockHeader of last block already committed to ledger
	LastCommittedBlockHash []byte `protobuf:"bytes,3,opt,name=last_committed_block_hash,json=lastCommittedBlockHash,proto3" json:"last_committed_block_hash,omitempty"`
	// Number of last block already committed to ledger
	LastCommittedBlockNum uint64   `protobuf:"varint,4,opt,name=last_committed_block_num,json=lastCommittedBlockNum,proto3" json:"last_committed_block_num,omitempty"`
	XXX_NoUnkeyedLiteral  struct{} `json:"-"`
	XXX_unrecognized      []byte   `json:"-"`
	XXX_sizecache         int32    `json:"-"`
}

func (m *BlockHeaderBase) Reset()         { *m = BlockHeaderBase{} }
func (m *BlockHeaderBase) String() string { return proto.CompactTextString(m) }
func (*BlockHeaderBase) ProtoMessage()    {}
func (*BlockHeaderBase) Descriptor() ([]byte, []int) {
	return fileDescriptor_8098d268f52aac08, []int{1}
}

func (m *BlockHeaderBase) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockHeaderBase.Unmarshal(m, b)
}
func (m *BlockHeaderBase) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockHeaderBase.Marshal(b, m, deterministic)
}
func (m *BlockHeaderBase) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockHeaderBase.Merge(m, src)
}
func (m *BlockHeaderBase) XXX_Size() int {
	return xxx_messageInfo_BlockHeaderBase.Size(m)
}
func (m *BlockHeaderBase) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockHeaderBase.DiscardUnknown(m)
}

var xxx_messageInfo_BlockHeaderBase proto.InternalMessageInfo

func (m *BlockHeaderBase) GetNumber() uint64 {
	if m != nil {
		return m.Number
	}
	return 0
}

func (m *BlockHeaderBase) GetPreviousBaseHeaderHash() []byte {
	if m != nil {
		return m.PreviousBaseHeaderHash
	}
	return nil
}

func (m *BlockHeaderBase) GetLastCommittedBlockHash() []byte {
	if m != nil {
		return m.LastCommittedBlockHash
	}
	return nil
}

func (m *BlockHeaderBase) GetLastCommittedBlockNum() uint64 {
	if m != nil {
		return m.LastCommittedBlockNum
	}
	return 0
}

// BlockHeader holds, in addition to base header, extra block metadata and the chain information
// that computed after transactions validation
type BlockHeader struct {
	BaseHeader *BlockHeaderBase `protobuf:"bytes,1,opt,name=base_header,json=baseHeader,proto3" json:"base_header,omitempty"`
	// Skip chain hashed, based of BlockHeader hashed of blocks connected in blocks skip list
	SkipchainHashes [][]byte `protobuf:"bytes,2,rep,name=skipchain_hashes,json=skipchainHashes,proto3" json:"skipchain_hashes,omitempty"`
	// Root of Merkle tree that contains all transactions, including validation data
	TxMerkelTreeRootHash []byte `protobuf:"bytes,3,opt,name=tx_merkel_tree_root_hash,json=txMerkelTreeRootHash,proto3" json:"tx_merkel_tree_root_hash,omitempty"`
	// Root hash of system wide state merkle-particia tree
	StateMerkelTreeRootHash []byte `protobuf:"bytes,4,opt,name=state_merkel_tree_root_hash,json=stateMerkelTreeRootHash,proto3" json:"state_merkel_tree_root_hash,omitempty"`
	// Validation info for transactions in block.
	ValidationInfo       []*ValidationInfo `protobuf:"bytes,5,rep,name=validation_info,json=validationInfo,proto3" json:"validation_info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *BlockHeader) Reset()         { *m = BlockHeader{} }
func (m *BlockHeader) String() string { return proto.CompactTextString(m) }
func (*BlockHeader) ProtoMessage()    {}
func (*BlockHeader) Descriptor() ([]byte, []int) {
	return fileDescriptor_8098d268f52aac08, []int{2}
}

func (m *BlockHeader) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockHeader.Unmarshal(m, b)
}
func (m *BlockHeader) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockHeader.Marshal(b, m, deterministic)
}
func (m *BlockHeader) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockHeader.Merge(m, src)
}
func (m *BlockHeader) XXX_Size() int {
	return xxx_messageInfo_BlockHeader.Size(m)
}
func (m *BlockHeader) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockHeader.DiscardUnknown(m)
}

var xxx_messageInfo_BlockHeader proto.InternalMessageInfo

func (m *BlockHeader) GetBaseHeader() *BlockHeaderBase {
	if m != nil {
		return m.BaseHeader
	}
	return nil
}

func (m *BlockHeader) GetSkipchainHashes() [][]byte {
	if m != nil {
		return m.SkipchainHashes
	}
	return nil
}

func (m *BlockHeader) GetTxMerkelTreeRootHash() []byte {
	if m != nil {
		return m.TxMerkelTreeRootHash
	}
	return nil
}

func (m *BlockHeader) GetStateMerkelTreeRootHash() []byte {
	if m != nil {
		return m.StateMerkelTreeRootHash
	}
	return nil
}

func (m *BlockHeader) GetValidationInfo() []*ValidationInfo {
	if m != nil {
		return m.ValidationInfo
	}
	return nil
}

type DataTxEnvelopes struct {
	Envelopes            []*DataTxEnvelope `protobuf:"bytes,1,rep,name=envelopes,proto3" json:"envelopes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *DataTxEnvelopes) Reset()         { *m = DataTxEnvelopes{} }
func (m *DataTxEnvelopes) String() string { return proto.CompactTextString(m) }
func (*DataTxEnvelopes) ProtoMessage()    {}
func (*DataTxEnvelopes) Descriptor() ([]byte, []int) {
	return fileDescriptor_8098d268f52aac08, []int{3}
}

func (m *DataTxEnvelopes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DataTxEnvelopes.Unmarshal(m, b)
}
func (m *DataTxEnvelopes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DataTxEnvelopes.Marshal(b, m, deterministic)
}
func (m *DataTxEnvelopes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DataTxEnvelopes.Merge(m, src)
}
func (m *DataTxEnvelopes) XXX_Size() int {
	return xxx_messageInfo_DataTxEnvelopes.Size(m)
}
func (m *DataTxEnvelopes) XXX_DiscardUnknown() {
	xxx_messageInfo_DataTxEnvelopes.DiscardUnknown(m)
}

var xxx_messageInfo_DataTxEnvelopes proto.InternalMessageInfo

func (m *DataTxEnvelopes) GetEnvelopes() []*DataTxEnvelope {
	if m != nil {
		return m.Envelopes
	}
	return nil
}

type DataTxEnvelope struct {
	Payload              *DataTx  `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	Signature            []byte   `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DataTxEnvelope) Reset()         { *m = DataTxEnvelope{} }
func (m *DataTxEnvelope) String() string { return proto.CompactTextString(m) }
func (*DataTxEnvelope) ProtoMessage()    {}
func (*DataTxEnvelope) Descriptor() ([]byte, []int) {
	return fileDescriptor_8098d268f52aac08, []int{4}
}

func (m *DataTxEnvelope) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DataTxEnvelope.Unmarshal(m, b)
}
func (m *DataTxEnvelope) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DataTxEnvelope.Marshal(b, m, deterministic)
}
func (m *DataTxEnvelope) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DataTxEnvelope.Merge(m, src)
}
func (m *DataTxEnvelope) XXX_Size() int {
	return xxx_messageInfo_DataTxEnvelope.Size(m)
}
func (m *DataTxEnvelope) XXX_DiscardUnknown() {
	xxx_messageInfo_DataTxEnvelope.DiscardUnknown(m)
}

var xxx_messageInfo_DataTxEnvelope proto.InternalMessageInfo

func (m *DataTxEnvelope) GetPayload() *DataTx {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *DataTxEnvelope) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

type ConfigTxEnvelope struct {
	Payload              *ConfigTx `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	Signature            []byte    `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ConfigTxEnvelope) Reset()         { *m = ConfigTxEnvelope{} }
func (m *ConfigTxEnvelope) String() string { return proto.CompactTextString(m) }
func (*ConfigTxEnvelope) ProtoMessage()    {}
func (*ConfigTxEnvelope) Descriptor() ([]byte, []int) {
	return fileDescriptor_8098d268f52aac08, []int{5}
}

func (m *ConfigTxEnvelope) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfigTxEnvelope.Unmarshal(m, b)
}
func (m *ConfigTxEnvelope) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfigTxEnvelope.Marshal(b, m, deterministic)
}
func (m *ConfigTxEnvelope) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfigTxEnvelope.Merge(m, src)
}
func (m *ConfigTxEnvelope) XXX_Size() int {
	return xxx_messageInfo_ConfigTxEnvelope.Size(m)
}
func (m *ConfigTxEnvelope) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfigTxEnvelope.DiscardUnknown(m)
}

var xxx_messageInfo_ConfigTxEnvelope proto.InternalMessageInfo

func (m *ConfigTxEnvelope) GetPayload() *ConfigTx {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *ConfigTxEnvelope) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

type DBAdministrationTxEnvelope struct {
	Payload              *DBAdministrationTx `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	Signature            []byte              `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *DBAdministrationTxEnvelope) Reset()         { *m = DBAdministrationTxEnvelope{} }
func (m *DBAdministrationTxEnvelope) String() string { return proto.CompactTextString(m) }
func (*DBAdministrationTxEnvelope) ProtoMessage()    {}
func (*DBAdministrationTxEnvelope) Descriptor() ([]byte, []int) {
	return fileDescriptor_8098d268f52aac08, []int{6}
}

func (m *DBAdministrationTxEnvelope) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DBAdministrationTxEnvelope.Unmarshal(m, b)
}
func (m *DBAdministrationTxEnvelope) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DBAdministrationTxEnvelope.Marshal(b, m, deterministic)
}
func (m *DBAdministrationTxEnvelope) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DBAdministrationTxEnvelope.Merge(m, src)
}
func (m *DBAdministrationTxEnvelope) XXX_Size() int {
	return xxx_messageInfo_DBAdministrationTxEnvelope.Size(m)
}
func (m *DBAdministrationTxEnvelope) XXX_DiscardUnknown() {
	xxx_messageInfo_DBAdministrationTxEnvelope.DiscardUnknown(m)
}

var xxx_messageInfo_DBAdministrationTxEnvelope proto.InternalMessageInfo

func (m *DBAdministrationTxEnvelope) GetPayload() *DBAdministrationTx {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *DBAdministrationTxEnvelope) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

type UserAdministrationTxEnvelope struct {
	Payload              *UserAdministrationTx `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	Signature            []byte                `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *UserAdministrationTxEnvelope) Reset()         { *m = UserAdministrationTxEnvelope{} }
func (m *UserAdministrationTxEnvelope) String() string { return proto.CompactTextString(m) }
func (*UserAdministrationTxEnvelope) ProtoMessage()    {}
func (*UserAdministrationTxEnvelope) Descriptor() ([]byte, []int) {
	return fileDescriptor_8098d268f52aac08, []int{7}
}

func (m *UserAdministrationTxEnvelope) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserAdministrationTxEnvelope.Unmarshal(m, b)
}
func (m *UserAdministrationTxEnvelope) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserAdministrationTxEnvelope.Marshal(b, m, deterministic)
}
func (m *UserAdministrationTxEnvelope) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserAdministrationTxEnvelope.Merge(m, src)
}
func (m *UserAdministrationTxEnvelope) XXX_Size() int {
	return xxx_messageInfo_UserAdministrationTxEnvelope.Size(m)
}
func (m *UserAdministrationTxEnvelope) XXX_DiscardUnknown() {
	xxx_messageInfo_UserAdministrationTxEnvelope.DiscardUnknown(m)
}

var xxx_messageInfo_UserAdministrationTxEnvelope proto.InternalMessageInfo

func (m *UserAdministrationTxEnvelope) GetPayload() *UserAdministrationTx {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *UserAdministrationTxEnvelope) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

type DataTx struct {
	UserID               string         `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID,omitempty"`
	TxID                 string         `protobuf:"bytes,2,opt,name=txID,proto3" json:"txID,omitempty"`
	DBOperations         []*DBOperation `protobuf:"bytes,3,rep,name=DBOperations,proto3" json:"DBOperations,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *DataTx) Reset()         { *m = DataTx{} }
func (m *DataTx) String() string { return proto.CompactTextString(m) }
func (*DataTx) ProtoMessage()    {}
func (*DataTx) Descriptor() ([]byte, []int) {
	return fileDescriptor_8098d268f52aac08, []int{8}
}

func (m *DataTx) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DataTx.Unmarshal(m, b)
}
func (m *DataTx) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DataTx.Marshal(b, m, deterministic)
}
func (m *DataTx) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DataTx.Merge(m, src)
}
func (m *DataTx) XXX_Size() int {
	return xxx_messageInfo_DataTx.Size(m)
}
func (m *DataTx) XXX_DiscardUnknown() {
	xxx_messageInfo_DataTx.DiscardUnknown(m)
}

var xxx_messageInfo_DataTx proto.InternalMessageInfo

func (m *DataTx) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *DataTx) GetTxID() string {
	if m != nil {
		return m.TxID
	}
	return ""
}

func (m *DataTx) GetDBOperations() []*DBOperation {
	if m != nil {
		return m.DBOperations
	}
	return nil
}

type DBOperation struct {
	DBName               string        `protobuf:"bytes,3,opt,name=DB_name,json=DBName,proto3" json:"DB_name,omitempty"`
	DataReads            []*DataRead   `protobuf:"bytes,4,rep,name=data_reads,json=dataReads,proto3" json:"data_reads,omitempty"`
	DataWrites           []*DataWrite  `protobuf:"bytes,5,rep,name=data_writes,json=dataWrites,proto3" json:"data_writes,omitempty"`
	DataDeletes          []*DataDelete `protobuf:"bytes,6,rep,name=data_deletes,json=dataDeletes,proto3" json:"data_deletes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *DBOperation) Reset()         { *m = DBOperation{} }
func (m *DBOperation) String() string { return proto.CompactTextString(m) }
func (*DBOperation) ProtoMessage()    {}
func (*DBOperation) Descriptor() ([]byte, []int) {
	return fileDescriptor_8098d268f52aac08, []int{9}
}

func (m *DBOperation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DBOperation.Unmarshal(m, b)
}
func (m *DBOperation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DBOperation.Marshal(b, m, deterministic)
}
func (m *DBOperation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DBOperation.Merge(m, src)
}
func (m *DBOperation) XXX_Size() int {
	return xxx_messageInfo_DBOperation.Size(m)
}
func (m *DBOperation) XXX_DiscardUnknown() {
	xxx_messageInfo_DBOperation.DiscardUnknown(m)
}

var xxx_messageInfo_DBOperation proto.InternalMessageInfo

func (m *DBOperation) GetDBName() string {
	if m != nil {
		return m.DBName
	}
	return ""
}

func (m *DBOperation) GetDataReads() []*DataRead {
	if m != nil {
		return m.DataReads
	}
	return nil
}

func (m *DBOperation) GetDataWrites() []*DataWrite {
	if m != nil {
		return m.DataWrites
	}
	return nil
}

func (m *DBOperation) GetDataDeletes() []*DataDelete {
	if m != nil {
		return m.DataDeletes
	}
	return nil
}

// DataRead hold a read key and its version
type DataRead struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Version              *Version `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DataRead) Reset()         { *m = DataRead{} }
func (m *DataRead) String() string { return proto.CompactTextString(m) }
func (*DataRead) ProtoMessage()    {}
func (*DataRead) Descriptor() ([]byte, []int) {
	return fileDescriptor_8098d268f52aac08, []int{10}
}

func (m *DataRead) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DataRead.Unmarshal(m, b)
}
func (m *DataRead) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DataRead.Marshal(b, m, deterministic)
}
func (m *DataRead) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DataRead.Merge(m, src)
}
func (m *DataRead) XXX_Size() int {
	return xxx_messageInfo_DataRead.Size(m)
}
func (m *DataRead) XXX_DiscardUnknown() {
	xxx_messageInfo_DataRead.DiscardUnknown(m)
}

var xxx_messageInfo_DataRead proto.InternalMessageInfo

func (m *DataRead) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *DataRead) GetVersion() *Version {
	if m != nil {
		return m.Version
	}
	return nil
}

// DataWrite hold a write including a delete
type DataWrite struct {
	Key                  string         `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value                []byte         `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	ACL                  *AccessControl `protobuf:"bytes,3,opt,name=ACL,proto3" json:"ACL,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *DataWrite) Reset()         { *m = DataWrite{} }
func (m *DataWrite) String() string { return proto.CompactTextString(m) }
func (*DataWrite) ProtoMessage()    {}
func (*DataWrite) Descriptor() ([]byte, []int) {
	return fileDescriptor_8098d268f52aac08, []int{11}
}

func (m *DataWrite) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DataWrite.Unmarshal(m, b)
}
func (m *DataWrite) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DataWrite.Marshal(b, m, deterministic)
}
func (m *DataWrite) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DataWrite.Merge(m, src)
}
func (m *DataWrite) XXX_Size() int {
	return xxx_messageInfo_DataWrite.Size(m)
}
func (m *DataWrite) XXX_DiscardUnknown() {
	xxx_messageInfo_DataWrite.DiscardUnknown(m)
}

var xxx_messageInfo_DataWrite proto.InternalMessageInfo

func (m *DataWrite) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *DataWrite) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *DataWrite) GetACL() *AccessControl {
	if m != nil {
		return m.ACL
	}
	return nil
}

type DataDelete struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DataDelete) Reset()         { *m = DataDelete{} }
func (m *DataDelete) String() string { return proto.CompactTextString(m) }
func (*DataDelete) ProtoMessage()    {}
func (*DataDelete) Descriptor() ([]byte, []int) {
	return fileDescriptor_8098d268f52aac08, []int{12}
}

func (m *DataDelete) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DataDelete.Unmarshal(m, b)
}
func (m *DataDelete) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DataDelete.Marshal(b, m, deterministic)
}
func (m *DataDelete) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DataDelete.Merge(m, src)
}
func (m *DataDelete) XXX_Size() int {
	return xxx_messageInfo_DataDelete.Size(m)
}
func (m *DataDelete) XXX_DiscardUnknown() {
	xxx_messageInfo_DataDelete.DiscardUnknown(m)
}

var xxx_messageInfo_DataDelete proto.InternalMessageInfo

func (m *DataDelete) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type ConfigTx struct {
	UserID               string         `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID,omitempty"`
	TxID                 string         `protobuf:"bytes,2,opt,name=txID,proto3" json:"txID,omitempty"`
	ReadOldConfigVersion *Version       `protobuf:"bytes,3,opt,name=read_old_config_version,json=readOldConfigVersion,proto3" json:"read_old_config_version,omitempty"`
	NewConfig            *ClusterConfig `protobuf:"bytes,4,opt,name=new_config,json=newConfig,proto3" json:"new_config,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ConfigTx) Reset()         { *m = ConfigTx{} }
func (m *ConfigTx) String() string { return proto.CompactTextString(m) }
func (*ConfigTx) ProtoMessage()    {}
func (*ConfigTx) Descriptor() ([]byte, []int) {
	return fileDescriptor_8098d268f52aac08, []int{13}
}

func (m *ConfigTx) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfigTx.Unmarshal(m, b)
}
func (m *ConfigTx) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfigTx.Marshal(b, m, deterministic)
}
func (m *ConfigTx) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfigTx.Merge(m, src)
}
func (m *ConfigTx) XXX_Size() int {
	return xxx_messageInfo_ConfigTx.Size(m)
}
func (m *ConfigTx) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfigTx.DiscardUnknown(m)
}

var xxx_messageInfo_ConfigTx proto.InternalMessageInfo

func (m *ConfigTx) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *ConfigTx) GetTxID() string {
	if m != nil {
		return m.TxID
	}
	return ""
}

func (m *ConfigTx) GetReadOldConfigVersion() *Version {
	if m != nil {
		return m.ReadOldConfigVersion
	}
	return nil
}

func (m *ConfigTx) GetNewConfig() *ClusterConfig {
	if m != nil {
		return m.NewConfig
	}
	return nil
}

type DBAdministrationTx struct {
	UserID               string   `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID,omitempty"`
	TxID                 string   `protobuf:"bytes,2,opt,name=txID,proto3" json:"txID,omitempty"`
	CreateDBs            []string `protobuf:"bytes,3,rep,name=createDBs,proto3" json:"createDBs,omitempty"`
	DeleteDBs            []string `protobuf:"bytes,4,rep,name=deleteDBs,proto3" json:"deleteDBs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DBAdministrationTx) Reset()         { *m = DBAdministrationTx{} }
func (m *DBAdministrationTx) String() string { return proto.CompactTextString(m) }
func (*DBAdministrationTx) ProtoMessage()    {}
func (*DBAdministrationTx) Descriptor() ([]byte, []int) {
	return fileDescriptor_8098d268f52aac08, []int{14}
}

func (m *DBAdministrationTx) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DBAdministrationTx.Unmarshal(m, b)
}
func (m *DBAdministrationTx) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DBAdministrationTx.Marshal(b, m, deterministic)
}
func (m *DBAdministrationTx) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DBAdministrationTx.Merge(m, src)
}
func (m *DBAdministrationTx) XXX_Size() int {
	return xxx_messageInfo_DBAdministrationTx.Size(m)
}
func (m *DBAdministrationTx) XXX_DiscardUnknown() {
	xxx_messageInfo_DBAdministrationTx.DiscardUnknown(m)
}

var xxx_messageInfo_DBAdministrationTx proto.InternalMessageInfo

func (m *DBAdministrationTx) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *DBAdministrationTx) GetTxID() string {
	if m != nil {
		return m.TxID
	}
	return ""
}

func (m *DBAdministrationTx) GetCreateDBs() []string {
	if m != nil {
		return m.CreateDBs
	}
	return nil
}

func (m *DBAdministrationTx) GetDeleteDBs() []string {
	if m != nil {
		return m.DeleteDBs
	}
	return nil
}

type UserAdministrationTx struct {
	UserID               string        `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID,omitempty"`
	TxID                 string        `protobuf:"bytes,2,opt,name=txID,proto3" json:"txID,omitempty"`
	UserReads            []*UserRead   `protobuf:"bytes,3,rep,name=user_reads,json=userReads,proto3" json:"user_reads,omitempty"`
	UserWrites           []*UserWrite  `protobuf:"bytes,4,rep,name=user_writes,json=userWrites,proto3" json:"user_writes,omitempty"`
	UserDeletes          []*UserDelete `protobuf:"bytes,5,rep,name=user_deletes,json=userDeletes,proto3" json:"user_deletes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *UserAdministrationTx) Reset()         { *m = UserAdministrationTx{} }
func (m *UserAdministrationTx) String() string { return proto.CompactTextString(m) }
func (*UserAdministrationTx) ProtoMessage()    {}
func (*UserAdministrationTx) Descriptor() ([]byte, []int) {
	return fileDescriptor_8098d268f52aac08, []int{15}
}

func (m *UserAdministrationTx) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserAdministrationTx.Unmarshal(m, b)
}
func (m *UserAdministrationTx) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserAdministrationTx.Marshal(b, m, deterministic)
}
func (m *UserAdministrationTx) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserAdministrationTx.Merge(m, src)
}
func (m *UserAdministrationTx) XXX_Size() int {
	return xxx_messageInfo_UserAdministrationTx.Size(m)
}
func (m *UserAdministrationTx) XXX_DiscardUnknown() {
	xxx_messageInfo_UserAdministrationTx.DiscardUnknown(m)
}

var xxx_messageInfo_UserAdministrationTx proto.InternalMessageInfo

func (m *UserAdministrationTx) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *UserAdministrationTx) GetTxID() string {
	if m != nil {
		return m.TxID
	}
	return ""
}

func (m *UserAdministrationTx) GetUserReads() []*UserRead {
	if m != nil {
		return m.UserReads
	}
	return nil
}

func (m *UserAdministrationTx) GetUserWrites() []*UserWrite {
	if m != nil {
		return m.UserWrites
	}
	return nil
}

func (m *UserAdministrationTx) GetUserDeletes() []*UserDelete {
	if m != nil {
		return m.UserDeletes
	}
	return nil
}

type UserRead struct {
	UserID               string   `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID,omitempty"`
	Version              *Version `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserRead) Reset()         { *m = UserRead{} }
func (m *UserRead) String() string { return proto.CompactTextString(m) }
func (*UserRead) ProtoMessage()    {}
func (*UserRead) Descriptor() ([]byte, []int) {
	return fileDescriptor_8098d268f52aac08, []int{16}
}

func (m *UserRead) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserRead.Unmarshal(m, b)
}
func (m *UserRead) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserRead.Marshal(b, m, deterministic)
}
func (m *UserRead) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserRead.Merge(m, src)
}
func (m *UserRead) XXX_Size() int {
	return xxx_messageInfo_UserRead.Size(m)
}
func (m *UserRead) XXX_DiscardUnknown() {
	xxx_messageInfo_UserRead.DiscardUnknown(m)
}

var xxx_messageInfo_UserRead proto.InternalMessageInfo

func (m *UserRead) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *UserRead) GetVersion() *Version {
	if m != nil {
		return m.Version
	}
	return nil
}

type UserWrite struct {
	User                 *User          `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	ACL                  *AccessControl `protobuf:"bytes,2,opt,name=ACL,proto3" json:"ACL,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *UserWrite) Reset()         { *m = UserWrite{} }
func (m *UserWrite) String() string { return proto.CompactTextString(m) }
func (*UserWrite) ProtoMessage()    {}
func (*UserWrite) Descriptor() ([]byte, []int) {
	return fileDescriptor_8098d268f52aac08, []int{17}
}

func (m *UserWrite) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserWrite.Unmarshal(m, b)
}
func (m *UserWrite) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserWrite.Marshal(b, m, deterministic)
}
func (m *UserWrite) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserWrite.Merge(m, src)
}
func (m *UserWrite) XXX_Size() int {
	return xxx_messageInfo_UserWrite.Size(m)
}
func (m *UserWrite) XXX_DiscardUnknown() {
	xxx_messageInfo_UserWrite.DiscardUnknown(m)
}

var xxx_messageInfo_UserWrite proto.InternalMessageInfo

func (m *UserWrite) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *UserWrite) GetACL() *AccessControl {
	if m != nil {
		return m.ACL
	}
	return nil
}

type UserDelete struct {
	UserID               string   `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserDelete) Reset()         { *m = UserDelete{} }
func (m *UserDelete) String() string { return proto.CompactTextString(m) }
func (*UserDelete) ProtoMessage()    {}
func (*UserDelete) Descriptor() ([]byte, []int) {
	return fileDescriptor_8098d268f52aac08, []int{18}
}

func (m *UserDelete) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserDelete.Unmarshal(m, b)
}
func (m *UserDelete) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserDelete.Marshal(b, m, deterministic)
}
func (m *UserDelete) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserDelete.Merge(m, src)
}
func (m *UserDelete) XXX_Size() int {
	return xxx_messageInfo_UserDelete.Size(m)
}
func (m *UserDelete) XXX_DiscardUnknown() {
	xxx_messageInfo_UserDelete.DiscardUnknown(m)
}

var xxx_messageInfo_UserDelete proto.InternalMessageInfo

func (m *UserDelete) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

type Metadata struct {
	Version              *Version       `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	AccessControl        *AccessControl `protobuf:"bytes,2,opt,name=access_control,json=accessControl,proto3" json:"access_control,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Metadata) Reset()         { *m = Metadata{} }
func (m *Metadata) String() string { return proto.CompactTextString(m) }
func (*Metadata) ProtoMessage()    {}
func (*Metadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_8098d268f52aac08, []int{19}
}

func (m *Metadata) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Metadata.Unmarshal(m, b)
}
func (m *Metadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Metadata.Marshal(b, m, deterministic)
}
func (m *Metadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Metadata.Merge(m, src)
}
func (m *Metadata) XXX_Size() int {
	return xxx_messageInfo_Metadata.Size(m)
}
func (m *Metadata) XXX_DiscardUnknown() {
	xxx_messageInfo_Metadata.DiscardUnknown(m)
}

var xxx_messageInfo_Metadata proto.InternalMessageInfo

func (m *Metadata) GetVersion() *Version {
	if m != nil {
		return m.Version
	}
	return nil
}

func (m *Metadata) GetAccessControl() *AccessControl {
	if m != nil {
		return m.AccessControl
	}
	return nil
}

type Version struct {
	BlockNum             uint64   `protobuf:"varint,1,opt,name=block_num,json=blockNum,proto3" json:"block_num,omitempty"`
	TxNum                uint64   `protobuf:"varint,2,opt,name=tx_num,json=txNum,proto3" json:"tx_num,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Version) Reset()         { *m = Version{} }
func (m *Version) String() string { return proto.CompactTextString(m) }
func (*Version) ProtoMessage()    {}
func (*Version) Descriptor() ([]byte, []int) {
	return fileDescriptor_8098d268f52aac08, []int{20}
}

func (m *Version) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Version.Unmarshal(m, b)
}
func (m *Version) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Version.Marshal(b, m, deterministic)
}
func (m *Version) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Version.Merge(m, src)
}
func (m *Version) XXX_Size() int {
	return xxx_messageInfo_Version.Size(m)
}
func (m *Version) XXX_DiscardUnknown() {
	xxx_messageInfo_Version.DiscardUnknown(m)
}

var xxx_messageInfo_Version proto.InternalMessageInfo

func (m *Version) GetBlockNum() uint64 {
	if m != nil {
		return m.BlockNum
	}
	return 0
}

func (m *Version) GetTxNum() uint64 {
	if m != nil {
		return m.TxNum
	}
	return 0
}

type AccessControl struct {
	ReadUsers            map[string]bool `protobuf:"bytes,1,rep,name=read_users,json=readUsers,proto3" json:"read_users,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	ReadWriteUsers       map[string]bool `protobuf:"bytes,2,rep,name=read_write_users,json=readWriteUsers,proto3" json:"read_write_users,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *AccessControl) Reset()         { *m = AccessControl{} }
func (m *AccessControl) String() string { return proto.CompactTextString(m) }
func (*AccessControl) ProtoMessage()    {}
func (*AccessControl) Descriptor() ([]byte, []int) {
	return fileDescriptor_8098d268f52aac08, []int{21}
}

func (m *AccessControl) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccessControl.Unmarshal(m, b)
}
func (m *AccessControl) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccessControl.Marshal(b, m, deterministic)
}
func (m *AccessControl) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccessControl.Merge(m, src)
}
func (m *AccessControl) XXX_Size() int {
	return xxx_messageInfo_AccessControl.Size(m)
}
func (m *AccessControl) XXX_DiscardUnknown() {
	xxx_messageInfo_AccessControl.DiscardUnknown(m)
}

var xxx_messageInfo_AccessControl proto.InternalMessageInfo

func (m *AccessControl) GetReadUsers() map[string]bool {
	if m != nil {
		return m.ReadUsers
	}
	return nil
}

func (m *AccessControl) GetReadWriteUsers() map[string]bool {
	if m != nil {
		return m.ReadWriteUsers
	}
	return nil
}

type KVWithMetadata struct {
	Key                  string    `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value                []byte    `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Metadata             *Metadata `protobuf:"bytes,3,opt,name=metadata,proto3" json:"metadata,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *KVWithMetadata) Reset()         { *m = KVWithMetadata{} }
func (m *KVWithMetadata) String() string { return proto.CompactTextString(m) }
func (*KVWithMetadata) ProtoMessage()    {}
func (*KVWithMetadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_8098d268f52aac08, []int{22}
}

func (m *KVWithMetadata) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KVWithMetadata.Unmarshal(m, b)
}
func (m *KVWithMetadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KVWithMetadata.Marshal(b, m, deterministic)
}
func (m *KVWithMetadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KVWithMetadata.Merge(m, src)
}
func (m *KVWithMetadata) XXX_Size() int {
	return xxx_messageInfo_KVWithMetadata.Size(m)
}
func (m *KVWithMetadata) XXX_DiscardUnknown() {
	xxx_messageInfo_KVWithMetadata.DiscardUnknown(m)
}

var xxx_messageInfo_KVWithMetadata proto.InternalMessageInfo

func (m *KVWithMetadata) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *KVWithMetadata) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *KVWithMetadata) GetMetadata() *Metadata {
	if m != nil {
		return m.Metadata
	}
	return nil
}

type ValueWithMetadata struct {
	Value                []byte    `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Metadata             *Metadata `protobuf:"bytes,3,opt,name=metadata,proto3" json:"metadata,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ValueWithMetadata) Reset()         { *m = ValueWithMetadata{} }
func (m *ValueWithMetadata) String() string { return proto.CompactTextString(m) }
func (*ValueWithMetadata) ProtoMessage()    {}
func (*ValueWithMetadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_8098d268f52aac08, []int{23}
}

func (m *ValueWithMetadata) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ValueWithMetadata.Unmarshal(m, b)
}
func (m *ValueWithMetadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ValueWithMetadata.Marshal(b, m, deterministic)
}
func (m *ValueWithMetadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValueWithMetadata.Merge(m, src)
}
func (m *ValueWithMetadata) XXX_Size() int {
	return xxx_messageInfo_ValueWithMetadata.Size(m)
}
func (m *ValueWithMetadata) XXX_DiscardUnknown() {
	xxx_messageInfo_ValueWithMetadata.DiscardUnknown(m)
}

var xxx_messageInfo_ValueWithMetadata proto.InternalMessageInfo

func (m *ValueWithMetadata) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *ValueWithMetadata) GetMetadata() *Metadata {
	if m != nil {
		return m.Metadata
	}
	return nil
}

type Digest struct {
	// Ledger merkle tree root
	RootHash []byte `protobuf:"bytes,1,opt,name=root_hash,json=rootHash,proto3" json:"root_hash,omitempty"`
	// Ledger height
	Height               uint64   `protobuf:"varint,2,opt,name=height,proto3" json:"height,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Digest) Reset()         { *m = Digest{} }
func (m *Digest) String() string { return proto.CompactTextString(m) }
func (*Digest) ProtoMessage()    {}
func (*Digest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8098d268f52aac08, []int{24}
}

func (m *Digest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Digest.Unmarshal(m, b)
}
func (m *Digest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Digest.Marshal(b, m, deterministic)
}
func (m *Digest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Digest.Merge(m, src)
}
func (m *Digest) XXX_Size() int {
	return xxx_messageInfo_Digest.Size(m)
}
func (m *Digest) XXX_DiscardUnknown() {
	xxx_messageInfo_Digest.DiscardUnknown(m)
}

var xxx_messageInfo_Digest proto.InternalMessageInfo

func (m *Digest) GetRootHash() []byte {
	if m != nil {
		return m.RootHash
	}
	return nil
}

func (m *Digest) GetHeight() uint64 {
	if m != nil {
		return m.Height
	}
	return 0
}

type ValidationInfo struct {
	Flag                 Flag     `protobuf:"varint,1,opt,name=flag,proto3,enum=types.Flag" json:"flag,omitempty"`
	ReasonIfInvalid      string   `protobuf:"bytes,2,opt,name=reason_if_invalid,json=reasonIfInvalid,proto3" json:"reason_if_invalid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ValidationInfo) Reset()         { *m = ValidationInfo{} }
func (m *ValidationInfo) String() string { return proto.CompactTextString(m) }
func (*ValidationInfo) ProtoMessage()    {}
func (*ValidationInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_8098d268f52aac08, []int{25}
}

func (m *ValidationInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ValidationInfo.Unmarshal(m, b)
}
func (m *ValidationInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ValidationInfo.Marshal(b, m, deterministic)
}
func (m *ValidationInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValidationInfo.Merge(m, src)
}
func (m *ValidationInfo) XXX_Size() int {
	return xxx_messageInfo_ValidationInfo.Size(m)
}
func (m *ValidationInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ValidationInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ValidationInfo proto.InternalMessageInfo

func (m *ValidationInfo) GetFlag() Flag {
	if m != nil {
		return m.Flag
	}
	return Flag_VALID
}

func (m *ValidationInfo) GetReasonIfInvalid() string {
	if m != nil {
		return m.ReasonIfInvalid
	}
	return ""
}

type TxProof struct {
	Header               *BlockHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Path                 [][]byte     `protobuf:"bytes,2,rep,name=path,proto3" json:"path,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *TxProof) Reset()         { *m = TxProof{} }
func (m *TxProof) String() string { return proto.CompactTextString(m) }
func (*TxProof) ProtoMessage()    {}
func (*TxProof) Descriptor() ([]byte, []int) {
	return fileDescriptor_8098d268f52aac08, []int{26}
}

func (m *TxProof) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TxProof.Unmarshal(m, b)
}
func (m *TxProof) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TxProof.Marshal(b, m, deterministic)
}
func (m *TxProof) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TxProof.Merge(m, src)
}
func (m *TxProof) XXX_Size() int {
	return xxx_messageInfo_TxProof.Size(m)
}
func (m *TxProof) XXX_DiscardUnknown() {
	xxx_messageInfo_TxProof.DiscardUnknown(m)
}

var xxx_messageInfo_TxProof proto.InternalMessageInfo

func (m *TxProof) GetHeader() *BlockHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *TxProof) GetPath() [][]byte {
	if m != nil {
		return m.Path
	}
	return nil
}

type BlockProof struct {
	BlockNumber          uint64         `protobuf:"varint,1,opt,name=block_number,json=blockNumber,proto3" json:"block_number,omitempty"`
	Path                 []*BlockHeader `protobuf:"bytes,2,rep,name=path,proto3" json:"path,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *BlockProof) Reset()         { *m = BlockProof{} }
func (m *BlockProof) String() string { return proto.CompactTextString(m) }
func (*BlockProof) ProtoMessage()    {}
func (*BlockProof) Descriptor() ([]byte, []int) {
	return fileDescriptor_8098d268f52aac08, []int{27}
}

func (m *BlockProof) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockProof.Unmarshal(m, b)
}
func (m *BlockProof) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockProof.Marshal(b, m, deterministic)
}
func (m *BlockProof) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockProof.Merge(m, src)
}
func (m *BlockProof) XXX_Size() int {
	return xxx_messageInfo_BlockProof.Size(m)
}
func (m *BlockProof) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockProof.DiscardUnknown(m)
}

var xxx_messageInfo_BlockProof proto.InternalMessageInfo

func (m *BlockProof) GetBlockNumber() uint64 {
	if m != nil {
		return m.BlockNumber
	}
	return 0
}

func (m *BlockProof) GetPath() []*BlockHeader {
	if m != nil {
		return m.Path
	}
	return nil
}

type TxReceipt struct {
	Header               *BlockHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	TxIndex              uint64       `protobuf:"varint,2,opt,name=tx_index,json=txIndex,proto3" json:"tx_index,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *TxReceipt) Reset()         { *m = TxReceipt{} }
func (m *TxReceipt) String() string { return proto.CompactTextString(m) }
func (*TxReceipt) ProtoMessage()    {}
func (*TxReceipt) Descriptor() ([]byte, []int) {
	return fileDescriptor_8098d268f52aac08, []int{28}
}

func (m *TxReceipt) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TxReceipt.Unmarshal(m, b)
}
func (m *TxReceipt) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TxReceipt.Marshal(b, m, deterministic)
}
func (m *TxReceipt) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TxReceipt.Merge(m, src)
}
func (m *TxReceipt) XXX_Size() int {
	return xxx_messageInfo_TxReceipt.Size(m)
}
func (m *TxReceipt) XXX_DiscardUnknown() {
	xxx_messageInfo_TxReceipt.DiscardUnknown(m)
}

var xxx_messageInfo_TxReceipt proto.InternalMessageInfo

func (m *TxReceipt) GetHeader() *BlockHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *TxReceipt) GetTxIndex() uint64 {
	if m != nil {
		return m.TxIndex
	}
	return 0
}

func init() {
	proto.RegisterEnum("types.Flag", Flag_name, Flag_value)
	proto.RegisterType((*Block)(nil), "types.Block")
	proto.RegisterType((*BlockHeaderBase)(nil), "types.BlockHeaderBase")
	proto.RegisterType((*BlockHeader)(nil), "types.BlockHeader")
	proto.RegisterType((*DataTxEnvelopes)(nil), "types.DataTxEnvelopes")
	proto.RegisterType((*DataTxEnvelope)(nil), "types.DataTxEnvelope")
	proto.RegisterType((*ConfigTxEnvelope)(nil), "types.ConfigTxEnvelope")
	proto.RegisterType((*DBAdministrationTxEnvelope)(nil), "types.DBAdministrationTxEnvelope")
	proto.RegisterType((*UserAdministrationTxEnvelope)(nil), "types.UserAdministrationTxEnvelope")
	proto.RegisterType((*DataTx)(nil), "types.DataTx")
	proto.RegisterType((*DBOperation)(nil), "types.DBOperation")
	proto.RegisterType((*DataRead)(nil), "types.DataRead")
	proto.RegisterType((*DataWrite)(nil), "types.DataWrite")
	proto.RegisterType((*DataDelete)(nil), "types.DataDelete")
	proto.RegisterType((*ConfigTx)(nil), "types.ConfigTx")
	proto.RegisterType((*DBAdministrationTx)(nil), "types.DBAdministrationTx")
	proto.RegisterType((*UserAdministrationTx)(nil), "types.UserAdministrationTx")
	proto.RegisterType((*UserRead)(nil), "types.UserRead")
	proto.RegisterType((*UserWrite)(nil), "types.UserWrite")
	proto.RegisterType((*UserDelete)(nil), "types.UserDelete")
	proto.RegisterType((*Metadata)(nil), "types.Metadata")
	proto.RegisterType((*Version)(nil), "types.Version")
	proto.RegisterType((*AccessControl)(nil), "types.AccessControl")
	proto.RegisterMapType((map[string]bool)(nil), "types.AccessControl.ReadUsersEntry")
	proto.RegisterMapType((map[string]bool)(nil), "types.AccessControl.ReadWriteUsersEntry")
	proto.RegisterType((*KVWithMetadata)(nil), "types.KVWithMetadata")
	proto.RegisterType((*ValueWithMetadata)(nil), "types.ValueWithMetadata")
	proto.RegisterType((*Digest)(nil), "types.Digest")
	proto.RegisterType((*ValidationInfo)(nil), "types.ValidationInfo")
	proto.RegisterType((*TxProof)(nil), "types.TxProof")
	proto.RegisterType((*BlockProof)(nil), "types.BlockProof")
	proto.RegisterType((*TxReceipt)(nil), "types.TxReceipt")
}

func init() { proto.RegisterFile("block_and_transaction.proto", fileDescriptor_8098d268f52aac08) }

var fileDescriptor_8098d268f52aac08 = []byte{
	// 1542 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x57, 0xed, 0x6e, 0xdb, 0xbc,
	0x15, 0xae, 0x3f, 0x63, 0x1d, 0xa7, 0xb6, 0xc3, 0x37, 0x1f, 0xce, 0x47, 0xd7, 0x56, 0x1d, 0xba,
	0x34, 0x1b, 0x1c, 0xac, 0xd9, 0xda, 0x7d, 0xb4, 0x03, 0x6c, 0xcb, 0x59, 0x84, 0x26, 0x76, 0x41,
	0xab, 0xc9, 0xb0, 0x62, 0x10, 0x68, 0x8b, 0xb6, 0x85, 0xc8, 0x92, 0x27, 0xd1, 0xa9, 0x03, 0xec,
	0x7e, 0xb6, 0xdf, 0xbb, 0x81, 0xdd, 0xc6, 0x80, 0xfd, 0xdb, 0xaf, 0x5d, 0xc6, 0x40, 0x8a, 0xb2,
	0x2d, 0xc7, 0x71, 0x93, 0xf7, 0x1f, 0xc9, 0x73, 0x9e, 0xe7, 0x1c, 0x92, 0xcf, 0x39, 0xa2, 0x60,
	0xbf, 0xe3, 0x78, 0xdd, 0x6b, 0x93, 0xb8, 0x96, 0xc9, 0x7c, 0xe2, 0x06, 0xa4, 0xcb, 0x6c, 0xcf,
	0xad, 0x8c, 0x7c, 0x8f, 0x79, 0x28, 0xc3, 0x6e, 0x47, 0x34, 0xd8, 0xfb, 0xa1, 0xeb, 0xb9, 0x3d,
	0xbb, 0x3f, 0xf6, 0xc9, 0xcc, 0xa6, 0xfe, 0x2f, 0x05, 0x99, 0x1a, 0xc7, 0xa2, 0x23, 0xc8, 0x0e,
	0x28, 0xb1, 0xa8, 0x5f, 0x4e, 0xbc, 0x48, 0x1c, 0xe6, 0xdf, 0xa2, 0x8a, 0x80, 0x55, 0x84, 0xf5,
	0x4c, 0x58, 0xb0, 0xf4, 0x40, 0x1a, 0x6c, 0x58, 0x84, 0x11, 0x93, 0x4d, 0x4c, 0xea, 0xde, 0x50,
	0xc7, 0x1b, 0xd1, 0xa0, 0x9c, 0x14, 0xb0, 0x6d, 0x09, 0xd3, 0x08, 0x23, 0xc6, 0xa4, 0x11, 0x59,
	0xcf, 0x9e, 0xe0, 0xa2, 0x15, 0x5f, 0x42, 0x7f, 0x04, 0x14, 0xa6, 0x34, 0xcf, 0x53, 0x4e, 0x09,
	0x9a, 0x1d, 0x49, 0x53, 0x17, 0x0e, 0x33, 0xd4, 0xd9, 0x13, 0x5c, 0xea, 0x2e, 0xac, 0xa1, 0x1e,
	0x3c, 0xd3, 0x6a, 0x26, 0xb1, 0x86, 0xb6, 0x6b, 0x07, 0x2c, 0xdc, 0x5f, 0x8c, 0x33, 0x2d, 0x38,
	0x5f, 0x46, 0xa9, 0xd5, 0xaa, 0x31, 0xd7, 0x18, 0xfb, 0xde, 0xfd, 0x56, 0xe4, 0xc0, 0xf3, 0x71,
	0x40, 0xfd, 0x55, 0x91, 0x32, 0x22, 0xd2, 0x2b, 0x19, 0xe9, 0x4b, 0x40, 0xfd, 0x15, 0xb1, 0x0e,
	0xc6, 0x2b, 0xec, 0xa8, 0x0e, 0x88, 0x4d, 0xcc, 0x1b, 0xe2, 0xd8, 0x56, 0x18, 0xc7, 0x76, 0x7b,
	0x5e, 0x39, 0xfb, 0x22, 0x75, 0x98, 0x7f, 0xbb, 0x25, 0x03, 0x5c, 0x4e, 0xad, 0xba, 0xdb, 0xf3,
	0x70, 0x89, 0x4d, 0xe2, 0x2b, 0x35, 0x05, 0xd6, 0x3e, 0x93, 0x5b, 0xc7, 0x23, 0x96, 0xfa, 0xef,
	0x04, 0x14, 0xe7, 0x2e, 0xb3, 0x46, 0x02, 0x8a, 0xb6, 0x21, 0xeb, 0x8e, 0x87, 0x1d, 0x79, 0xe9,
	0x69, 0x2c, 0x67, 0xe8, 0xb7, 0xb0, 0x3b, 0xf2, 0xe9, 0x8d, 0xed, 0x8d, 0x03, 0xb3, 0x43, 0x02,
	0x6a, 0x86, 0x17, 0x6f, 0x0e, 0x48, 0x30, 0x10, 0x17, 0xbd, 0x8e, 0xb7, 0x23, 0x07, 0x4e, 0x14,
	0x52, 0x9e, 0x91, 0x60, 0xc0, 0xa1, 0x0e, 0x09, 0x98, 0xd9, 0xf5, 0x86, 0x43, 0x9b, 0x31, 0x6a,
	0x99, 0xa1, 0x36, 0x05, 0x34, 0x15, 0x42, 0xb9, 0x43, 0x3d, 0xb2, 0x87, 0x39, 0x71, 0xe8, 0x7b,
	0x28, 0x2f, 0x85, 0xba, 0xe3, 0xa1, 0xb8, 0xc2, 0x34, 0xde, 0xba, 0x8b, 0x6c, 0x8e, 0x87, 0xea,
	0xdf, 0x93, 0x90, 0x9f, 0xdb, 0x1a, 0x7a, 0x0f, 0xf9, 0xb9, 0xac, 0xa5, 0xa0, 0xb7, 0xef, 0x0a,
	0x9a, 0xa7, 0x8e, 0xa1, 0x33, 0xdd, 0x00, 0x7a, 0x03, 0xa5, 0xe0, 0xda, 0x1e, 0x75, 0x07, 0xc4,
	0x76, 0x45, 0xc6, 0x42, 0xd7, 0xa9, 0xc3, 0x75, 0x5c, 0x9c, 0xae, 0x9f, 0x89, 0x65, 0xf4, 0x0e,
	0xca, 0x6c, 0x62, 0x0e, 0xa9, 0x7f, 0x4d, 0x1d, 0x93, 0xf9, 0x94, 0x9a, 0xbe, 0xe7, 0xb1, 0xf9,
	0x6d, 0x6e, 0xb2, 0xc9, 0x85, 0x30, 0x1b, 0x3e, 0xa5, 0xd8, 0xf3, 0x98, 0xd8, 0xe4, 0x07, 0xd8,
	0x0f, 0x18, 0x61, 0xf4, 0x1e, 0x68, 0x5a, 0x40, 0x77, 0x84, 0xcb, 0x12, 0xf4, 0x1f, 0xa0, 0xb8,
	0xa8, 0x88, 0xcc, 0x2a, 0x45, 0x14, 0x6e, 0x62, 0x73, 0xf5, 0x14, 0x8a, 0x0b, 0x95, 0x89, 0x4e,
	0x40, 0x99, 0x15, 0x71, 0x22, 0x46, 0x16, 0x77, 0xc5, 0x33, 0x3f, 0xf5, 0x0a, 0x0a, 0x71, 0x23,
	0xfa, 0x19, 0xac, 0x8d, 0x42, 0xa5, 0xc9, 0xf3, 0x7e, 0x1a, 0x23, 0xc1, 0x91, 0x15, 0x1d, 0x80,
	0x12, 0xd8, 0x7d, 0x97, 0xb0, 0xb1, 0x4f, 0xa5, 0x96, 0x66, 0x0b, 0xea, 0x57, 0x28, 0x2d, 0xd6,
	0x3c, 0x7a, 0xb3, 0x48, 0x5d, 0x5c, 0xe8, 0x0e, 0x0f, 0x25, 0xf7, 0x60, 0x55, 0x79, 0x9f, 0x2c,
	0x86, 0xd9, 0xbd, 0xb7, 0x61, 0x3c, 0x34, 0x60, 0x00, 0x07, 0xab, 0x7a, 0x00, 0xfa, 0xf5, 0x62,
	0xc8, 0xfd, 0x15, 0x9d, 0xe3, 0xa1, 0x41, 0x1d, 0xc8, 0x86, 0x67, 0xce, 0xcb, 0x9b, 0xb7, 0x18,
	0x5d, 0x13, 0xec, 0x0a, 0x96, 0x33, 0x84, 0x20, 0xcd, 0x26, 0xba, 0x26, 0xa0, 0x0a, 0x16, 0x63,
	0xf4, 0x0e, 0xd6, 0xb5, 0x5a, 0x6b, 0x44, 0xc3, 0x68, 0x41, 0x39, 0x25, 0x94, 0x80, 0xa6, 0x47,
	0x30, 0x35, 0xe1, 0x98, 0x9f, 0xfa, 0xaf, 0x04, 0xe4, 0xe7, 0x16, 0xd0, 0x0e, 0xac, 0x69, 0x35,
	0xd3, 0x25, 0xc3, 0xb0, 0x95, 0x2b, 0x38, 0xab, 0xd5, 0x9a, 0x64, 0x48, 0x51, 0x05, 0x40, 0x7c,
	0x34, 0x7c, 0x4a, 0xac, 0xa0, 0x9c, 0x16, 0xf4, 0xc5, 0x39, 0x8d, 0x60, 0x4a, 0x2c, 0xac, 0x58,
	0x72, 0x14, 0xa0, 0x5f, 0x42, 0x5e, 0xf8, 0x7f, 0xf3, 0x6d, 0x46, 0x03, 0x29, 0xf3, 0xd2, 0x1c,
	0xe0, 0x8a, 0x1b, 0xb0, 0x20, 0x15, 0xc3, 0x00, 0xfd, 0x0a, 0xd6, 0x05, 0xc4, 0xa2, 0x0e, 0xe5,
	0x98, 0xb0, 0x59, 0x6e, 0xcc, 0x61, 0x34, 0x61, 0xc1, 0x82, 0x39, 0x1c, 0x07, 0xea, 0x29, 0xe4,
	0xa2, 0xf8, 0xa8, 0x04, 0xa9, 0x6b, 0x7a, 0x2b, 0x8f, 0x8b, 0x0f, 0xd1, 0x21, 0xac, 0xdd, 0x50,
	0x3f, 0xb0, 0x3d, 0x57, 0x7e, 0xe1, 0x0a, 0x51, 0xa5, 0x85, 0xab, 0x38, 0x32, 0xab, 0x5f, 0x41,
	0x99, 0xa6, 0xb5, 0x84, 0x68, 0x13, 0x32, 0x37, 0xc4, 0x19, 0x47, 0x17, 0x16, 0x4e, 0xd0, 0x6b,
	0x48, 0x55, 0xeb, 0xe7, 0xf2, 0xab, 0xb7, 0x29, 0xa9, 0xab, 0xdd, 0x2e, 0x0d, 0x82, 0xba, 0xe7,
	0x32, 0xdf, 0x73, 0x30, 0x77, 0x50, 0x7f, 0x02, 0x30, 0xcb, 0xff, 0x2e, 0xbb, 0xfa, 0xcf, 0x04,
	0xe4, 0xa2, 0x72, 0x78, 0xd4, 0xbd, 0x37, 0x60, 0x87, 0xdf, 0x88, 0xe9, 0x39, 0x96, 0x29, 0x3f,
	0xc7, 0xd1, 0x7e, 0x53, 0x4b, 0xf7, 0xbb, 0xc9, 0xdd, 0x5b, 0x8e, 0x15, 0x46, 0x93, 0xab, 0xe8,
	0x04, 0xc0, 0xa5, 0xdf, 0x24, 0x83, 0xfc, 0xe0, 0x46, 0xdb, 0xa9, 0x3b, 0xe3, 0x80, 0x51, 0x3f,
	0x04, 0x60, 0xc5, 0xa5, 0xdf, 0xc2, 0xa1, 0xfa, 0x37, 0x40, 0x77, 0x6b, 0xeb, 0x51, 0xd9, 0x1f,
	0x80, 0xd2, 0xf5, 0x29, 0x61, 0x54, 0xab, 0x85, 0x92, 0x55, 0xf0, 0x6c, 0x81, 0x5b, 0x43, 0x29,
	0x70, 0x6b, 0x3a, 0xb4, 0x4e, 0x17, 0xd4, 0xff, 0x24, 0x60, 0x73, 0x59, 0x9d, 0x3d, 0x2a, 0x81,
	0x0a, 0x80, 0x78, 0x13, 0x84, 0xaa, 0x4e, 0xc5, 0x54, 0xcd, 0xc9, 0x43, 0x55, 0x8f, 0xe5, 0x48,
	0xa8, 0x5a, 0xf8, 0x4b, 0x55, 0xa7, 0x63, 0xaa, 0xe6, 0x00, 0xa9, 0xea, 0x71, 0x34, 0x14, 0xaa,
	0x16, 0x90, 0x48, 0xd5, 0x99, 0x98, 0xaa, 0x39, 0x26, 0x52, 0xf5, 0x78, 0x3a, 0x0e, 0xd4, 0x73,
	0xc8, 0x45, 0xf1, 0xef, 0xdd, 0xd0, 0xc3, 0xb5, 0x6d, 0x80, 0x32, 0x4d, 0x0e, 0x3d, 0x87, 0x34,
	0x27, 0x90, 0x2d, 0x2b, 0x3f, 0xbf, 0x5b, 0x61, 0x88, 0x44, 0x9d, 0xfc, 0x9e, 0xa8, 0x7f, 0x0a,
	0x30, 0x4b, 0xff, 0xbe, 0x2c, 0xd5, 0xbf, 0x42, 0xee, 0x82, 0x32, 0xc2, 0x4b, 0x76, 0x3e, 0xe3,
	0xc4, 0xca, 0x8c, 0xd1, 0xef, 0xa1, 0x40, 0x44, 0x44, 0xae, 0x49, 0x1e, 0x72, 0x65, 0x3a, 0x4f,
	0xc9, 0xfc, 0x54, 0xfd, 0x08, 0x6b, 0x91, 0xb0, 0xf7, 0x41, 0x99, 0xbd, 0x42, 0xc2, 0x57, 0x52,
	0xae, 0x23, 0x1f, 0x1e, 0x68, 0x0b, 0xb2, 0x6c, 0x22, 0x2c, 0x49, 0x61, 0xc9, 0xb0, 0x09, 0x7f,
	0x8f, 0xfc, 0x23, 0x09, 0x4f, 0x63, 0xfc, 0xa8, 0x06, 0x20, 0xaa, 0x8c, 0x6f, 0x29, 0xfa, 0xca,
	0xbe, 0x5a, 0x96, 0x49, 0x85, 0x5f, 0x18, 0x3f, 0x94, 0xa0, 0xe1, 0x32, 0xff, 0x16, 0x2b, 0x7e,
	0x34, 0x47, 0x18, 0x4a, 0x82, 0x43, 0x48, 0x47, 0x32, 0x25, 0x05, 0xd3, 0xe1, 0xbd, 0x4c, 0xe2,
	0xc2, 0xe6, 0xe8, 0x0a, 0x7e, 0x6c, 0x71, 0xef, 0x03, 0x14, 0xe2, 0x01, 0xbf, 0xd7, 0xb8, 0x72,
	0xb2, 0x71, 0xfd, 0x2e, 0xf9, 0x9b, 0xc4, 0x5e, 0x15, 0x7e, 0x58, 0x12, 0xe4, 0x31, 0x14, 0x2a,
	0x85, 0xc2, 0xa7, 0xcb, 0x2b, 0x9b, 0x0d, 0xa6, 0x57, 0xfc, 0xd0, 0xce, 0xf9, 0x73, 0xc8, 0x0d,
	0x25, 0x46, 0x76, 0xaa, 0xa8, 0xee, 0x22, 0x2a, 0x3c, 0x75, 0x50, 0x2f, 0x61, 0xe3, 0x92, 0xa3,
	0x62, 0x91, 0xa6, 0xbc, 0x89, 0x1f, 0xcd, 0xfb, 0x11, 0xb2, 0x9a, 0xdd, 0xa7, 0x01, 0xe3, 0x3a,
	0x99, 0xbd, 0xe2, 0x42, 0xc2, 0x9c, 0x1f, 0x3d, 0xdb, 0xb6, 0xf9, 0xcf, 0x95, 0xdd, 0x1f, 0x30,
	0xa9, 0x13, 0x39, 0x53, 0xff, 0x02, 0x85, 0xf8, 0x83, 0x8d, 0xd7, 0x56, 0xcf, 0x21, 0x7d, 0xc1,
	0x50, 0x98, 0xd6, 0xd6, 0xa9, 0x43, 0xfa, 0x58, 0x18, 0xd0, 0x11, 0x6c, 0xf8, 0x94, 0x04, 0xfc,
	0xf5, 0xd7, 0x33, 0x6d, 0x57, 0xbc, 0xef, 0x64, 0x47, 0x2a, 0x86, 0x06, 0xbd, 0xa7, 0x87, 0xcb,
	0xaa, 0x0e, 0x6b, 0xc6, 0xe4, 0xb3, 0xef, 0x79, 0xbd, 0x47, 0xfd, 0xde, 0x21, 0x48, 0x8f, 0x08,
	0x1b, 0xc8, 0x97, 0xaf, 0x18, 0xab, 0x57, 0x00, 0xc2, 0x35, 0x64, 0x7b, 0x09, 0xeb, 0xd3, 0xa2,
	0x98, 0xfd, 0x3d, 0xe4, 0xa3, 0xba, 0xe8, 0x88, 0x1e, 0x30, 0x23, 0x59, 0x1e, 0x2e, 0x24, 0xc6,
	0xa0, 0x18, 0x13, 0x4c, 0xbb, 0xd4, 0x1e, 0xb1, 0x47, 0x65, 0xb9, 0x0b, 0x39, 0x36, 0x31, 0x6d,
	0xd7, 0xa2, 0x13, 0x79, 0xaa, 0x6b, 0x6c, 0xa2, 0xf3, 0xe9, 0xd1, 0x7f, 0x13, 0x90, 0xe6, 0x47,
	0x86, 0x14, 0xc8, 0x5c, 0x56, 0xcf, 0x75, 0xad, 0xf4, 0x04, 0xbd, 0x06, 0x55, 0x6f, 0x8a, 0x89,
	0x79, 0x71, 0x59, 0xaf, 0x9b, 0xf5, 0x56, 0xf3, 0xf4, 0x5c, 0xaf, 0x1b, 0xe6, 0x95, 0x6e, 0x9c,
	0xe9, 0x4d, 0xb3, 0x76, 0xde, 0xaa, 0x7f, 0x2a, 0x25, 0x50, 0x05, 0x8e, 0xee, 0xf7, 0x33, 0xeb,
	0xad, 0x8b, 0x0b, 0xdd, 0x30, 0x1a, 0x9a, 0xd9, 0x36, 0xaa, 0x46, 0xa3, 0x94, 0x44, 0xaf, 0xe0,
	0x79, 0xe4, 0xaf, 0x55, 0x8d, 0x6a, 0xad, 0xda, 0x6e, 0x98, 0x5a, 0xab, 0xd1, 0x36, 0x9b, 0x2d,
	0xc3, 0x6c, 0xfc, 0x49, 0x6f, 0x1b, 0xa5, 0x14, 0xda, 0x85, 0xad, 0xc8, 0xa9, 0xd9, 0x32, 0x3f,
	0x37, 0xf0, 0x85, 0xde, 0x6e, 0xeb, 0xad, 0x66, 0x29, 0x8d, 0x9e, 0xc1, 0x6e, 0x64, 0xd2, 0x9b,
	0xf5, 0x16, 0xc6, 0x8d, 0xba, 0x61, 0x36, 0x9a, 0x06, 0xd6, 0x1b, 0xed, 0x52, 0x06, 0x95, 0x61,
	0x33, 0x32, 0x7f, 0x69, 0x56, 0xbf, 0x18, 0x67, 0x2d, 0xac, 0xb7, 0x1b, 0x5a, 0x29, 0x5b, 0xab,
	0xfc, 0xf9, 0x17, 0x7d, 0x9b, 0x0d, 0xc6, 0x9d, 0x8a, 0xdd, 0x19, 0x56, 0xba, 0xde, 0xf0, 0x58,
	0x1c, 0xbf, 0xf8, 0x47, 0xb1, 0x3a, 0xc7, 0x01, 0xf5, 0x6f, 0xa8, 0x7f, 0x3c, 0xba, 0xee, 0x1f,
	0x8b, 0x33, 0xec, 0x64, 0xc5, 0x1f, 0xff, 0xc9, 0xff, 0x03, 0x00, 0x00, 0xff, 0xff, 0x9c, 0x6d,
	0xe9, 0xae, 0x2c, 0x10, 0x00, 0x00,
}
