// Code generated by protoc-gen-go. DO NOT EDIT.
// source: provenance.proto

package types

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type TxProof struct {
	Header               *BlockHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Path                 [][]byte     `protobuf:"bytes,2,rep,name=path,proto3" json:"path,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *TxProof) Reset()         { *m = TxProof{} }
func (m *TxProof) String() string { return proto.CompactTextString(m) }
func (*TxProof) ProtoMessage()    {}
func (*TxProof) Descriptor() ([]byte, []int) {
	return fileDescriptor_fd9885392b6ac305, []int{0}
}

func (m *TxProof) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TxProof.Unmarshal(m, b)
}
func (m *TxProof) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TxProof.Marshal(b, m, deterministic)
}
func (m *TxProof) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TxProof.Merge(m, src)
}
func (m *TxProof) XXX_Size() int {
	return xxx_messageInfo_TxProof.Size(m)
}
func (m *TxProof) XXX_DiscardUnknown() {
	xxx_messageInfo_TxProof.DiscardUnknown(m)
}

var xxx_messageInfo_TxProof proto.InternalMessageInfo

func (m *TxProof) GetHeader() *BlockHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *TxProof) GetPath() [][]byte {
	if m != nil {
		return m.Path
	}
	return nil
}

type BlockProof struct {
	BlockNumber          uint64         `protobuf:"varint,1,opt,name=block_number,json=blockNumber,proto3" json:"block_number,omitempty"`
	Path                 []*BlockHeader `protobuf:"bytes,2,rep,name=path,proto3" json:"path,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *BlockProof) Reset()         { *m = BlockProof{} }
func (m *BlockProof) String() string { return proto.CompactTextString(m) }
func (*BlockProof) ProtoMessage()    {}
func (*BlockProof) Descriptor() ([]byte, []int) {
	return fileDescriptor_fd9885392b6ac305, []int{1}
}

func (m *BlockProof) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockProof.Unmarshal(m, b)
}
func (m *BlockProof) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockProof.Marshal(b, m, deterministic)
}
func (m *BlockProof) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockProof.Merge(m, src)
}
func (m *BlockProof) XXX_Size() int {
	return xxx_messageInfo_BlockProof.Size(m)
}
func (m *BlockProof) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockProof.DiscardUnknown(m)
}

var xxx_messageInfo_BlockProof proto.InternalMessageInfo

func (m *BlockProof) GetBlockNumber() uint64 {
	if m != nil {
		return m.BlockNumber
	}
	return 0
}

func (m *BlockProof) GetPath() []*BlockHeader {
	if m != nil {
		return m.Path
	}
	return nil
}

type GetBlockQuery struct {
	UserID               string   `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID,omitempty"`
	BlockNumber          uint64   `protobuf:"varint,2,opt,name=block_number,json=blockNumber,proto3" json:"block_number,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBlockQuery) Reset()         { *m = GetBlockQuery{} }
func (m *GetBlockQuery) String() string { return proto.CompactTextString(m) }
func (*GetBlockQuery) ProtoMessage()    {}
func (*GetBlockQuery) Descriptor() ([]byte, []int) {
	return fileDescriptor_fd9885392b6ac305, []int{2}
}

func (m *GetBlockQuery) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBlockQuery.Unmarshal(m, b)
}
func (m *GetBlockQuery) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBlockQuery.Marshal(b, m, deterministic)
}
func (m *GetBlockQuery) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBlockQuery.Merge(m, src)
}
func (m *GetBlockQuery) XXX_Size() int {
	return xxx_messageInfo_GetBlockQuery.Size(m)
}
func (m *GetBlockQuery) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBlockQuery.DiscardUnknown(m)
}

var xxx_messageInfo_GetBlockQuery proto.InternalMessageInfo

func (m *GetBlockQuery) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *GetBlockQuery) GetBlockNumber() uint64 {
	if m != nil {
		return m.BlockNumber
	}
	return 0
}

type GetBlockQueryEnvelope struct {
	Payload              *GetBlockQuery `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	Signature            []byte         `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *GetBlockQueryEnvelope) Reset()         { *m = GetBlockQueryEnvelope{} }
func (m *GetBlockQueryEnvelope) String() string { return proto.CompactTextString(m) }
func (*GetBlockQueryEnvelope) ProtoMessage()    {}
func (*GetBlockQueryEnvelope) Descriptor() ([]byte, []int) {
	return fileDescriptor_fd9885392b6ac305, []int{3}
}

func (m *GetBlockQueryEnvelope) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBlockQueryEnvelope.Unmarshal(m, b)
}
func (m *GetBlockQueryEnvelope) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBlockQueryEnvelope.Marshal(b, m, deterministic)
}
func (m *GetBlockQueryEnvelope) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBlockQueryEnvelope.Merge(m, src)
}
func (m *GetBlockQueryEnvelope) XXX_Size() int {
	return xxx_messageInfo_GetBlockQueryEnvelope.Size(m)
}
func (m *GetBlockQueryEnvelope) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBlockQueryEnvelope.DiscardUnknown(m)
}

var xxx_messageInfo_GetBlockQueryEnvelope proto.InternalMessageInfo

func (m *GetBlockQueryEnvelope) GetPayload() *GetBlockQuery {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *GetBlockQueryEnvelope) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

type GetBlockResponse struct {
	Header               *ResponseHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	BlockHeader          *BlockHeader    `protobuf:"bytes,2,opt,name=blockHeader,proto3" json:"blockHeader,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *GetBlockResponse) Reset()         { *m = GetBlockResponse{} }
func (m *GetBlockResponse) String() string { return proto.CompactTextString(m) }
func (*GetBlockResponse) ProtoMessage()    {}
func (*GetBlockResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fd9885392b6ac305, []int{4}
}

func (m *GetBlockResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBlockResponse.Unmarshal(m, b)
}
func (m *GetBlockResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBlockResponse.Marshal(b, m, deterministic)
}
func (m *GetBlockResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBlockResponse.Merge(m, src)
}
func (m *GetBlockResponse) XXX_Size() int {
	return xxx_messageInfo_GetBlockResponse.Size(m)
}
func (m *GetBlockResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBlockResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetBlockResponse proto.InternalMessageInfo

func (m *GetBlockResponse) GetHeader() *ResponseHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *GetBlockResponse) GetBlockHeader() *BlockHeader {
	if m != nil {
		return m.BlockHeader
	}
	return nil
}

type GetBlockResponseEnvelope struct {
	Payload              *GetBlockResponse `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	Signature            []byte            `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *GetBlockResponseEnvelope) Reset()         { *m = GetBlockResponseEnvelope{} }
func (m *GetBlockResponseEnvelope) String() string { return proto.CompactTextString(m) }
func (*GetBlockResponseEnvelope) ProtoMessage()    {}
func (*GetBlockResponseEnvelope) Descriptor() ([]byte, []int) {
	return fileDescriptor_fd9885392b6ac305, []int{5}
}

func (m *GetBlockResponseEnvelope) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBlockResponseEnvelope.Unmarshal(m, b)
}
func (m *GetBlockResponseEnvelope) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBlockResponseEnvelope.Marshal(b, m, deterministic)
}
func (m *GetBlockResponseEnvelope) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBlockResponseEnvelope.Merge(m, src)
}
func (m *GetBlockResponseEnvelope) XXX_Size() int {
	return xxx_messageInfo_GetBlockResponseEnvelope.Size(m)
}
func (m *GetBlockResponseEnvelope) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBlockResponseEnvelope.DiscardUnknown(m)
}

var xxx_messageInfo_GetBlockResponseEnvelope proto.InternalMessageInfo

func (m *GetBlockResponseEnvelope) GetPayload() *GetBlockResponse {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *GetBlockResponseEnvelope) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

type GetLedgerPathQuery struct {
	UserID               string   `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID,omitempty"`
	StartBlockNumber     uint64   `protobuf:"varint,2,opt,name=start_block_number,json=startBlockNumber,proto3" json:"start_block_number,omitempty"`
	EndBlockNumber       uint64   `protobuf:"varint,3,opt,name=end_block_number,json=endBlockNumber,proto3" json:"end_block_number,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetLedgerPathQuery) Reset()         { *m = GetLedgerPathQuery{} }
func (m *GetLedgerPathQuery) String() string { return proto.CompactTextString(m) }
func (*GetLedgerPathQuery) ProtoMessage()    {}
func (*GetLedgerPathQuery) Descriptor() ([]byte, []int) {
	return fileDescriptor_fd9885392b6ac305, []int{6}
}

func (m *GetLedgerPathQuery) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetLedgerPathQuery.Unmarshal(m, b)
}
func (m *GetLedgerPathQuery) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetLedgerPathQuery.Marshal(b, m, deterministic)
}
func (m *GetLedgerPathQuery) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetLedgerPathQuery.Merge(m, src)
}
func (m *GetLedgerPathQuery) XXX_Size() int {
	return xxx_messageInfo_GetLedgerPathQuery.Size(m)
}
func (m *GetLedgerPathQuery) XXX_DiscardUnknown() {
	xxx_messageInfo_GetLedgerPathQuery.DiscardUnknown(m)
}

var xxx_messageInfo_GetLedgerPathQuery proto.InternalMessageInfo

func (m *GetLedgerPathQuery) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *GetLedgerPathQuery) GetStartBlockNumber() uint64 {
	if m != nil {
		return m.StartBlockNumber
	}
	return 0
}

func (m *GetLedgerPathQuery) GetEndBlockNumber() uint64 {
	if m != nil {
		return m.EndBlockNumber
	}
	return 0
}

type GetLedgerPathQueryEnvelope struct {
	Payload              *GetLedgerPathQuery `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	Signature            []byte              `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *GetLedgerPathQueryEnvelope) Reset()         { *m = GetLedgerPathQueryEnvelope{} }
func (m *GetLedgerPathQueryEnvelope) String() string { return proto.CompactTextString(m) }
func (*GetLedgerPathQueryEnvelope) ProtoMessage()    {}
func (*GetLedgerPathQueryEnvelope) Descriptor() ([]byte, []int) {
	return fileDescriptor_fd9885392b6ac305, []int{7}
}

func (m *GetLedgerPathQueryEnvelope) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetLedgerPathQueryEnvelope.Unmarshal(m, b)
}
func (m *GetLedgerPathQueryEnvelope) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetLedgerPathQueryEnvelope.Marshal(b, m, deterministic)
}
func (m *GetLedgerPathQueryEnvelope) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetLedgerPathQueryEnvelope.Merge(m, src)
}
func (m *GetLedgerPathQueryEnvelope) XXX_Size() int {
	return xxx_messageInfo_GetLedgerPathQueryEnvelope.Size(m)
}
func (m *GetLedgerPathQueryEnvelope) XXX_DiscardUnknown() {
	xxx_messageInfo_GetLedgerPathQueryEnvelope.DiscardUnknown(m)
}

var xxx_messageInfo_GetLedgerPathQueryEnvelope proto.InternalMessageInfo

func (m *GetLedgerPathQueryEnvelope) GetPayload() *GetLedgerPathQuery {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *GetLedgerPathQueryEnvelope) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

type GetLedgerPathResponse struct {
	Header               *ResponseHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	BlockHeaders         []*BlockHeader  `protobuf:"bytes,2,rep,name=blockHeaders,proto3" json:"blockHeaders,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *GetLedgerPathResponse) Reset()         { *m = GetLedgerPathResponse{} }
func (m *GetLedgerPathResponse) String() string { return proto.CompactTextString(m) }
func (*GetLedgerPathResponse) ProtoMessage()    {}
func (*GetLedgerPathResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fd9885392b6ac305, []int{8}
}

func (m *GetLedgerPathResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetLedgerPathResponse.Unmarshal(m, b)
}
func (m *GetLedgerPathResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetLedgerPathResponse.Marshal(b, m, deterministic)
}
func (m *GetLedgerPathResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetLedgerPathResponse.Merge(m, src)
}
func (m *GetLedgerPathResponse) XXX_Size() int {
	return xxx_messageInfo_GetLedgerPathResponse.Size(m)
}
func (m *GetLedgerPathResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetLedgerPathResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetLedgerPathResponse proto.InternalMessageInfo

func (m *GetLedgerPathResponse) GetHeader() *ResponseHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *GetLedgerPathResponse) GetBlockHeaders() []*BlockHeader {
	if m != nil {
		return m.BlockHeaders
	}
	return nil
}

type GetLedgerPathResponseEnvelope struct {
	Payload              *GetLedgerPathResponse `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	Signature            []byte                 `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *GetLedgerPathResponseEnvelope) Reset()         { *m = GetLedgerPathResponseEnvelope{} }
func (m *GetLedgerPathResponseEnvelope) String() string { return proto.CompactTextString(m) }
func (*GetLedgerPathResponseEnvelope) ProtoMessage()    {}
func (*GetLedgerPathResponseEnvelope) Descriptor() ([]byte, []int) {
	return fileDescriptor_fd9885392b6ac305, []int{9}
}

func (m *GetLedgerPathResponseEnvelope) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetLedgerPathResponseEnvelope.Unmarshal(m, b)
}
func (m *GetLedgerPathResponseEnvelope) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetLedgerPathResponseEnvelope.Marshal(b, m, deterministic)
}
func (m *GetLedgerPathResponseEnvelope) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetLedgerPathResponseEnvelope.Merge(m, src)
}
func (m *GetLedgerPathResponseEnvelope) XXX_Size() int {
	return xxx_messageInfo_GetLedgerPathResponseEnvelope.Size(m)
}
func (m *GetLedgerPathResponseEnvelope) XXX_DiscardUnknown() {
	xxx_messageInfo_GetLedgerPathResponseEnvelope.DiscardUnknown(m)
}

var xxx_messageInfo_GetLedgerPathResponseEnvelope proto.InternalMessageInfo

func (m *GetLedgerPathResponseEnvelope) GetPayload() *GetLedgerPathResponse {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *GetLedgerPathResponseEnvelope) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

type GetTxProofQuery struct {
	UserID               string   `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID,omitempty"`
	BlockNumber          uint64   `protobuf:"varint,2,opt,name=block_number,json=blockNumber,proto3" json:"block_number,omitempty"`
	TxIndex              uint64   `protobuf:"varint,3,opt,name=tx_index,json=txIndex,proto3" json:"tx_index,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetTxProofQuery) Reset()         { *m = GetTxProofQuery{} }
func (m *GetTxProofQuery) String() string { return proto.CompactTextString(m) }
func (*GetTxProofQuery) ProtoMessage()    {}
func (*GetTxProofQuery) Descriptor() ([]byte, []int) {
	return fileDescriptor_fd9885392b6ac305, []int{10}
}

func (m *GetTxProofQuery) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTxProofQuery.Unmarshal(m, b)
}
func (m *GetTxProofQuery) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTxProofQuery.Marshal(b, m, deterministic)
}
func (m *GetTxProofQuery) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTxProofQuery.Merge(m, src)
}
func (m *GetTxProofQuery) XXX_Size() int {
	return xxx_messageInfo_GetTxProofQuery.Size(m)
}
func (m *GetTxProofQuery) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTxProofQuery.DiscardUnknown(m)
}

var xxx_messageInfo_GetTxProofQuery proto.InternalMessageInfo

func (m *GetTxProofQuery) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *GetTxProofQuery) GetBlockNumber() uint64 {
	if m != nil {
		return m.BlockNumber
	}
	return 0
}

func (m *GetTxProofQuery) GetTxIndex() uint64 {
	if m != nil {
		return m.TxIndex
	}
	return 0
}

type GetTxProofQueryEnvelope struct {
	Payload              *GetTxProofQuery `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	Signature            []byte           `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *GetTxProofQueryEnvelope) Reset()         { *m = GetTxProofQueryEnvelope{} }
func (m *GetTxProofQueryEnvelope) String() string { return proto.CompactTextString(m) }
func (*GetTxProofQueryEnvelope) ProtoMessage()    {}
func (*GetTxProofQueryEnvelope) Descriptor() ([]byte, []int) {
	return fileDescriptor_fd9885392b6ac305, []int{11}
}

func (m *GetTxProofQueryEnvelope) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTxProofQueryEnvelope.Unmarshal(m, b)
}
func (m *GetTxProofQueryEnvelope) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTxProofQueryEnvelope.Marshal(b, m, deterministic)
}
func (m *GetTxProofQueryEnvelope) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTxProofQueryEnvelope.Merge(m, src)
}
func (m *GetTxProofQueryEnvelope) XXX_Size() int {
	return xxx_messageInfo_GetTxProofQueryEnvelope.Size(m)
}
func (m *GetTxProofQueryEnvelope) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTxProofQueryEnvelope.DiscardUnknown(m)
}

var xxx_messageInfo_GetTxProofQueryEnvelope proto.InternalMessageInfo

func (m *GetTxProofQueryEnvelope) GetPayload() *GetTxProofQuery {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *GetTxProofQueryEnvelope) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

type GetTxProofResponse struct {
	Header               *ResponseHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Hashes               [][]byte        `protobuf:"bytes,2,rep,name=hashes,proto3" json:"hashes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *GetTxProofResponse) Reset()         { *m = GetTxProofResponse{} }
func (m *GetTxProofResponse) String() string { return proto.CompactTextString(m) }
func (*GetTxProofResponse) ProtoMessage()    {}
func (*GetTxProofResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fd9885392b6ac305, []int{12}
}

func (m *GetTxProofResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTxProofResponse.Unmarshal(m, b)
}
func (m *GetTxProofResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTxProofResponse.Marshal(b, m, deterministic)
}
func (m *GetTxProofResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTxProofResponse.Merge(m, src)
}
func (m *GetTxProofResponse) XXX_Size() int {
	return xxx_messageInfo_GetTxProofResponse.Size(m)
}
func (m *GetTxProofResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTxProofResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetTxProofResponse proto.InternalMessageInfo

func (m *GetTxProofResponse) GetHeader() *ResponseHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *GetTxProofResponse) GetHashes() [][]byte {
	if m != nil {
		return m.Hashes
	}
	return nil
}

type GetTxProofResponseEnvelope struct {
	Payload              *GetTxProofResponse `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	Signature            []byte              `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *GetTxProofResponseEnvelope) Reset()         { *m = GetTxProofResponseEnvelope{} }
func (m *GetTxProofResponseEnvelope) String() string { return proto.CompactTextString(m) }
func (*GetTxProofResponseEnvelope) ProtoMessage()    {}
func (*GetTxProofResponseEnvelope) Descriptor() ([]byte, []int) {
	return fileDescriptor_fd9885392b6ac305, []int{13}
}

func (m *GetTxProofResponseEnvelope) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTxProofResponseEnvelope.Unmarshal(m, b)
}
func (m *GetTxProofResponseEnvelope) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTxProofResponseEnvelope.Marshal(b, m, deterministic)
}
func (m *GetTxProofResponseEnvelope) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTxProofResponseEnvelope.Merge(m, src)
}
func (m *GetTxProofResponseEnvelope) XXX_Size() int {
	return xxx_messageInfo_GetTxProofResponseEnvelope.Size(m)
}
func (m *GetTxProofResponseEnvelope) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTxProofResponseEnvelope.DiscardUnknown(m)
}

var xxx_messageInfo_GetTxProofResponseEnvelope proto.InternalMessageInfo

func (m *GetTxProofResponseEnvelope) GetPayload() *GetTxProofResponse {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *GetTxProofResponseEnvelope) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

type GetHistoricalDataQuery struct {
	UserID               string   `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID,omitempty"`
	DBName               string   `protobuf:"bytes,2,opt,name=DBName,proto3" json:"DBName,omitempty"`
	Key                  string   `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`
	Version              *Version `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`
	Direction            string   `protobuf:"bytes,5,opt,name=direction,proto3" json:"direction,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetHistoricalDataQuery) Reset()         { *m = GetHistoricalDataQuery{} }
func (m *GetHistoricalDataQuery) String() string { return proto.CompactTextString(m) }
func (*GetHistoricalDataQuery) ProtoMessage()    {}
func (*GetHistoricalDataQuery) Descriptor() ([]byte, []int) {
	return fileDescriptor_fd9885392b6ac305, []int{14}
}

func (m *GetHistoricalDataQuery) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetHistoricalDataQuery.Unmarshal(m, b)
}
func (m *GetHistoricalDataQuery) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetHistoricalDataQuery.Marshal(b, m, deterministic)
}
func (m *GetHistoricalDataQuery) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetHistoricalDataQuery.Merge(m, src)
}
func (m *GetHistoricalDataQuery) XXX_Size() int {
	return xxx_messageInfo_GetHistoricalDataQuery.Size(m)
}
func (m *GetHistoricalDataQuery) XXX_DiscardUnknown() {
	xxx_messageInfo_GetHistoricalDataQuery.DiscardUnknown(m)
}

var xxx_messageInfo_GetHistoricalDataQuery proto.InternalMessageInfo

func (m *GetHistoricalDataQuery) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *GetHistoricalDataQuery) GetDBName() string {
	if m != nil {
		return m.DBName
	}
	return ""
}

func (m *GetHistoricalDataQuery) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *GetHistoricalDataQuery) GetVersion() *Version {
	if m != nil {
		return m.Version
	}
	return nil
}

func (m *GetHistoricalDataQuery) GetDirection() string {
	if m != nil {
		return m.Direction
	}
	return ""
}

type GetHistoricalDataQueryEnvelope struct {
	Payload              *GetHistoricalDataQuery `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	Signature            []byte                  `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *GetHistoricalDataQueryEnvelope) Reset()         { *m = GetHistoricalDataQueryEnvelope{} }
func (m *GetHistoricalDataQueryEnvelope) String() string { return proto.CompactTextString(m) }
func (*GetHistoricalDataQueryEnvelope) ProtoMessage()    {}
func (*GetHistoricalDataQueryEnvelope) Descriptor() ([]byte, []int) {
	return fileDescriptor_fd9885392b6ac305, []int{15}
}

func (m *GetHistoricalDataQueryEnvelope) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetHistoricalDataQueryEnvelope.Unmarshal(m, b)
}
func (m *GetHistoricalDataQueryEnvelope) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetHistoricalDataQueryEnvelope.Marshal(b, m, deterministic)
}
func (m *GetHistoricalDataQueryEnvelope) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetHistoricalDataQueryEnvelope.Merge(m, src)
}
func (m *GetHistoricalDataQueryEnvelope) XXX_Size() int {
	return xxx_messageInfo_GetHistoricalDataQueryEnvelope.Size(m)
}
func (m *GetHistoricalDataQueryEnvelope) XXX_DiscardUnknown() {
	xxx_messageInfo_GetHistoricalDataQueryEnvelope.DiscardUnknown(m)
}

var xxx_messageInfo_GetHistoricalDataQueryEnvelope proto.InternalMessageInfo

func (m *GetHistoricalDataQueryEnvelope) GetPayload() *GetHistoricalDataQuery {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *GetHistoricalDataQueryEnvelope) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

type GetHistoricalDataResponse struct {
	Header               *ResponseHeader      `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Values               []*ValueWithMetadata `protobuf:"bytes,2,rep,name=values,proto3" json:"values,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *GetHistoricalDataResponse) Reset()         { *m = GetHistoricalDataResponse{} }
func (m *GetHistoricalDataResponse) String() string { return proto.CompactTextString(m) }
func (*GetHistoricalDataResponse) ProtoMessage()    {}
func (*GetHistoricalDataResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fd9885392b6ac305, []int{16}
}

func (m *GetHistoricalDataResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetHistoricalDataResponse.Unmarshal(m, b)
}
func (m *GetHistoricalDataResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetHistoricalDataResponse.Marshal(b, m, deterministic)
}
func (m *GetHistoricalDataResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetHistoricalDataResponse.Merge(m, src)
}
func (m *GetHistoricalDataResponse) XXX_Size() int {
	return xxx_messageInfo_GetHistoricalDataResponse.Size(m)
}
func (m *GetHistoricalDataResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetHistoricalDataResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetHistoricalDataResponse proto.InternalMessageInfo

func (m *GetHistoricalDataResponse) GetHeader() *ResponseHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *GetHistoricalDataResponse) GetValues() []*ValueWithMetadata {
	if m != nil {
		return m.Values
	}
	return nil
}

type GetHistoricalDataResponseEnvelope struct {
	Payload              *GetHistoricalDataResponse `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	Signature            []byte                     `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *GetHistoricalDataResponseEnvelope) Reset()         { *m = GetHistoricalDataResponseEnvelope{} }
func (m *GetHistoricalDataResponseEnvelope) String() string { return proto.CompactTextString(m) }
func (*GetHistoricalDataResponseEnvelope) ProtoMessage()    {}
func (*GetHistoricalDataResponseEnvelope) Descriptor() ([]byte, []int) {
	return fileDescriptor_fd9885392b6ac305, []int{17}
}

func (m *GetHistoricalDataResponseEnvelope) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetHistoricalDataResponseEnvelope.Unmarshal(m, b)
}
func (m *GetHistoricalDataResponseEnvelope) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetHistoricalDataResponseEnvelope.Marshal(b, m, deterministic)
}
func (m *GetHistoricalDataResponseEnvelope) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetHistoricalDataResponseEnvelope.Merge(m, src)
}
func (m *GetHistoricalDataResponseEnvelope) XXX_Size() int {
	return xxx_messageInfo_GetHistoricalDataResponseEnvelope.Size(m)
}
func (m *GetHistoricalDataResponseEnvelope) XXX_DiscardUnknown() {
	xxx_messageInfo_GetHistoricalDataResponseEnvelope.DiscardUnknown(m)
}

var xxx_messageInfo_GetHistoricalDataResponseEnvelope proto.InternalMessageInfo

func (m *GetHistoricalDataResponseEnvelope) GetPayload() *GetHistoricalDataResponse {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *GetHistoricalDataResponseEnvelope) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

type GetDataReadersQuery struct {
	UserID               string   `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID,omitempty"`
	DBName               string   `protobuf:"bytes,2,opt,name=DBName,proto3" json:"DBName,omitempty"`
	Key                  string   `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetDataReadersQuery) Reset()         { *m = GetDataReadersQuery{} }
func (m *GetDataReadersQuery) String() string { return proto.CompactTextString(m) }
func (*GetDataReadersQuery) ProtoMessage()    {}
func (*GetDataReadersQuery) Descriptor() ([]byte, []int) {
	return fileDescriptor_fd9885392b6ac305, []int{18}
}

func (m *GetDataReadersQuery) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDataReadersQuery.Unmarshal(m, b)
}
func (m *GetDataReadersQuery) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDataReadersQuery.Marshal(b, m, deterministic)
}
func (m *GetDataReadersQuery) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDataReadersQuery.Merge(m, src)
}
func (m *GetDataReadersQuery) XXX_Size() int {
	return xxx_messageInfo_GetDataReadersQuery.Size(m)
}
func (m *GetDataReadersQuery) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDataReadersQuery.DiscardUnknown(m)
}

var xxx_messageInfo_GetDataReadersQuery proto.InternalMessageInfo

func (m *GetDataReadersQuery) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *GetDataReadersQuery) GetDBName() string {
	if m != nil {
		return m.DBName
	}
	return ""
}

func (m *GetDataReadersQuery) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type GetDataReadersQueryEnvelope struct {
	Payload              *GetDataReadersQuery `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	Signature            []byte               `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *GetDataReadersQueryEnvelope) Reset()         { *m = GetDataReadersQueryEnvelope{} }
func (m *GetDataReadersQueryEnvelope) String() string { return proto.CompactTextString(m) }
func (*GetDataReadersQueryEnvelope) ProtoMessage()    {}
func (*GetDataReadersQueryEnvelope) Descriptor() ([]byte, []int) {
	return fileDescriptor_fd9885392b6ac305, []int{19}
}

func (m *GetDataReadersQueryEnvelope) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDataReadersQueryEnvelope.Unmarshal(m, b)
}
func (m *GetDataReadersQueryEnvelope) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDataReadersQueryEnvelope.Marshal(b, m, deterministic)
}
func (m *GetDataReadersQueryEnvelope) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDataReadersQueryEnvelope.Merge(m, src)
}
func (m *GetDataReadersQueryEnvelope) XXX_Size() int {
	return xxx_messageInfo_GetDataReadersQueryEnvelope.Size(m)
}
func (m *GetDataReadersQueryEnvelope) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDataReadersQueryEnvelope.DiscardUnknown(m)
}

var xxx_messageInfo_GetDataReadersQueryEnvelope proto.InternalMessageInfo

func (m *GetDataReadersQueryEnvelope) GetPayload() *GetDataReadersQuery {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *GetDataReadersQueryEnvelope) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

type GetDataReadersResponse struct {
	Header               *ResponseHeader   `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	ReadBy               map[string]uint32 `protobuf:"bytes,2,rep,name=read_by,json=readBy,proto3" json:"read_by,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *GetDataReadersResponse) Reset()         { *m = GetDataReadersResponse{} }
func (m *GetDataReadersResponse) String() string { return proto.CompactTextString(m) }
func (*GetDataReadersResponse) ProtoMessage()    {}
func (*GetDataReadersResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fd9885392b6ac305, []int{20}
}

func (m *GetDataReadersResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDataReadersResponse.Unmarshal(m, b)
}
func (m *GetDataReadersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDataReadersResponse.Marshal(b, m, deterministic)
}
func (m *GetDataReadersResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDataReadersResponse.Merge(m, src)
}
func (m *GetDataReadersResponse) XXX_Size() int {
	return xxx_messageInfo_GetDataReadersResponse.Size(m)
}
func (m *GetDataReadersResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDataReadersResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetDataReadersResponse proto.InternalMessageInfo

func (m *GetDataReadersResponse) GetHeader() *ResponseHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *GetDataReadersResponse) GetReadBy() map[string]uint32 {
	if m != nil {
		return m.ReadBy
	}
	return nil
}

type GetDataReadersResponseEnvelope struct {
	Payload              *GetDataReadersResponse `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	Signature            []byte                  `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *GetDataReadersResponseEnvelope) Reset()         { *m = GetDataReadersResponseEnvelope{} }
func (m *GetDataReadersResponseEnvelope) String() string { return proto.CompactTextString(m) }
func (*GetDataReadersResponseEnvelope) ProtoMessage()    {}
func (*GetDataReadersResponseEnvelope) Descriptor() ([]byte, []int) {
	return fileDescriptor_fd9885392b6ac305, []int{21}
}

func (m *GetDataReadersResponseEnvelope) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDataReadersResponseEnvelope.Unmarshal(m, b)
}
func (m *GetDataReadersResponseEnvelope) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDataReadersResponseEnvelope.Marshal(b, m, deterministic)
}
func (m *GetDataReadersResponseEnvelope) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDataReadersResponseEnvelope.Merge(m, src)
}
func (m *GetDataReadersResponseEnvelope) XXX_Size() int {
	return xxx_messageInfo_GetDataReadersResponseEnvelope.Size(m)
}
func (m *GetDataReadersResponseEnvelope) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDataReadersResponseEnvelope.DiscardUnknown(m)
}

var xxx_messageInfo_GetDataReadersResponseEnvelope proto.InternalMessageInfo

func (m *GetDataReadersResponseEnvelope) GetPayload() *GetDataReadersResponse {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *GetDataReadersResponseEnvelope) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

type GetDataWritersQuery struct {
	UserID               string   `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID,omitempty"`
	DBName               string   `protobuf:"bytes,2,opt,name=DBName,proto3" json:"DBName,omitempty"`
	Key                  string   `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetDataWritersQuery) Reset()         { *m = GetDataWritersQuery{} }
func (m *GetDataWritersQuery) String() string { return proto.CompactTextString(m) }
func (*GetDataWritersQuery) ProtoMessage()    {}
func (*GetDataWritersQuery) Descriptor() ([]byte, []int) {
	return fileDescriptor_fd9885392b6ac305, []int{22}
}

func (m *GetDataWritersQuery) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDataWritersQuery.Unmarshal(m, b)
}
func (m *GetDataWritersQuery) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDataWritersQuery.Marshal(b, m, deterministic)
}
func (m *GetDataWritersQuery) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDataWritersQuery.Merge(m, src)
}
func (m *GetDataWritersQuery) XXX_Size() int {
	return xxx_messageInfo_GetDataWritersQuery.Size(m)
}
func (m *GetDataWritersQuery) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDataWritersQuery.DiscardUnknown(m)
}

var xxx_messageInfo_GetDataWritersQuery proto.InternalMessageInfo

func (m *GetDataWritersQuery) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *GetDataWritersQuery) GetDBName() string {
	if m != nil {
		return m.DBName
	}
	return ""
}

func (m *GetDataWritersQuery) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type GetDataWritersQueryEnvelope struct {
	Payload              *GetDataWritersQuery `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	Signature            []byte               `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *GetDataWritersQueryEnvelope) Reset()         { *m = GetDataWritersQueryEnvelope{} }
func (m *GetDataWritersQueryEnvelope) String() string { return proto.CompactTextString(m) }
func (*GetDataWritersQueryEnvelope) ProtoMessage()    {}
func (*GetDataWritersQueryEnvelope) Descriptor() ([]byte, []int) {
	return fileDescriptor_fd9885392b6ac305, []int{23}
}

func (m *GetDataWritersQueryEnvelope) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDataWritersQueryEnvelope.Unmarshal(m, b)
}
func (m *GetDataWritersQueryEnvelope) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDataWritersQueryEnvelope.Marshal(b, m, deterministic)
}
func (m *GetDataWritersQueryEnvelope) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDataWritersQueryEnvelope.Merge(m, src)
}
func (m *GetDataWritersQueryEnvelope) XXX_Size() int {
	return xxx_messageInfo_GetDataWritersQueryEnvelope.Size(m)
}
func (m *GetDataWritersQueryEnvelope) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDataWritersQueryEnvelope.DiscardUnknown(m)
}

var xxx_messageInfo_GetDataWritersQueryEnvelope proto.InternalMessageInfo

func (m *GetDataWritersQueryEnvelope) GetPayload() *GetDataWritersQuery {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *GetDataWritersQueryEnvelope) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

type GetDataWritersResponse struct {
	Header               *ResponseHeader   `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	WrittenBy            map[string]uint32 `protobuf:"bytes,2,rep,name=written_by,json=writtenBy,proto3" json:"written_by,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *GetDataWritersResponse) Reset()         { *m = GetDataWritersResponse{} }
func (m *GetDataWritersResponse) String() string { return proto.CompactTextString(m) }
func (*GetDataWritersResponse) ProtoMessage()    {}
func (*GetDataWritersResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fd9885392b6ac305, []int{24}
}

func (m *GetDataWritersResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDataWritersResponse.Unmarshal(m, b)
}
func (m *GetDataWritersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDataWritersResponse.Marshal(b, m, deterministic)
}
func (m *GetDataWritersResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDataWritersResponse.Merge(m, src)
}
func (m *GetDataWritersResponse) XXX_Size() int {
	return xxx_messageInfo_GetDataWritersResponse.Size(m)
}
func (m *GetDataWritersResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDataWritersResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetDataWritersResponse proto.InternalMessageInfo

func (m *GetDataWritersResponse) GetHeader() *ResponseHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *GetDataWritersResponse) GetWrittenBy() map[string]uint32 {
	if m != nil {
		return m.WrittenBy
	}
	return nil
}

type GetDataWritersResponseEnvelope struct {
	Payload              *GetDataWritersResponse `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	Signature            []byte                  `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *GetDataWritersResponseEnvelope) Reset()         { *m = GetDataWritersResponseEnvelope{} }
func (m *GetDataWritersResponseEnvelope) String() string { return proto.CompactTextString(m) }
func (*GetDataWritersResponseEnvelope) ProtoMessage()    {}
func (*GetDataWritersResponseEnvelope) Descriptor() ([]byte, []int) {
	return fileDescriptor_fd9885392b6ac305, []int{25}
}

func (m *GetDataWritersResponseEnvelope) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDataWritersResponseEnvelope.Unmarshal(m, b)
}
func (m *GetDataWritersResponseEnvelope) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDataWritersResponseEnvelope.Marshal(b, m, deterministic)
}
func (m *GetDataWritersResponseEnvelope) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDataWritersResponseEnvelope.Merge(m, src)
}
func (m *GetDataWritersResponseEnvelope) XXX_Size() int {
	return xxx_messageInfo_GetDataWritersResponseEnvelope.Size(m)
}
func (m *GetDataWritersResponseEnvelope) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDataWritersResponseEnvelope.DiscardUnknown(m)
}

var xxx_messageInfo_GetDataWritersResponseEnvelope proto.InternalMessageInfo

func (m *GetDataWritersResponseEnvelope) GetPayload() *GetDataWritersResponse {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *GetDataWritersResponseEnvelope) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

type GetDataReadByQuery struct {
	UserID               string   `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID,omitempty"`
	TargetUserID         string   `protobuf:"bytes,2,opt,name=target_userID,json=targetUserID,proto3" json:"target_userID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetDataReadByQuery) Reset()         { *m = GetDataReadByQuery{} }
func (m *GetDataReadByQuery) String() string { return proto.CompactTextString(m) }
func (*GetDataReadByQuery) ProtoMessage()    {}
func (*GetDataReadByQuery) Descriptor() ([]byte, []int) {
	return fileDescriptor_fd9885392b6ac305, []int{26}
}

func (m *GetDataReadByQuery) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDataReadByQuery.Unmarshal(m, b)
}
func (m *GetDataReadByQuery) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDataReadByQuery.Marshal(b, m, deterministic)
}
func (m *GetDataReadByQuery) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDataReadByQuery.Merge(m, src)
}
func (m *GetDataReadByQuery) XXX_Size() int {
	return xxx_messageInfo_GetDataReadByQuery.Size(m)
}
func (m *GetDataReadByQuery) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDataReadByQuery.DiscardUnknown(m)
}

var xxx_messageInfo_GetDataReadByQuery proto.InternalMessageInfo

func (m *GetDataReadByQuery) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *GetDataReadByQuery) GetTargetUserID() string {
	if m != nil {
		return m.TargetUserID
	}
	return ""
}

type GetDataReadByQueryEnvelope struct {
	Payload              *GetDataReadByQuery `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	Signature            []byte              `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *GetDataReadByQueryEnvelope) Reset()         { *m = GetDataReadByQueryEnvelope{} }
func (m *GetDataReadByQueryEnvelope) String() string { return proto.CompactTextString(m) }
func (*GetDataReadByQueryEnvelope) ProtoMessage()    {}
func (*GetDataReadByQueryEnvelope) Descriptor() ([]byte, []int) {
	return fileDescriptor_fd9885392b6ac305, []int{27}
}

func (m *GetDataReadByQueryEnvelope) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDataReadByQueryEnvelope.Unmarshal(m, b)
}
func (m *GetDataReadByQueryEnvelope) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDataReadByQueryEnvelope.Marshal(b, m, deterministic)
}
func (m *GetDataReadByQueryEnvelope) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDataReadByQueryEnvelope.Merge(m, src)
}
func (m *GetDataReadByQueryEnvelope) XXX_Size() int {
	return xxx_messageInfo_GetDataReadByQueryEnvelope.Size(m)
}
func (m *GetDataReadByQueryEnvelope) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDataReadByQueryEnvelope.DiscardUnknown(m)
}

var xxx_messageInfo_GetDataReadByQueryEnvelope proto.InternalMessageInfo

func (m *GetDataReadByQueryEnvelope) GetPayload() *GetDataReadByQuery {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *GetDataReadByQueryEnvelope) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

type GetDataReadByResponse struct {
	Header               *ResponseHeader   `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	KVs                  []*KVWithMetadata `protobuf:"bytes,2,rep,name=KVs,proto3" json:"KVs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *GetDataReadByResponse) Reset()         { *m = GetDataReadByResponse{} }
func (m *GetDataReadByResponse) String() string { return proto.CompactTextString(m) }
func (*GetDataReadByResponse) ProtoMessage()    {}
func (*GetDataReadByResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fd9885392b6ac305, []int{28}
}

func (m *GetDataReadByResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDataReadByResponse.Unmarshal(m, b)
}
func (m *GetDataReadByResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDataReadByResponse.Marshal(b, m, deterministic)
}
func (m *GetDataReadByResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDataReadByResponse.Merge(m, src)
}
func (m *GetDataReadByResponse) XXX_Size() int {
	return xxx_messageInfo_GetDataReadByResponse.Size(m)
}
func (m *GetDataReadByResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDataReadByResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetDataReadByResponse proto.InternalMessageInfo

func (m *GetDataReadByResponse) GetHeader() *ResponseHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *GetDataReadByResponse) GetKVs() []*KVWithMetadata {
	if m != nil {
		return m.KVs
	}
	return nil
}

type GetDataReadByResponseEnvelope struct {
	Payload              *GetDataReadByResponse `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	Signature            []byte                 `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *GetDataReadByResponseEnvelope) Reset()         { *m = GetDataReadByResponseEnvelope{} }
func (m *GetDataReadByResponseEnvelope) String() string { return proto.CompactTextString(m) }
func (*GetDataReadByResponseEnvelope) ProtoMessage()    {}
func (*GetDataReadByResponseEnvelope) Descriptor() ([]byte, []int) {
	return fileDescriptor_fd9885392b6ac305, []int{29}
}

func (m *GetDataReadByResponseEnvelope) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDataReadByResponseEnvelope.Unmarshal(m, b)
}
func (m *GetDataReadByResponseEnvelope) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDataReadByResponseEnvelope.Marshal(b, m, deterministic)
}
func (m *GetDataReadByResponseEnvelope) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDataReadByResponseEnvelope.Merge(m, src)
}
func (m *GetDataReadByResponseEnvelope) XXX_Size() int {
	return xxx_messageInfo_GetDataReadByResponseEnvelope.Size(m)
}
func (m *GetDataReadByResponseEnvelope) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDataReadByResponseEnvelope.DiscardUnknown(m)
}

var xxx_messageInfo_GetDataReadByResponseEnvelope proto.InternalMessageInfo

func (m *GetDataReadByResponseEnvelope) GetPayload() *GetDataReadByResponse {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *GetDataReadByResponseEnvelope) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

type GetDataWrittenByQuery struct {
	UserID               string   `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID,omitempty"`
	TargetUserID         string   `protobuf:"bytes,2,opt,name=target_userID,json=targetUserID,proto3" json:"target_userID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetDataWrittenByQuery) Reset()         { *m = GetDataWrittenByQuery{} }
func (m *GetDataWrittenByQuery) String() string { return proto.CompactTextString(m) }
func (*GetDataWrittenByQuery) ProtoMessage()    {}
func (*GetDataWrittenByQuery) Descriptor() ([]byte, []int) {
	return fileDescriptor_fd9885392b6ac305, []int{30}
}

func (m *GetDataWrittenByQuery) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDataWrittenByQuery.Unmarshal(m, b)
}
func (m *GetDataWrittenByQuery) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDataWrittenByQuery.Marshal(b, m, deterministic)
}
func (m *GetDataWrittenByQuery) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDataWrittenByQuery.Merge(m, src)
}
func (m *GetDataWrittenByQuery) XXX_Size() int {
	return xxx_messageInfo_GetDataWrittenByQuery.Size(m)
}
func (m *GetDataWrittenByQuery) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDataWrittenByQuery.DiscardUnknown(m)
}

var xxx_messageInfo_GetDataWrittenByQuery proto.InternalMessageInfo

func (m *GetDataWrittenByQuery) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *GetDataWrittenByQuery) GetTargetUserID() string {
	if m != nil {
		return m.TargetUserID
	}
	return ""
}

type GetDataWrittenByQueryEnvelope struct {
	Payload              *GetDataWrittenByQuery `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	Signature            []byte                 `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *GetDataWrittenByQueryEnvelope) Reset()         { *m = GetDataWrittenByQueryEnvelope{} }
func (m *GetDataWrittenByQueryEnvelope) String() string { return proto.CompactTextString(m) }
func (*GetDataWrittenByQueryEnvelope) ProtoMessage()    {}
func (*GetDataWrittenByQueryEnvelope) Descriptor() ([]byte, []int) {
	return fileDescriptor_fd9885392b6ac305, []int{31}
}

func (m *GetDataWrittenByQueryEnvelope) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDataWrittenByQueryEnvelope.Unmarshal(m, b)
}
func (m *GetDataWrittenByQueryEnvelope) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDataWrittenByQueryEnvelope.Marshal(b, m, deterministic)
}
func (m *GetDataWrittenByQueryEnvelope) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDataWrittenByQueryEnvelope.Merge(m, src)
}
func (m *GetDataWrittenByQueryEnvelope) XXX_Size() int {
	return xxx_messageInfo_GetDataWrittenByQueryEnvelope.Size(m)
}
func (m *GetDataWrittenByQueryEnvelope) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDataWrittenByQueryEnvelope.DiscardUnknown(m)
}

var xxx_messageInfo_GetDataWrittenByQueryEnvelope proto.InternalMessageInfo

func (m *GetDataWrittenByQueryEnvelope) GetPayload() *GetDataWrittenByQuery {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *GetDataWrittenByQueryEnvelope) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

type GetDataWrittenByResponse struct {
	Header               *ResponseHeader   `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	KVs                  []*KVWithMetadata `protobuf:"bytes,2,rep,name=KVs,proto3" json:"KVs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *GetDataWrittenByResponse) Reset()         { *m = GetDataWrittenByResponse{} }
func (m *GetDataWrittenByResponse) String() string { return proto.CompactTextString(m) }
func (*GetDataWrittenByResponse) ProtoMessage()    {}
func (*GetDataWrittenByResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fd9885392b6ac305, []int{32}
}

func (m *GetDataWrittenByResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDataWrittenByResponse.Unmarshal(m, b)
}
func (m *GetDataWrittenByResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDataWrittenByResponse.Marshal(b, m, deterministic)
}
func (m *GetDataWrittenByResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDataWrittenByResponse.Merge(m, src)
}
func (m *GetDataWrittenByResponse) XXX_Size() int {
	return xxx_messageInfo_GetDataWrittenByResponse.Size(m)
}
func (m *GetDataWrittenByResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDataWrittenByResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetDataWrittenByResponse proto.InternalMessageInfo

func (m *GetDataWrittenByResponse) GetHeader() *ResponseHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *GetDataWrittenByResponse) GetKVs() []*KVWithMetadata {
	if m != nil {
		return m.KVs
	}
	return nil
}

type GetDataWrittenByResponseEnvelope struct {
	Payload              *GetDataWrittenByResponse `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	Signature            []byte                    `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *GetDataWrittenByResponseEnvelope) Reset()         { *m = GetDataWrittenByResponseEnvelope{} }
func (m *GetDataWrittenByResponseEnvelope) String() string { return proto.CompactTextString(m) }
func (*GetDataWrittenByResponseEnvelope) ProtoMessage()    {}
func (*GetDataWrittenByResponseEnvelope) Descriptor() ([]byte, []int) {
	return fileDescriptor_fd9885392b6ac305, []int{33}
}

func (m *GetDataWrittenByResponseEnvelope) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDataWrittenByResponseEnvelope.Unmarshal(m, b)
}
func (m *GetDataWrittenByResponseEnvelope) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDataWrittenByResponseEnvelope.Marshal(b, m, deterministic)
}
func (m *GetDataWrittenByResponseEnvelope) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDataWrittenByResponseEnvelope.Merge(m, src)
}
func (m *GetDataWrittenByResponseEnvelope) XXX_Size() int {
	return xxx_messageInfo_GetDataWrittenByResponseEnvelope.Size(m)
}
func (m *GetDataWrittenByResponseEnvelope) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDataWrittenByResponseEnvelope.DiscardUnknown(m)
}

var xxx_messageInfo_GetDataWrittenByResponseEnvelope proto.InternalMessageInfo

func (m *GetDataWrittenByResponseEnvelope) GetPayload() *GetDataWrittenByResponse {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *GetDataWrittenByResponseEnvelope) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

type GetTxIDsSubmittedByQuery struct {
	UserID               string   `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID,omitempty"`
	TargetUserID         string   `protobuf:"bytes,2,opt,name=target_userID,json=targetUserID,proto3" json:"target_userID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetTxIDsSubmittedByQuery) Reset()         { *m = GetTxIDsSubmittedByQuery{} }
func (m *GetTxIDsSubmittedByQuery) String() string { return proto.CompactTextString(m) }
func (*GetTxIDsSubmittedByQuery) ProtoMessage()    {}
func (*GetTxIDsSubmittedByQuery) Descriptor() ([]byte, []int) {
	return fileDescriptor_fd9885392b6ac305, []int{34}
}

func (m *GetTxIDsSubmittedByQuery) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTxIDsSubmittedByQuery.Unmarshal(m, b)
}
func (m *GetTxIDsSubmittedByQuery) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTxIDsSubmittedByQuery.Marshal(b, m, deterministic)
}
func (m *GetTxIDsSubmittedByQuery) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTxIDsSubmittedByQuery.Merge(m, src)
}
func (m *GetTxIDsSubmittedByQuery) XXX_Size() int {
	return xxx_messageInfo_GetTxIDsSubmittedByQuery.Size(m)
}
func (m *GetTxIDsSubmittedByQuery) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTxIDsSubmittedByQuery.DiscardUnknown(m)
}

var xxx_messageInfo_GetTxIDsSubmittedByQuery proto.InternalMessageInfo

func (m *GetTxIDsSubmittedByQuery) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *GetTxIDsSubmittedByQuery) GetTargetUserID() string {
	if m != nil {
		return m.TargetUserID
	}
	return ""
}

type GetTxIDsSubmittedByQueryEnvelope struct {
	Payload              *GetTxIDsSubmittedByQuery `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	Signature            []byte                    `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *GetTxIDsSubmittedByQueryEnvelope) Reset()         { *m = GetTxIDsSubmittedByQueryEnvelope{} }
func (m *GetTxIDsSubmittedByQueryEnvelope) String() string { return proto.CompactTextString(m) }
func (*GetTxIDsSubmittedByQueryEnvelope) ProtoMessage()    {}
func (*GetTxIDsSubmittedByQueryEnvelope) Descriptor() ([]byte, []int) {
	return fileDescriptor_fd9885392b6ac305, []int{35}
}

func (m *GetTxIDsSubmittedByQueryEnvelope) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTxIDsSubmittedByQueryEnvelope.Unmarshal(m, b)
}
func (m *GetTxIDsSubmittedByQueryEnvelope) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTxIDsSubmittedByQueryEnvelope.Marshal(b, m, deterministic)
}
func (m *GetTxIDsSubmittedByQueryEnvelope) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTxIDsSubmittedByQueryEnvelope.Merge(m, src)
}
func (m *GetTxIDsSubmittedByQueryEnvelope) XXX_Size() int {
	return xxx_messageInfo_GetTxIDsSubmittedByQueryEnvelope.Size(m)
}
func (m *GetTxIDsSubmittedByQueryEnvelope) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTxIDsSubmittedByQueryEnvelope.DiscardUnknown(m)
}

var xxx_messageInfo_GetTxIDsSubmittedByQueryEnvelope proto.InternalMessageInfo

func (m *GetTxIDsSubmittedByQueryEnvelope) GetPayload() *GetTxIDsSubmittedByQuery {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *GetTxIDsSubmittedByQueryEnvelope) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

type GetTxIDsSubmittedByResponse struct {
	Header               *ResponseHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	TxIDs                []string        `protobuf:"bytes,2,rep,name=txIDs,proto3" json:"txIDs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *GetTxIDsSubmittedByResponse) Reset()         { *m = GetTxIDsSubmittedByResponse{} }
func (m *GetTxIDsSubmittedByResponse) String() string { return proto.CompactTextString(m) }
func (*GetTxIDsSubmittedByResponse) ProtoMessage()    {}
func (*GetTxIDsSubmittedByResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fd9885392b6ac305, []int{36}
}

func (m *GetTxIDsSubmittedByResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTxIDsSubmittedByResponse.Unmarshal(m, b)
}
func (m *GetTxIDsSubmittedByResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTxIDsSubmittedByResponse.Marshal(b, m, deterministic)
}
func (m *GetTxIDsSubmittedByResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTxIDsSubmittedByResponse.Merge(m, src)
}
func (m *GetTxIDsSubmittedByResponse) XXX_Size() int {
	return xxx_messageInfo_GetTxIDsSubmittedByResponse.Size(m)
}
func (m *GetTxIDsSubmittedByResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTxIDsSubmittedByResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetTxIDsSubmittedByResponse proto.InternalMessageInfo

func (m *GetTxIDsSubmittedByResponse) GetHeader() *ResponseHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *GetTxIDsSubmittedByResponse) GetTxIDs() []string {
	if m != nil {
		return m.TxIDs
	}
	return nil
}

type GetTxIDsSubmittedByResponseEnvelope struct {
	Payload              *GetTxIDsSubmittedByResponse `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	Signature            []byte                       `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-"`
	XXX_unrecognized     []byte                       `json:"-"`
	XXX_sizecache        int32                        `json:"-"`
}

func (m *GetTxIDsSubmittedByResponseEnvelope) Reset()         { *m = GetTxIDsSubmittedByResponseEnvelope{} }
func (m *GetTxIDsSubmittedByResponseEnvelope) String() string { return proto.CompactTextString(m) }
func (*GetTxIDsSubmittedByResponseEnvelope) ProtoMessage()    {}
func (*GetTxIDsSubmittedByResponseEnvelope) Descriptor() ([]byte, []int) {
	return fileDescriptor_fd9885392b6ac305, []int{37}
}

func (m *GetTxIDsSubmittedByResponseEnvelope) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTxIDsSubmittedByResponseEnvelope.Unmarshal(m, b)
}
func (m *GetTxIDsSubmittedByResponseEnvelope) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTxIDsSubmittedByResponseEnvelope.Marshal(b, m, deterministic)
}
func (m *GetTxIDsSubmittedByResponseEnvelope) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTxIDsSubmittedByResponseEnvelope.Merge(m, src)
}
func (m *GetTxIDsSubmittedByResponseEnvelope) XXX_Size() int {
	return xxx_messageInfo_GetTxIDsSubmittedByResponseEnvelope.Size(m)
}
func (m *GetTxIDsSubmittedByResponseEnvelope) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTxIDsSubmittedByResponseEnvelope.DiscardUnknown(m)
}

var xxx_messageInfo_GetTxIDsSubmittedByResponseEnvelope proto.InternalMessageInfo

func (m *GetTxIDsSubmittedByResponseEnvelope) GetPayload() *GetTxIDsSubmittedByResponse {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *GetTxIDsSubmittedByResponseEnvelope) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

type TxReceipt struct {
	Header               *BlockHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	TxIndex              uint64       `protobuf:"varint,2,opt,name=tx_index,json=txIndex,proto3" json:"tx_index,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *TxReceipt) Reset()         { *m = TxReceipt{} }
func (m *TxReceipt) String() string { return proto.CompactTextString(m) }
func (*TxReceipt) ProtoMessage()    {}
func (*TxReceipt) Descriptor() ([]byte, []int) {
	return fileDescriptor_fd9885392b6ac305, []int{38}
}

func (m *TxReceipt) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TxReceipt.Unmarshal(m, b)
}
func (m *TxReceipt) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TxReceipt.Marshal(b, m, deterministic)
}
func (m *TxReceipt) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TxReceipt.Merge(m, src)
}
func (m *TxReceipt) XXX_Size() int {
	return xxx_messageInfo_TxReceipt.Size(m)
}
func (m *TxReceipt) XXX_DiscardUnknown() {
	xxx_messageInfo_TxReceipt.DiscardUnknown(m)
}

var xxx_messageInfo_TxReceipt proto.InternalMessageInfo

func (m *TxReceipt) GetHeader() *BlockHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *TxReceipt) GetTxIndex() uint64 {
	if m != nil {
		return m.TxIndex
	}
	return 0
}

type GetTxReceiptQuery struct {
	UserID               string   `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID,omitempty"`
	TxID                 string   `protobuf:"bytes,2,opt,name=txID,proto3" json:"txID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetTxReceiptQuery) Reset()         { *m = GetTxReceiptQuery{} }
func (m *GetTxReceiptQuery) String() string { return proto.CompactTextString(m) }
func (*GetTxReceiptQuery) ProtoMessage()    {}
func (*GetTxReceiptQuery) Descriptor() ([]byte, []int) {
	return fileDescriptor_fd9885392b6ac305, []int{39}
}

func (m *GetTxReceiptQuery) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTxReceiptQuery.Unmarshal(m, b)
}
func (m *GetTxReceiptQuery) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTxReceiptQuery.Marshal(b, m, deterministic)
}
func (m *GetTxReceiptQuery) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTxReceiptQuery.Merge(m, src)
}
func (m *GetTxReceiptQuery) XXX_Size() int {
	return xxx_messageInfo_GetTxReceiptQuery.Size(m)
}
func (m *GetTxReceiptQuery) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTxReceiptQuery.DiscardUnknown(m)
}

var xxx_messageInfo_GetTxReceiptQuery proto.InternalMessageInfo

func (m *GetTxReceiptQuery) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *GetTxReceiptQuery) GetTxID() string {
	if m != nil {
		return m.TxID
	}
	return ""
}

type GetTxReceiptQueryEnvelope struct {
	Payload              *GetTxReceiptQuery `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	Signature            []byte             `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *GetTxReceiptQueryEnvelope) Reset()         { *m = GetTxReceiptQueryEnvelope{} }
func (m *GetTxReceiptQueryEnvelope) String() string { return proto.CompactTextString(m) }
func (*GetTxReceiptQueryEnvelope) ProtoMessage()    {}
func (*GetTxReceiptQueryEnvelope) Descriptor() ([]byte, []int) {
	return fileDescriptor_fd9885392b6ac305, []int{40}
}

func (m *GetTxReceiptQueryEnvelope) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTxReceiptQueryEnvelope.Unmarshal(m, b)
}
func (m *GetTxReceiptQueryEnvelope) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTxReceiptQueryEnvelope.Marshal(b, m, deterministic)
}
func (m *GetTxReceiptQueryEnvelope) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTxReceiptQueryEnvelope.Merge(m, src)
}
func (m *GetTxReceiptQueryEnvelope) XXX_Size() int {
	return xxx_messageInfo_GetTxReceiptQueryEnvelope.Size(m)
}
func (m *GetTxReceiptQueryEnvelope) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTxReceiptQueryEnvelope.DiscardUnknown(m)
}

var xxx_messageInfo_GetTxReceiptQueryEnvelope proto.InternalMessageInfo

func (m *GetTxReceiptQueryEnvelope) GetPayload() *GetTxReceiptQuery {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *GetTxReceiptQueryEnvelope) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

type GetTxReceiptResponse struct {
	Header               *ResponseHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Receipt              *TxReceipt      `protobuf:"bytes,2,opt,name=receipt,proto3" json:"receipt,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *GetTxReceiptResponse) Reset()         { *m = GetTxReceiptResponse{} }
func (m *GetTxReceiptResponse) String() string { return proto.CompactTextString(m) }
func (*GetTxReceiptResponse) ProtoMessage()    {}
func (*GetTxReceiptResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fd9885392b6ac305, []int{41}
}

func (m *GetTxReceiptResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTxReceiptResponse.Unmarshal(m, b)
}
func (m *GetTxReceiptResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTxReceiptResponse.Marshal(b, m, deterministic)
}
func (m *GetTxReceiptResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTxReceiptResponse.Merge(m, src)
}
func (m *GetTxReceiptResponse) XXX_Size() int {
	return xxx_messageInfo_GetTxReceiptResponse.Size(m)
}
func (m *GetTxReceiptResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTxReceiptResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetTxReceiptResponse proto.InternalMessageInfo

func (m *GetTxReceiptResponse) GetHeader() *ResponseHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *GetTxReceiptResponse) GetReceipt() *TxReceipt {
	if m != nil {
		return m.Receipt
	}
	return nil
}

type GetTxReceiptResponseEnvelope struct {
	Payload              *GetTxReceiptResponse `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	Signature            []byte                `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *GetTxReceiptResponseEnvelope) Reset()         { *m = GetTxReceiptResponseEnvelope{} }
func (m *GetTxReceiptResponseEnvelope) String() string { return proto.CompactTextString(m) }
func (*GetTxReceiptResponseEnvelope) ProtoMessage()    {}
func (*GetTxReceiptResponseEnvelope) Descriptor() ([]byte, []int) {
	return fileDescriptor_fd9885392b6ac305, []int{42}
}

func (m *GetTxReceiptResponseEnvelope) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTxReceiptResponseEnvelope.Unmarshal(m, b)
}
func (m *GetTxReceiptResponseEnvelope) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTxReceiptResponseEnvelope.Marshal(b, m, deterministic)
}
func (m *GetTxReceiptResponseEnvelope) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTxReceiptResponseEnvelope.Merge(m, src)
}
func (m *GetTxReceiptResponseEnvelope) XXX_Size() int {
	return xxx_messageInfo_GetTxReceiptResponseEnvelope.Size(m)
}
func (m *GetTxReceiptResponseEnvelope) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTxReceiptResponseEnvelope.DiscardUnknown(m)
}

var xxx_messageInfo_GetTxReceiptResponseEnvelope proto.InternalMessageInfo

func (m *GetTxReceiptResponseEnvelope) GetPayload() *GetTxReceiptResponse {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *GetTxReceiptResponseEnvelope) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

func init() {
	proto.RegisterType((*TxProof)(nil), "types.TxProof")
	proto.RegisterType((*BlockProof)(nil), "types.BlockProof")
	proto.RegisterType((*GetBlockQuery)(nil), "types.GetBlockQuery")
	proto.RegisterType((*GetBlockQueryEnvelope)(nil), "types.GetBlockQueryEnvelope")
	proto.RegisterType((*GetBlockResponse)(nil), "types.GetBlockResponse")
	proto.RegisterType((*GetBlockResponseEnvelope)(nil), "types.GetBlockResponseEnvelope")
	proto.RegisterType((*GetLedgerPathQuery)(nil), "types.GetLedgerPathQuery")
	proto.RegisterType((*GetLedgerPathQueryEnvelope)(nil), "types.GetLedgerPathQueryEnvelope")
	proto.RegisterType((*GetLedgerPathResponse)(nil), "types.GetLedgerPathResponse")
	proto.RegisterType((*GetLedgerPathResponseEnvelope)(nil), "types.GetLedgerPathResponseEnvelope")
	proto.RegisterType((*GetTxProofQuery)(nil), "types.GetTxProofQuery")
	proto.RegisterType((*GetTxProofQueryEnvelope)(nil), "types.GetTxProofQueryEnvelope")
	proto.RegisterType((*GetTxProofResponse)(nil), "types.GetTxProofResponse")
	proto.RegisterType((*GetTxProofResponseEnvelope)(nil), "types.GetTxProofResponseEnvelope")
	proto.RegisterType((*GetHistoricalDataQuery)(nil), "types.GetHistoricalDataQuery")
	proto.RegisterType((*GetHistoricalDataQueryEnvelope)(nil), "types.GetHistoricalDataQueryEnvelope")
	proto.RegisterType((*GetHistoricalDataResponse)(nil), "types.GetHistoricalDataResponse")
	proto.RegisterType((*GetHistoricalDataResponseEnvelope)(nil), "types.GetHistoricalDataResponseEnvelope")
	proto.RegisterType((*GetDataReadersQuery)(nil), "types.GetDataReadersQuery")
	proto.RegisterType((*GetDataReadersQueryEnvelope)(nil), "types.GetDataReadersQueryEnvelope")
	proto.RegisterType((*GetDataReadersResponse)(nil), "types.GetDataReadersResponse")
	proto.RegisterMapType((map[string]uint32)(nil), "types.GetDataReadersResponse.ReadByEntry")
	proto.RegisterType((*GetDataReadersResponseEnvelope)(nil), "types.GetDataReadersResponseEnvelope")
	proto.RegisterType((*GetDataWritersQuery)(nil), "types.GetDataWritersQuery")
	proto.RegisterType((*GetDataWritersQueryEnvelope)(nil), "types.GetDataWritersQueryEnvelope")
	proto.RegisterType((*GetDataWritersResponse)(nil), "types.GetDataWritersResponse")
	proto.RegisterMapType((map[string]uint32)(nil), "types.GetDataWritersResponse.WrittenByEntry")
	proto.RegisterType((*GetDataWritersResponseEnvelope)(nil), "types.GetDataWritersResponseEnvelope")
	proto.RegisterType((*GetDataReadByQuery)(nil), "types.GetDataReadByQuery")
	proto.RegisterType((*GetDataReadByQueryEnvelope)(nil), "types.GetDataReadByQueryEnvelope")
	proto.RegisterType((*GetDataReadByResponse)(nil), "types.GetDataReadByResponse")
	proto.RegisterType((*GetDataReadByResponseEnvelope)(nil), "types.GetDataReadByResponseEnvelope")
	proto.RegisterType((*GetDataWrittenByQuery)(nil), "types.GetDataWrittenByQuery")
	proto.RegisterType((*GetDataWrittenByQueryEnvelope)(nil), "types.GetDataWrittenByQueryEnvelope")
	proto.RegisterType((*GetDataWrittenByResponse)(nil), "types.GetDataWrittenByResponse")
	proto.RegisterType((*GetDataWrittenByResponseEnvelope)(nil), "types.GetDataWrittenByResponseEnvelope")
	proto.RegisterType((*GetTxIDsSubmittedByQuery)(nil), "types.GetTxIDsSubmittedByQuery")
	proto.RegisterType((*GetTxIDsSubmittedByQueryEnvelope)(nil), "types.GetTxIDsSubmittedByQueryEnvelope")
	proto.RegisterType((*GetTxIDsSubmittedByResponse)(nil), "types.GetTxIDsSubmittedByResponse")
	proto.RegisterType((*GetTxIDsSubmittedByResponseEnvelope)(nil), "types.GetTxIDsSubmittedByResponseEnvelope")
	proto.RegisterType((*TxReceipt)(nil), "types.TxReceipt")
	proto.RegisterType((*GetTxReceiptQuery)(nil), "types.GetTxReceiptQuery")
	proto.RegisterType((*GetTxReceiptQueryEnvelope)(nil), "types.GetTxReceiptQueryEnvelope")
	proto.RegisterType((*GetTxReceiptResponse)(nil), "types.GetTxReceiptResponse")
	proto.RegisterType((*GetTxReceiptResponseEnvelope)(nil), "types.GetTxReceiptResponseEnvelope")
}

func init() { proto.RegisterFile("provenance.proto", fileDescriptor_fd9885392b6ac305) }

var fileDescriptor_fd9885392b6ac305 = []byte{
	// 1121 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x58, 0xeb, 0x6e, 0x1b, 0x45,
	0x14, 0x96, 0x73, 0xb1, 0xf1, 0xc9, 0x05, 0xb3, 0xa4, 0xae, 0xe3, 0xa4, 0x90, 0x6e, 0x25, 0x30,
	0x51, 0x71, 0x4a, 0x5b, 0x0a, 0xad, 0x2a, 0x21, 0x59, 0xa9, 0xdc, 0x10, 0xa8, 0xda, 0x25, 0xc4,
	0x12, 0xfc, 0xb0, 0xc6, 0xde, 0xc1, 0x5e, 0xc5, 0xde, 0x75, 0x66, 0xc7, 0x89, 0x2d, 0x2e, 0x12,
	0x12, 0x4f, 0xc2, 0xc3, 0xf0, 0x00, 0x3c, 0x11, 0xda, 0xb3, 0xb3, 0xb7, 0xf1, 0xda, 0x1a, 0x2f,
	0xc9, 0x3f, 0xcf, 0xd9, 0xf3, 0x7d, 0x67, 0xbe, 0x73, 0xbe, 0xd9, 0x8b, 0xa1, 0x34, 0x62, 0xce,
	0x15, 0xb5, 0x89, 0xdd, 0xa5, 0xf5, 0x11, 0x73, 0xb8, 0xa3, 0xad, 0xf3, 0xe9, 0x88, 0xba, 0xd5,
	0xbd, 0xce, 0xc0, 0xe9, 0x5e, 0xb4, 0x89, 0x6d, 0xb6, 0x39, 0x23, 0xb6, 0x4b, 0xba, 0xdc, 0x72,
	0x6c, 0x3f, 0xa7, 0x5a, 0xb9, 0x1c, 0x53, 0x36, 0xc5, 0x8b, 0x8c, 0xba, 0x23, 0xc7, 0x76, 0x05,
	0x5a, 0x3f, 0x81, 0xc2, 0xd9, 0xe4, 0x2d, 0x73, 0x9c, 0x5f, 0xb4, 0x43, 0xc8, 0xf7, 0x29, 0x31,
	0x29, 0xab, 0xe4, 0x0e, 0x72, 0xb5, 0x8d, 0xc7, 0x5a, 0x1d, 0x99, 0xeb, 0x0d, 0x8f, 0xf8, 0x35,
	0x5e, 0x31, 0x44, 0x86, 0xa6, 0xc1, 0xda, 0x88, 0xf0, 0x7e, 0x65, 0xe5, 0x60, 0xb5, 0xb6, 0x69,
	0xe0, 0x6f, 0xbd, 0x05, 0x80, 0xa9, 0x3e, 0xdb, 0x7d, 0xd8, 0xf4, 0x77, 0x64, 0x8f, 0x87, 0x1d,
	0xc1, 0xb9, 0x66, 0x6c, 0x60, 0xec, 0x0d, 0x86, 0xb4, 0x4f, 0x62, 0x24, 0xe9, 0xe5, 0x7c, 0xe2,
	0x6f, 0x61, 0xab, 0x49, 0x39, 0xc6, 0xdf, 0x79, 0x3a, 0xb4, 0x32, 0xe4, 0xc7, 0x2e, 0x65, 0x27,
	0xc7, 0xc8, 0x5a, 0x34, 0xc4, 0x6a, 0xa6, 0xe6, 0xca, 0x4c, 0x4d, 0x9d, 0xc2, 0x9d, 0x04, 0xd7,
	0x2b, 0xfb, 0x8a, 0x0e, 0x9c, 0x11, 0xd5, 0xea, 0x50, 0x18, 0x91, 0xe9, 0xc0, 0x21, 0xa6, 0x90,
	0xbf, 0x23, 0xf6, 0x93, 0x48, 0x37, 0x82, 0x24, 0x6d, 0x1f, 0x8a, 0xae, 0xd5, 0xb3, 0x09, 0x1f,
	0x33, 0x8a, 0x85, 0x36, 0x8d, 0x28, 0xa0, 0x5f, 0x43, 0x29, 0xc0, 0x19, 0xa2, 0xe1, 0xda, 0xe7,
	0x52, 0x7f, 0xef, 0x88, 0x02, 0x41, 0x82, 0xd4, 0xe2, 0xa7, 0xe0, 0x6f, 0xdc, 0x0f, 0x63, 0x89,
	0xf4, 0x26, 0xc5, 0xd3, 0xf4, 0x0b, 0xa8, 0xc8, 0x85, 0x43, 0x89, 0x5f, 0xc8, 0x12, 0xef, 0x4a,
	0x12, 0x03, 0x84, 0xaa, 0xca, 0xbf, 0x72, 0xa0, 0x35, 0x29, 0xff, 0x8e, 0x9a, 0x3d, 0xca, 0xde,
	0x12, 0xde, 0x5f, 0x3c, 0x9e, 0x87, 0xa0, 0xb9, 0x9c, 0x30, 0xde, 0x4e, 0x19, 0x52, 0x09, 0xaf,
	0x34, 0x62, 0xee, 0xa8, 0x41, 0x89, 0xda, 0x66, 0x32, 0x77, 0x15, 0x73, 0xb7, 0xa9, 0x6d, 0xc6,
	0x32, 0x75, 0x07, 0xaa, 0xb3, 0xbb, 0x08, 0x55, 0x3f, 0x91, 0x55, 0xef, 0x46, 0xaa, 0x25, 0x8c,
	0xaa, 0xee, 0x3f, 0xd0, 0x44, 0x11, 0x38, 0xeb, 0x88, 0x9f, 0x09, 0xbf, 0xfa, 0x61, 0x77, 0xc1,
	0x41, 0x48, 0xe4, 0xe9, 0x63, 0xb8, 0x97, 0x5a, 0x3f, 0xd4, 0xfc, 0x4c, 0xd6, 0xbc, 0x9f, 0xa6,
	0x79, 0xd9, 0x71, 0xf7, 0xe0, 0xfd, 0x26, 0xe5, 0xe2, 0x76, 0xf1, 0x7f, 0x4f, 0xa2, 0xb6, 0x0b,
	0xef, 0xf1, 0x49, 0xdb, 0xb2, 0x4d, 0x3a, 0x11, 0x73, 0x2d, 0xf0, 0xc9, 0x89, 0xb7, 0xd4, 0x2d,
	0xb8, 0x2b, 0x15, 0x0a, 0x95, 0x3d, 0x92, 0x95, 0x95, 0x23, 0x65, 0x71, 0x80, 0xaa, 0xa6, 0x9f,
	0xd1, 0xc1, 0x02, 0x99, 0x75, 0x8e, 0x65, 0xc8, 0xf7, 0x89, 0xdb, 0xa7, 0xae, 0xb8, 0x1f, 0x8a,
	0x95, 0x30, 0xa6, 0x44, 0xae, 0x64, 0x4c, 0x09, 0xa3, 0xaa, 0xe6, 0xef, 0x1c, 0x94, 0x9b, 0x94,
	0xbf, 0xb6, 0x5c, 0xee, 0x30, 0xab, 0x4b, 0x06, 0xc7, 0x84, 0x93, 0xc5, 0x93, 0x2a, 0x43, 0xfe,
	0xb8, 0xf1, 0x86, 0x0c, 0x7d, 0xb6, 0xa2, 0x21, 0x56, 0x5a, 0x09, 0x56, 0x2f, 0xe8, 0x14, 0x27,
	0x53, 0x34, 0xbc, 0x9f, 0x5a, 0x0d, 0x0a, 0x57, 0x94, 0xb9, 0x96, 0x63, 0x57, 0xd6, 0x70, 0xbf,
	0xdb, 0x62, 0xbf, 0xe7, 0x7e, 0xd4, 0x08, 0x2e, 0x7b, 0x9b, 0x34, 0x2d, 0x46, 0xf1, 0x09, 0x54,
	0x59, 0x47, 0x86, 0x28, 0xa0, 0x5f, 0xc3, 0x47, 0xe9, 0x7b, 0x0c, 0x3b, 0xf3, 0x95, 0xdc, 0x99,
	0x7b, 0x51, 0x67, 0x52, 0x70, 0xaa, 0xdd, 0xf9, 0x0d, 0x76, 0x67, 0x08, 0xb2, 0x8e, 0xfc, 0x11,
	0xe4, 0xaf, 0xc8, 0x60, 0x4c, 0x83, 0x43, 0x5b, 0x09, 0x7a, 0xe1, 0x05, 0x5b, 0x16, 0xef, 0x7f,
	0x4f, 0x39, 0x31, 0xbd, 0x02, 0x22, 0x4f, 0xff, 0x1d, 0xee, 0xcf, 0xad, 0x1e, 0x2a, 0x7f, 0x21,
	0x2b, 0x3f, 0x98, 0xa7, 0x7c, 0x59, 0x6b, 0xb4, 0xe0, 0xc3, 0x26, 0xe5, 0x3e, 0x12, 0xef, 0x22,
	0x37, 0x64, 0x0b, 0xfd, 0x12, 0xf6, 0x52, 0x88, 0x43, 0x45, 0x4f, 0x65, 0x45, 0xd5, 0x48, 0x91,
	0x0c, 0x52, 0xd5, 0xf2, 0x8f, 0x6f, 0xf3, 0x18, 0x3c, 0xeb, 0x18, 0x1b, 0x50, 0x60, 0x94, 0x98,
	0xed, 0xce, 0x54, 0xcc, 0xf1, 0xb3, 0xd4, 0xdd, 0x05, 0xe8, 0xba, 0xb7, 0x6e, 0x4c, 0x5f, 0xd9,
	0x9c, 0x4d, 0x8d, 0x3c, 0xc3, 0x45, 0xf5, 0x39, 0x6c, 0xc4, 0xc2, 0x41, 0x87, 0x72, 0xd1, 0xc1,
	0xd9, 0x81, 0x75, 0xf4, 0x00, 0x0a, 0xd9, 0x32, 0xfc, 0xc5, 0x8b, 0x95, 0xaf, 0x73, 0xe2, 0x28,
	0xa4, 0x14, 0x52, 0x3a, 0x0a, 0x29, 0xb8, 0xe5, 0xdd, 0xd0, 0x62, 0x16, 0xbf, 0x15, 0x37, 0xc4,
	0x89, 0x95, 0xdd, 0x10, 0x07, 0xa9, 0x6a, 0xf9, 0x37, 0x72, 0x83, 0x80, 0x67, 0x75, 0xc3, 0x29,
	0xc0, 0x35, 0xb3, 0x38, 0xa7, 0x76, 0x64, 0x88, 0x87, 0xa9, 0x1b, 0x0c, 0x0d, 0xd1, 0xf2, 0xf3,
	0x03, 0x4f, 0x14, 0xaf, 0x83, 0x75, 0xf5, 0x25, 0x6c, 0x27, 0x2f, 0x66, 0x74, 0x86, 0x54, 0x51,
	0xd9, 0x19, 0x12, 0x4e, 0xb5, 0x9b, 0xef, 0xf0, 0x81, 0x18, 0x58, 0xab, 0x31, 0x5d, 0x6c, 0x8c,
	0x07, 0xb0, 0xc5, 0x09, 0xeb, 0x51, 0xde, 0x16, 0x97, 0x7d, 0x7f, 0x6c, 0xfa, 0xc1, 0x1f, 0x31,
	0x26, 0x1e, 0x83, 0x12, 0xa5, 0xd2, 0x63, 0x50, 0xc2, 0xa8, 0x6a, 0x70, 0xf0, 0xfd, 0x2c, 0x02,
	0x67, 0xf5, 0xc3, 0xa7, 0xb0, 0x7a, 0x7a, 0x1e, 0xdc, 0xe1, 0x83, 0xdc, 0xd3, 0xf3, 0xc4, 0xed,
	0xdd, 0xcb, 0x10, 0x2f, 0x64, 0xb3, 0x05, 0x95, 0x5e, 0xc8, 0x66, 0x61, 0xaa, 0x3a, 0xcf, 0x42,
	0x9d, 0xa1, 0xd3, 0x6e, 0x60, 0x5c, 0x91, 0x98, 0x24, 0xab, 0xb2, 0x98, 0x24, 0x4c, 0x55, 0x0c,
	0xc3, 0x2f, 0x97, 0x04, 0xfe, 0xd6, 0xe7, 0xf6, 0x2b, 0x1c, 0xcc, 0xab, 0x19, 0xaa, 0x7d, 0x2e,
	0xab, 0xfd, 0x78, 0x8e, 0xda, 0xe5, 0xef, 0xc1, 0x15, 0x7c, 0xd3, 0x3b, 0x39, 0x76, 0x7f, 0x18,
	0x77, 0x86, 0x1e, 0xcb, 0xcd, 0x9c, 0x37, 0x5f, 0x55, 0x2a, 0xb1, 0x92, 0xaa, 0x54, 0xa4, 0xaa,
	0xaa, 0x0e, 0x3e, 0x00, 0x64, 0x8a, 0xac, 0x93, 0xdc, 0x81, 0x75, 0xee, 0x51, 0xe1, 0x2c, 0x8b,
	0x86, 0xbf, 0xd0, 0xff, 0xcc, 0xc1, 0x83, 0x05, 0x45, 0x42, 0x91, 0x2f, 0x65, 0x91, 0xfa, 0x7c,
	0x91, 0xcb, 0x4e, 0xcf, 0x80, 0xe2, 0xd9, 0xc4, 0xa0, 0x5d, 0x6a, 0x8d, 0xf8, 0x52, 0x7f, 0x9d,
	0xc4, 0xbf, 0x7b, 0x56, 0x92, 0xdf, 0x3d, 0xdf, 0xc0, 0x07, 0xb8, 0x33, 0x41, 0xbb, 0xd8, 0x0a,
	0x1a, 0xac, 0x79, 0xdd, 0x10, 0x0e, 0xc0, 0xdf, 0xfa, 0x10, 0xdf, 0x70, 0x93, 0x04, 0x61, 0x37,
	0x1e, 0xcb, 0xdd, 0xa8, 0xc4, 0xbb, 0x11, 0x87, 0xa8, 0xf6, 0xe0, 0x12, 0x76, 0xe2, 0xd8, 0xac,
	0x43, 0x3e, 0xf4, 0x5e, 0xc2, 0x90, 0x41, 0xfc, 0xcb, 0x51, 0x12, 0xf9, 0x11, 0x73, 0x90, 0xa0,
	0xbb, 0xb0, 0x9f, 0x56, 0x32, 0x14, 0xf9, 0xa5, 0x2c, 0x72, 0x2f, 0x45, 0xe4, 0x92, 0xb3, 0x6e,
	0x1c, 0xfe, 0x54, 0xeb, 0x59, 0xbc, 0x3f, 0xee, 0xd4, 0xad, 0xce, 0xb0, 0xde, 0x75, 0x86, 0x47,
	0xf8, 0x21, 0xdb, 0xed, 0x13, 0xcb, 0x36, 0x3b, 0x47, 0xf8, 0x4f, 0x9a, 0x7b, 0x84, 0x75, 0x3a,
	0x79, 0x5c, 0x3d, 0xf9, 0x2f, 0x00, 0x00, 0xff, 0xff, 0x41, 0x47, 0xe2, 0x4d, 0xa9, 0x13, 0x00,
	0x00,
}
