// Code generated by protoc-gen-go. DO NOT EDIT.
// source: query.proto

package types

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetDBStatusQueryEnvelope struct {
	Payload              *GetDBStatusQuery `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	Signature            []byte            `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *GetDBStatusQueryEnvelope) Reset()         { *m = GetDBStatusQueryEnvelope{} }
func (m *GetDBStatusQueryEnvelope) String() string { return proto.CompactTextString(m) }
func (*GetDBStatusQueryEnvelope) ProtoMessage()    {}
func (*GetDBStatusQueryEnvelope) Descriptor() ([]byte, []int) {
	return fileDescriptor_5c6ac9b241082464, []int{0}
}

func (m *GetDBStatusQueryEnvelope) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDBStatusQueryEnvelope.Unmarshal(m, b)
}
func (m *GetDBStatusQueryEnvelope) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDBStatusQueryEnvelope.Marshal(b, m, deterministic)
}
func (m *GetDBStatusQueryEnvelope) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDBStatusQueryEnvelope.Merge(m, src)
}
func (m *GetDBStatusQueryEnvelope) XXX_Size() int {
	return xxx_messageInfo_GetDBStatusQueryEnvelope.Size(m)
}
func (m *GetDBStatusQueryEnvelope) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDBStatusQueryEnvelope.DiscardUnknown(m)
}

var xxx_messageInfo_GetDBStatusQueryEnvelope proto.InternalMessageInfo

func (m *GetDBStatusQueryEnvelope) GetPayload() *GetDBStatusQuery {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *GetDBStatusQueryEnvelope) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

type GetDBStatusQuery struct {
	UserID               string   `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID,omitempty"`
	DBName               string   `protobuf:"bytes,2,opt,name=DBName,proto3" json:"DBName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetDBStatusQuery) Reset()         { *m = GetDBStatusQuery{} }
func (m *GetDBStatusQuery) String() string { return proto.CompactTextString(m) }
func (*GetDBStatusQuery) ProtoMessage()    {}
func (*GetDBStatusQuery) Descriptor() ([]byte, []int) {
	return fileDescriptor_5c6ac9b241082464, []int{1}
}

func (m *GetDBStatusQuery) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDBStatusQuery.Unmarshal(m, b)
}
func (m *GetDBStatusQuery) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDBStatusQuery.Marshal(b, m, deterministic)
}
func (m *GetDBStatusQuery) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDBStatusQuery.Merge(m, src)
}
func (m *GetDBStatusQuery) XXX_Size() int {
	return xxx_messageInfo_GetDBStatusQuery.Size(m)
}
func (m *GetDBStatusQuery) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDBStatusQuery.DiscardUnknown(m)
}

var xxx_messageInfo_GetDBStatusQuery proto.InternalMessageInfo

func (m *GetDBStatusQuery) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *GetDBStatusQuery) GetDBName() string {
	if m != nil {
		return m.DBName
	}
	return ""
}

type GetDataQueryEnvelope struct {
	Payload              *GetDataQuery `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	Signature            []byte        `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *GetDataQueryEnvelope) Reset()         { *m = GetDataQueryEnvelope{} }
func (m *GetDataQueryEnvelope) String() string { return proto.CompactTextString(m) }
func (*GetDataQueryEnvelope) ProtoMessage()    {}
func (*GetDataQueryEnvelope) Descriptor() ([]byte, []int) {
	return fileDescriptor_5c6ac9b241082464, []int{2}
}

func (m *GetDataQueryEnvelope) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDataQueryEnvelope.Unmarshal(m, b)
}
func (m *GetDataQueryEnvelope) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDataQueryEnvelope.Marshal(b, m, deterministic)
}
func (m *GetDataQueryEnvelope) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDataQueryEnvelope.Merge(m, src)
}
func (m *GetDataQueryEnvelope) XXX_Size() int {
	return xxx_messageInfo_GetDataQueryEnvelope.Size(m)
}
func (m *GetDataQueryEnvelope) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDataQueryEnvelope.DiscardUnknown(m)
}

var xxx_messageInfo_GetDataQueryEnvelope proto.InternalMessageInfo

func (m *GetDataQueryEnvelope) GetPayload() *GetDataQuery {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *GetDataQueryEnvelope) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

type GetDataQuery struct {
	UserID               string   `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID,omitempty"`
	DBName               string   `protobuf:"bytes,2,opt,name=DBName,proto3" json:"DBName,omitempty"`
	Key                  string   `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetDataQuery) Reset()         { *m = GetDataQuery{} }
func (m *GetDataQuery) String() string { return proto.CompactTextString(m) }
func (*GetDataQuery) ProtoMessage()    {}
func (*GetDataQuery) Descriptor() ([]byte, []int) {
	return fileDescriptor_5c6ac9b241082464, []int{3}
}

func (m *GetDataQuery) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDataQuery.Unmarshal(m, b)
}
func (m *GetDataQuery) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDataQuery.Marshal(b, m, deterministic)
}
func (m *GetDataQuery) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDataQuery.Merge(m, src)
}
func (m *GetDataQuery) XXX_Size() int {
	return xxx_messageInfo_GetDataQuery.Size(m)
}
func (m *GetDataQuery) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDataQuery.DiscardUnknown(m)
}

var xxx_messageInfo_GetDataQuery proto.InternalMessageInfo

func (m *GetDataQuery) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *GetDataQuery) GetDBName() string {
	if m != nil {
		return m.DBName
	}
	return ""
}

func (m *GetDataQuery) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type GetUserQueryEnvelope struct {
	Payload              *GetUserQuery `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	Signature            []byte        `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *GetUserQueryEnvelope) Reset()         { *m = GetUserQueryEnvelope{} }
func (m *GetUserQueryEnvelope) String() string { return proto.CompactTextString(m) }
func (*GetUserQueryEnvelope) ProtoMessage()    {}
func (*GetUserQueryEnvelope) Descriptor() ([]byte, []int) {
	return fileDescriptor_5c6ac9b241082464, []int{4}
}

func (m *GetUserQueryEnvelope) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserQueryEnvelope.Unmarshal(m, b)
}
func (m *GetUserQueryEnvelope) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserQueryEnvelope.Marshal(b, m, deterministic)
}
func (m *GetUserQueryEnvelope) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserQueryEnvelope.Merge(m, src)
}
func (m *GetUserQueryEnvelope) XXX_Size() int {
	return xxx_messageInfo_GetUserQueryEnvelope.Size(m)
}
func (m *GetUserQueryEnvelope) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserQueryEnvelope.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserQueryEnvelope proto.InternalMessageInfo

func (m *GetUserQueryEnvelope) GetPayload() *GetUserQuery {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *GetUserQueryEnvelope) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

type GetUserQuery struct {
	UserID               string   `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID,omitempty"`
	TargetUserID         string   `protobuf:"bytes,2,opt,name=targetUserID,proto3" json:"targetUserID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserQuery) Reset()         { *m = GetUserQuery{} }
func (m *GetUserQuery) String() string { return proto.CompactTextString(m) }
func (*GetUserQuery) ProtoMessage()    {}
func (*GetUserQuery) Descriptor() ([]byte, []int) {
	return fileDescriptor_5c6ac9b241082464, []int{5}
}

func (m *GetUserQuery) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserQuery.Unmarshal(m, b)
}
func (m *GetUserQuery) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserQuery.Marshal(b, m, deterministic)
}
func (m *GetUserQuery) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserQuery.Merge(m, src)
}
func (m *GetUserQuery) XXX_Size() int {
	return xxx_messageInfo_GetUserQuery.Size(m)
}
func (m *GetUserQuery) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserQuery.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserQuery proto.InternalMessageInfo

func (m *GetUserQuery) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *GetUserQuery) GetTargetUserID() string {
	if m != nil {
		return m.TargetUserID
	}
	return ""
}

type GetConfigQueryEnvelope struct {
	Payload              *GetConfigQuery `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	Signature            []byte          `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *GetConfigQueryEnvelope) Reset()         { *m = GetConfigQueryEnvelope{} }
func (m *GetConfigQueryEnvelope) String() string { return proto.CompactTextString(m) }
func (*GetConfigQueryEnvelope) ProtoMessage()    {}
func (*GetConfigQueryEnvelope) Descriptor() ([]byte, []int) {
	return fileDescriptor_5c6ac9b241082464, []int{6}
}

func (m *GetConfigQueryEnvelope) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetConfigQueryEnvelope.Unmarshal(m, b)
}
func (m *GetConfigQueryEnvelope) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetConfigQueryEnvelope.Marshal(b, m, deterministic)
}
func (m *GetConfigQueryEnvelope) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetConfigQueryEnvelope.Merge(m, src)
}
func (m *GetConfigQueryEnvelope) XXX_Size() int {
	return xxx_messageInfo_GetConfigQueryEnvelope.Size(m)
}
func (m *GetConfigQueryEnvelope) XXX_DiscardUnknown() {
	xxx_messageInfo_GetConfigQueryEnvelope.DiscardUnknown(m)
}

var xxx_messageInfo_GetConfigQueryEnvelope proto.InternalMessageInfo

func (m *GetConfigQueryEnvelope) GetPayload() *GetConfigQuery {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *GetConfigQueryEnvelope) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

type GetConfigQuery struct {
	UserID               string   `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetConfigQuery) Reset()         { *m = GetConfigQuery{} }
func (m *GetConfigQuery) String() string { return proto.CompactTextString(m) }
func (*GetConfigQuery) ProtoMessage()    {}
func (*GetConfigQuery) Descriptor() ([]byte, []int) {
	return fileDescriptor_5c6ac9b241082464, []int{7}
}

func (m *GetConfigQuery) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetConfigQuery.Unmarshal(m, b)
}
func (m *GetConfigQuery) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetConfigQuery.Marshal(b, m, deterministic)
}
func (m *GetConfigQuery) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetConfigQuery.Merge(m, src)
}
func (m *GetConfigQuery) XXX_Size() int {
	return xxx_messageInfo_GetConfigQuery.Size(m)
}
func (m *GetConfigQuery) XXX_DiscardUnknown() {
	xxx_messageInfo_GetConfigQuery.DiscardUnknown(m)
}

var xxx_messageInfo_GetConfigQuery proto.InternalMessageInfo

func (m *GetConfigQuery) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

type GetNodeConfigQueryEnvelope struct {
	Payload              *GetNodeConfigQuery `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	Signature            []byte              `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *GetNodeConfigQueryEnvelope) Reset()         { *m = GetNodeConfigQueryEnvelope{} }
func (m *GetNodeConfigQueryEnvelope) String() string { return proto.CompactTextString(m) }
func (*GetNodeConfigQueryEnvelope) ProtoMessage()    {}
func (*GetNodeConfigQueryEnvelope) Descriptor() ([]byte, []int) {
	return fileDescriptor_5c6ac9b241082464, []int{8}
}

func (m *GetNodeConfigQueryEnvelope) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetNodeConfigQueryEnvelope.Unmarshal(m, b)
}
func (m *GetNodeConfigQueryEnvelope) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetNodeConfigQueryEnvelope.Marshal(b, m, deterministic)
}
func (m *GetNodeConfigQueryEnvelope) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetNodeConfigQueryEnvelope.Merge(m, src)
}
func (m *GetNodeConfigQueryEnvelope) XXX_Size() int {
	return xxx_messageInfo_GetNodeConfigQueryEnvelope.Size(m)
}
func (m *GetNodeConfigQueryEnvelope) XXX_DiscardUnknown() {
	xxx_messageInfo_GetNodeConfigQueryEnvelope.DiscardUnknown(m)
}

var xxx_messageInfo_GetNodeConfigQueryEnvelope proto.InternalMessageInfo

func (m *GetNodeConfigQueryEnvelope) GetPayload() *GetNodeConfigQuery {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *GetNodeConfigQueryEnvelope) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

type GetNodeConfigQuery struct {
	UserID               string   `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID,omitempty"`
	NodeID               string   `protobuf:"bytes,2,opt,name=nodeID,proto3" json:"nodeID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetNodeConfigQuery) Reset()         { *m = GetNodeConfigQuery{} }
func (m *GetNodeConfigQuery) String() string { return proto.CompactTextString(m) }
func (*GetNodeConfigQuery) ProtoMessage()    {}
func (*GetNodeConfigQuery) Descriptor() ([]byte, []int) {
	return fileDescriptor_5c6ac9b241082464, []int{9}
}

func (m *GetNodeConfigQuery) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetNodeConfigQuery.Unmarshal(m, b)
}
func (m *GetNodeConfigQuery) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetNodeConfigQuery.Marshal(b, m, deterministic)
}
func (m *GetNodeConfigQuery) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetNodeConfigQuery.Merge(m, src)
}
func (m *GetNodeConfigQuery) XXX_Size() int {
	return xxx_messageInfo_GetNodeConfigQuery.Size(m)
}
func (m *GetNodeConfigQuery) XXX_DiscardUnknown() {
	xxx_messageInfo_GetNodeConfigQuery.DiscardUnknown(m)
}

var xxx_messageInfo_GetNodeConfigQuery proto.InternalMessageInfo

func (m *GetNodeConfigQuery) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *GetNodeConfigQuery) GetNodeID() string {
	if m != nil {
		return m.NodeID
	}
	return ""
}

type GetBlockQuery struct {
	UserID               string   `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID,omitempty"`
	BlockNumber          uint64   `protobuf:"varint,2,opt,name=block_number,json=blockNumber,proto3" json:"block_number,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBlockQuery) Reset()         { *m = GetBlockQuery{} }
func (m *GetBlockQuery) String() string { return proto.CompactTextString(m) }
func (*GetBlockQuery) ProtoMessage()    {}
func (*GetBlockQuery) Descriptor() ([]byte, []int) {
	return fileDescriptor_5c6ac9b241082464, []int{10}
}

func (m *GetBlockQuery) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBlockQuery.Unmarshal(m, b)
}
func (m *GetBlockQuery) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBlockQuery.Marshal(b, m, deterministic)
}
func (m *GetBlockQuery) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBlockQuery.Merge(m, src)
}
func (m *GetBlockQuery) XXX_Size() int {
	return xxx_messageInfo_GetBlockQuery.Size(m)
}
func (m *GetBlockQuery) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBlockQuery.DiscardUnknown(m)
}

var xxx_messageInfo_GetBlockQuery proto.InternalMessageInfo

func (m *GetBlockQuery) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *GetBlockQuery) GetBlockNumber() uint64 {
	if m != nil {
		return m.BlockNumber
	}
	return 0
}

type GetBlockQueryEnvelope struct {
	Payload              *GetBlockQuery `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	Signature            []byte         `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *GetBlockQueryEnvelope) Reset()         { *m = GetBlockQueryEnvelope{} }
func (m *GetBlockQueryEnvelope) String() string { return proto.CompactTextString(m) }
func (*GetBlockQueryEnvelope) ProtoMessage()    {}
func (*GetBlockQueryEnvelope) Descriptor() ([]byte, []int) {
	return fileDescriptor_5c6ac9b241082464, []int{11}
}

func (m *GetBlockQueryEnvelope) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBlockQueryEnvelope.Unmarshal(m, b)
}
func (m *GetBlockQueryEnvelope) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBlockQueryEnvelope.Marshal(b, m, deterministic)
}
func (m *GetBlockQueryEnvelope) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBlockQueryEnvelope.Merge(m, src)
}
func (m *GetBlockQueryEnvelope) XXX_Size() int {
	return xxx_messageInfo_GetBlockQueryEnvelope.Size(m)
}
func (m *GetBlockQueryEnvelope) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBlockQueryEnvelope.DiscardUnknown(m)
}

var xxx_messageInfo_GetBlockQueryEnvelope proto.InternalMessageInfo

func (m *GetBlockQueryEnvelope) GetPayload() *GetBlockQuery {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *GetBlockQueryEnvelope) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

type GetLedgerPathQuery struct {
	UserID               string   `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID,omitempty"`
	StartBlockNumber     uint64   `protobuf:"varint,2,opt,name=start_block_number,json=startBlockNumber,proto3" json:"start_block_number,omitempty"`
	EndBlockNumber       uint64   `protobuf:"varint,3,opt,name=end_block_number,json=endBlockNumber,proto3" json:"end_block_number,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetLedgerPathQuery) Reset()         { *m = GetLedgerPathQuery{} }
func (m *GetLedgerPathQuery) String() string { return proto.CompactTextString(m) }
func (*GetLedgerPathQuery) ProtoMessage()    {}
func (*GetLedgerPathQuery) Descriptor() ([]byte, []int) {
	return fileDescriptor_5c6ac9b241082464, []int{12}
}

func (m *GetLedgerPathQuery) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetLedgerPathQuery.Unmarshal(m, b)
}
func (m *GetLedgerPathQuery) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetLedgerPathQuery.Marshal(b, m, deterministic)
}
func (m *GetLedgerPathQuery) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetLedgerPathQuery.Merge(m, src)
}
func (m *GetLedgerPathQuery) XXX_Size() int {
	return xxx_messageInfo_GetLedgerPathQuery.Size(m)
}
func (m *GetLedgerPathQuery) XXX_DiscardUnknown() {
	xxx_messageInfo_GetLedgerPathQuery.DiscardUnknown(m)
}

var xxx_messageInfo_GetLedgerPathQuery proto.InternalMessageInfo

func (m *GetLedgerPathQuery) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *GetLedgerPathQuery) GetStartBlockNumber() uint64 {
	if m != nil {
		return m.StartBlockNumber
	}
	return 0
}

func (m *GetLedgerPathQuery) GetEndBlockNumber() uint64 {
	if m != nil {
		return m.EndBlockNumber
	}
	return 0
}

type GetLedgerPathQueryEnvelope struct {
	Payload              *GetLedgerPathQuery `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	Signature            []byte              `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *GetLedgerPathQueryEnvelope) Reset()         { *m = GetLedgerPathQueryEnvelope{} }
func (m *GetLedgerPathQueryEnvelope) String() string { return proto.CompactTextString(m) }
func (*GetLedgerPathQueryEnvelope) ProtoMessage()    {}
func (*GetLedgerPathQueryEnvelope) Descriptor() ([]byte, []int) {
	return fileDescriptor_5c6ac9b241082464, []int{13}
}

func (m *GetLedgerPathQueryEnvelope) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetLedgerPathQueryEnvelope.Unmarshal(m, b)
}
func (m *GetLedgerPathQueryEnvelope) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetLedgerPathQueryEnvelope.Marshal(b, m, deterministic)
}
func (m *GetLedgerPathQueryEnvelope) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetLedgerPathQueryEnvelope.Merge(m, src)
}
func (m *GetLedgerPathQueryEnvelope) XXX_Size() int {
	return xxx_messageInfo_GetLedgerPathQueryEnvelope.Size(m)
}
func (m *GetLedgerPathQueryEnvelope) XXX_DiscardUnknown() {
	xxx_messageInfo_GetLedgerPathQueryEnvelope.DiscardUnknown(m)
}

var xxx_messageInfo_GetLedgerPathQueryEnvelope proto.InternalMessageInfo

func (m *GetLedgerPathQueryEnvelope) GetPayload() *GetLedgerPathQuery {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *GetLedgerPathQueryEnvelope) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

type GetTxProofQuery struct {
	UserID               string   `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID,omitempty"`
	BlockNumber          uint64   `protobuf:"varint,2,opt,name=block_number,json=blockNumber,proto3" json:"block_number,omitempty"`
	TxIndex              uint64   `protobuf:"varint,3,opt,name=tx_index,json=txIndex,proto3" json:"tx_index,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetTxProofQuery) Reset()         { *m = GetTxProofQuery{} }
func (m *GetTxProofQuery) String() string { return proto.CompactTextString(m) }
func (*GetTxProofQuery) ProtoMessage()    {}
func (*GetTxProofQuery) Descriptor() ([]byte, []int) {
	return fileDescriptor_5c6ac9b241082464, []int{14}
}

func (m *GetTxProofQuery) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTxProofQuery.Unmarshal(m, b)
}
func (m *GetTxProofQuery) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTxProofQuery.Marshal(b, m, deterministic)
}
func (m *GetTxProofQuery) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTxProofQuery.Merge(m, src)
}
func (m *GetTxProofQuery) XXX_Size() int {
	return xxx_messageInfo_GetTxProofQuery.Size(m)
}
func (m *GetTxProofQuery) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTxProofQuery.DiscardUnknown(m)
}

var xxx_messageInfo_GetTxProofQuery proto.InternalMessageInfo

func (m *GetTxProofQuery) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *GetTxProofQuery) GetBlockNumber() uint64 {
	if m != nil {
		return m.BlockNumber
	}
	return 0
}

func (m *GetTxProofQuery) GetTxIndex() uint64 {
	if m != nil {
		return m.TxIndex
	}
	return 0
}

type GetTxProofQueryEnvelope struct {
	Payload              *GetTxProofQuery `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	Signature            []byte           `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *GetTxProofQueryEnvelope) Reset()         { *m = GetTxProofQueryEnvelope{} }
func (m *GetTxProofQueryEnvelope) String() string { return proto.CompactTextString(m) }
func (*GetTxProofQueryEnvelope) ProtoMessage()    {}
func (*GetTxProofQueryEnvelope) Descriptor() ([]byte, []int) {
	return fileDescriptor_5c6ac9b241082464, []int{15}
}

func (m *GetTxProofQueryEnvelope) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTxProofQueryEnvelope.Unmarshal(m, b)
}
func (m *GetTxProofQueryEnvelope) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTxProofQueryEnvelope.Marshal(b, m, deterministic)
}
func (m *GetTxProofQueryEnvelope) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTxProofQueryEnvelope.Merge(m, src)
}
func (m *GetTxProofQueryEnvelope) XXX_Size() int {
	return xxx_messageInfo_GetTxProofQueryEnvelope.Size(m)
}
func (m *GetTxProofQueryEnvelope) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTxProofQueryEnvelope.DiscardUnknown(m)
}

var xxx_messageInfo_GetTxProofQueryEnvelope proto.InternalMessageInfo

func (m *GetTxProofQueryEnvelope) GetPayload() *GetTxProofQuery {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *GetTxProofQueryEnvelope) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

type GetHistoricalDataQuery struct {
	UserID               string   `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID,omitempty"`
	DBName               string   `protobuf:"bytes,2,opt,name=DBName,proto3" json:"DBName,omitempty"`
	Key                  string   `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`
	Version              *Version `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`
	Direction            string   `protobuf:"bytes,5,opt,name=direction,proto3" json:"direction,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetHistoricalDataQuery) Reset()         { *m = GetHistoricalDataQuery{} }
func (m *GetHistoricalDataQuery) String() string { return proto.CompactTextString(m) }
func (*GetHistoricalDataQuery) ProtoMessage()    {}
func (*GetHistoricalDataQuery) Descriptor() ([]byte, []int) {
	return fileDescriptor_5c6ac9b241082464, []int{16}
}

func (m *GetHistoricalDataQuery) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetHistoricalDataQuery.Unmarshal(m, b)
}
func (m *GetHistoricalDataQuery) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetHistoricalDataQuery.Marshal(b, m, deterministic)
}
func (m *GetHistoricalDataQuery) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetHistoricalDataQuery.Merge(m, src)
}
func (m *GetHistoricalDataQuery) XXX_Size() int {
	return xxx_messageInfo_GetHistoricalDataQuery.Size(m)
}
func (m *GetHistoricalDataQuery) XXX_DiscardUnknown() {
	xxx_messageInfo_GetHistoricalDataQuery.DiscardUnknown(m)
}

var xxx_messageInfo_GetHistoricalDataQuery proto.InternalMessageInfo

func (m *GetHistoricalDataQuery) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *GetHistoricalDataQuery) GetDBName() string {
	if m != nil {
		return m.DBName
	}
	return ""
}

func (m *GetHistoricalDataQuery) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *GetHistoricalDataQuery) GetVersion() *Version {
	if m != nil {
		return m.Version
	}
	return nil
}

func (m *GetHistoricalDataQuery) GetDirection() string {
	if m != nil {
		return m.Direction
	}
	return ""
}

type GetHistoricalDataQueryEnvelope struct {
	Payload              *GetHistoricalDataQuery `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	Signature            []byte                  `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *GetHistoricalDataQueryEnvelope) Reset()         { *m = GetHistoricalDataQueryEnvelope{} }
func (m *GetHistoricalDataQueryEnvelope) String() string { return proto.CompactTextString(m) }
func (*GetHistoricalDataQueryEnvelope) ProtoMessage()    {}
func (*GetHistoricalDataQueryEnvelope) Descriptor() ([]byte, []int) {
	return fileDescriptor_5c6ac9b241082464, []int{17}
}

func (m *GetHistoricalDataQueryEnvelope) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetHistoricalDataQueryEnvelope.Unmarshal(m, b)
}
func (m *GetHistoricalDataQueryEnvelope) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetHistoricalDataQueryEnvelope.Marshal(b, m, deterministic)
}
func (m *GetHistoricalDataQueryEnvelope) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetHistoricalDataQueryEnvelope.Merge(m, src)
}
func (m *GetHistoricalDataQueryEnvelope) XXX_Size() int {
	return xxx_messageInfo_GetHistoricalDataQueryEnvelope.Size(m)
}
func (m *GetHistoricalDataQueryEnvelope) XXX_DiscardUnknown() {
	xxx_messageInfo_GetHistoricalDataQueryEnvelope.DiscardUnknown(m)
}

var xxx_messageInfo_GetHistoricalDataQueryEnvelope proto.InternalMessageInfo

func (m *GetHistoricalDataQueryEnvelope) GetPayload() *GetHistoricalDataQuery {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *GetHistoricalDataQueryEnvelope) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

type GetDataReadersQuery struct {
	UserID               string   `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID,omitempty"`
	DBName               string   `protobuf:"bytes,2,opt,name=DBName,proto3" json:"DBName,omitempty"`
	Key                  string   `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetDataReadersQuery) Reset()         { *m = GetDataReadersQuery{} }
func (m *GetDataReadersQuery) String() string { return proto.CompactTextString(m) }
func (*GetDataReadersQuery) ProtoMessage()    {}
func (*GetDataReadersQuery) Descriptor() ([]byte, []int) {
	return fileDescriptor_5c6ac9b241082464, []int{18}
}

func (m *GetDataReadersQuery) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDataReadersQuery.Unmarshal(m, b)
}
func (m *GetDataReadersQuery) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDataReadersQuery.Marshal(b, m, deterministic)
}
func (m *GetDataReadersQuery) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDataReadersQuery.Merge(m, src)
}
func (m *GetDataReadersQuery) XXX_Size() int {
	return xxx_messageInfo_GetDataReadersQuery.Size(m)
}
func (m *GetDataReadersQuery) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDataReadersQuery.DiscardUnknown(m)
}

var xxx_messageInfo_GetDataReadersQuery proto.InternalMessageInfo

func (m *GetDataReadersQuery) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *GetDataReadersQuery) GetDBName() string {
	if m != nil {
		return m.DBName
	}
	return ""
}

func (m *GetDataReadersQuery) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type GetDataReadersQueryEnvelope struct {
	Payload              *GetDataReadersQuery `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	Signature            []byte               `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *GetDataReadersQueryEnvelope) Reset()         { *m = GetDataReadersQueryEnvelope{} }
func (m *GetDataReadersQueryEnvelope) String() string { return proto.CompactTextString(m) }
func (*GetDataReadersQueryEnvelope) ProtoMessage()    {}
func (*GetDataReadersQueryEnvelope) Descriptor() ([]byte, []int) {
	return fileDescriptor_5c6ac9b241082464, []int{19}
}

func (m *GetDataReadersQueryEnvelope) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDataReadersQueryEnvelope.Unmarshal(m, b)
}
func (m *GetDataReadersQueryEnvelope) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDataReadersQueryEnvelope.Marshal(b, m, deterministic)
}
func (m *GetDataReadersQueryEnvelope) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDataReadersQueryEnvelope.Merge(m, src)
}
func (m *GetDataReadersQueryEnvelope) XXX_Size() int {
	return xxx_messageInfo_GetDataReadersQueryEnvelope.Size(m)
}
func (m *GetDataReadersQueryEnvelope) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDataReadersQueryEnvelope.DiscardUnknown(m)
}

var xxx_messageInfo_GetDataReadersQueryEnvelope proto.InternalMessageInfo

func (m *GetDataReadersQueryEnvelope) GetPayload() *GetDataReadersQuery {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *GetDataReadersQueryEnvelope) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

type GetDataWritersQuery struct {
	UserID               string   `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID,omitempty"`
	DBName               string   `protobuf:"bytes,2,opt,name=DBName,proto3" json:"DBName,omitempty"`
	Key                  string   `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetDataWritersQuery) Reset()         { *m = GetDataWritersQuery{} }
func (m *GetDataWritersQuery) String() string { return proto.CompactTextString(m) }
func (*GetDataWritersQuery) ProtoMessage()    {}
func (*GetDataWritersQuery) Descriptor() ([]byte, []int) {
	return fileDescriptor_5c6ac9b241082464, []int{20}
}

func (m *GetDataWritersQuery) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDataWritersQuery.Unmarshal(m, b)
}
func (m *GetDataWritersQuery) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDataWritersQuery.Marshal(b, m, deterministic)
}
func (m *GetDataWritersQuery) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDataWritersQuery.Merge(m, src)
}
func (m *GetDataWritersQuery) XXX_Size() int {
	return xxx_messageInfo_GetDataWritersQuery.Size(m)
}
func (m *GetDataWritersQuery) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDataWritersQuery.DiscardUnknown(m)
}

var xxx_messageInfo_GetDataWritersQuery proto.InternalMessageInfo

func (m *GetDataWritersQuery) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *GetDataWritersQuery) GetDBName() string {
	if m != nil {
		return m.DBName
	}
	return ""
}

func (m *GetDataWritersQuery) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type GetDataWritersQueryEnvelope struct {
	Payload              *GetDataWritersQuery `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	Signature            []byte               `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *GetDataWritersQueryEnvelope) Reset()         { *m = GetDataWritersQueryEnvelope{} }
func (m *GetDataWritersQueryEnvelope) String() string { return proto.CompactTextString(m) }
func (*GetDataWritersQueryEnvelope) ProtoMessage()    {}
func (*GetDataWritersQueryEnvelope) Descriptor() ([]byte, []int) {
	return fileDescriptor_5c6ac9b241082464, []int{21}
}

func (m *GetDataWritersQueryEnvelope) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDataWritersQueryEnvelope.Unmarshal(m, b)
}
func (m *GetDataWritersQueryEnvelope) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDataWritersQueryEnvelope.Marshal(b, m, deterministic)
}
func (m *GetDataWritersQueryEnvelope) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDataWritersQueryEnvelope.Merge(m, src)
}
func (m *GetDataWritersQueryEnvelope) XXX_Size() int {
	return xxx_messageInfo_GetDataWritersQueryEnvelope.Size(m)
}
func (m *GetDataWritersQueryEnvelope) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDataWritersQueryEnvelope.DiscardUnknown(m)
}

var xxx_messageInfo_GetDataWritersQueryEnvelope proto.InternalMessageInfo

func (m *GetDataWritersQueryEnvelope) GetPayload() *GetDataWritersQuery {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *GetDataWritersQueryEnvelope) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

type GetDataReadByQuery struct {
	UserID               string   `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID,omitempty"`
	TargetUserID         string   `protobuf:"bytes,2,opt,name=target_userID,json=targetUserID,proto3" json:"target_userID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetDataReadByQuery) Reset()         { *m = GetDataReadByQuery{} }
func (m *GetDataReadByQuery) String() string { return proto.CompactTextString(m) }
func (*GetDataReadByQuery) ProtoMessage()    {}
func (*GetDataReadByQuery) Descriptor() ([]byte, []int) {
	return fileDescriptor_5c6ac9b241082464, []int{22}
}

func (m *GetDataReadByQuery) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDataReadByQuery.Unmarshal(m, b)
}
func (m *GetDataReadByQuery) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDataReadByQuery.Marshal(b, m, deterministic)
}
func (m *GetDataReadByQuery) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDataReadByQuery.Merge(m, src)
}
func (m *GetDataReadByQuery) XXX_Size() int {
	return xxx_messageInfo_GetDataReadByQuery.Size(m)
}
func (m *GetDataReadByQuery) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDataReadByQuery.DiscardUnknown(m)
}

var xxx_messageInfo_GetDataReadByQuery proto.InternalMessageInfo

func (m *GetDataReadByQuery) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *GetDataReadByQuery) GetTargetUserID() string {
	if m != nil {
		return m.TargetUserID
	}
	return ""
}

type GetDataReadByQueryEnvelope struct {
	Payload              *GetDataReadByQuery `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	Signature            []byte              `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *GetDataReadByQueryEnvelope) Reset()         { *m = GetDataReadByQueryEnvelope{} }
func (m *GetDataReadByQueryEnvelope) String() string { return proto.CompactTextString(m) }
func (*GetDataReadByQueryEnvelope) ProtoMessage()    {}
func (*GetDataReadByQueryEnvelope) Descriptor() ([]byte, []int) {
	return fileDescriptor_5c6ac9b241082464, []int{23}
}

func (m *GetDataReadByQueryEnvelope) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDataReadByQueryEnvelope.Unmarshal(m, b)
}
func (m *GetDataReadByQueryEnvelope) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDataReadByQueryEnvelope.Marshal(b, m, deterministic)
}
func (m *GetDataReadByQueryEnvelope) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDataReadByQueryEnvelope.Merge(m, src)
}
func (m *GetDataReadByQueryEnvelope) XXX_Size() int {
	return xxx_messageInfo_GetDataReadByQueryEnvelope.Size(m)
}
func (m *GetDataReadByQueryEnvelope) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDataReadByQueryEnvelope.DiscardUnknown(m)
}

var xxx_messageInfo_GetDataReadByQueryEnvelope proto.InternalMessageInfo

func (m *GetDataReadByQueryEnvelope) GetPayload() *GetDataReadByQuery {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *GetDataReadByQueryEnvelope) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

type GetDataWrittenByQuery struct {
	UserID               string   `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID,omitempty"`
	TargetUserID         string   `protobuf:"bytes,2,opt,name=target_userID,json=targetUserID,proto3" json:"target_userID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetDataWrittenByQuery) Reset()         { *m = GetDataWrittenByQuery{} }
func (m *GetDataWrittenByQuery) String() string { return proto.CompactTextString(m) }
func (*GetDataWrittenByQuery) ProtoMessage()    {}
func (*GetDataWrittenByQuery) Descriptor() ([]byte, []int) {
	return fileDescriptor_5c6ac9b241082464, []int{24}
}

func (m *GetDataWrittenByQuery) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDataWrittenByQuery.Unmarshal(m, b)
}
func (m *GetDataWrittenByQuery) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDataWrittenByQuery.Marshal(b, m, deterministic)
}
func (m *GetDataWrittenByQuery) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDataWrittenByQuery.Merge(m, src)
}
func (m *GetDataWrittenByQuery) XXX_Size() int {
	return xxx_messageInfo_GetDataWrittenByQuery.Size(m)
}
func (m *GetDataWrittenByQuery) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDataWrittenByQuery.DiscardUnknown(m)
}

var xxx_messageInfo_GetDataWrittenByQuery proto.InternalMessageInfo

func (m *GetDataWrittenByQuery) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *GetDataWrittenByQuery) GetTargetUserID() string {
	if m != nil {
		return m.TargetUserID
	}
	return ""
}

type GetDataWrittenByQueryEnvelope struct {
	Payload              *GetDataWrittenByQuery `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	Signature            []byte                 `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *GetDataWrittenByQueryEnvelope) Reset()         { *m = GetDataWrittenByQueryEnvelope{} }
func (m *GetDataWrittenByQueryEnvelope) String() string { return proto.CompactTextString(m) }
func (*GetDataWrittenByQueryEnvelope) ProtoMessage()    {}
func (*GetDataWrittenByQueryEnvelope) Descriptor() ([]byte, []int) {
	return fileDescriptor_5c6ac9b241082464, []int{25}
}

func (m *GetDataWrittenByQueryEnvelope) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDataWrittenByQueryEnvelope.Unmarshal(m, b)
}
func (m *GetDataWrittenByQueryEnvelope) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDataWrittenByQueryEnvelope.Marshal(b, m, deterministic)
}
func (m *GetDataWrittenByQueryEnvelope) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDataWrittenByQueryEnvelope.Merge(m, src)
}
func (m *GetDataWrittenByQueryEnvelope) XXX_Size() int {
	return xxx_messageInfo_GetDataWrittenByQueryEnvelope.Size(m)
}
func (m *GetDataWrittenByQueryEnvelope) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDataWrittenByQueryEnvelope.DiscardUnknown(m)
}

var xxx_messageInfo_GetDataWrittenByQueryEnvelope proto.InternalMessageInfo

func (m *GetDataWrittenByQueryEnvelope) GetPayload() *GetDataWrittenByQuery {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *GetDataWrittenByQueryEnvelope) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

type GetTxIDsSubmittedByQuery struct {
	UserID               string   `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID,omitempty"`
	TargetUserID         string   `protobuf:"bytes,2,opt,name=target_userID,json=targetUserID,proto3" json:"target_userID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetTxIDsSubmittedByQuery) Reset()         { *m = GetTxIDsSubmittedByQuery{} }
func (m *GetTxIDsSubmittedByQuery) String() string { return proto.CompactTextString(m) }
func (*GetTxIDsSubmittedByQuery) ProtoMessage()    {}
func (*GetTxIDsSubmittedByQuery) Descriptor() ([]byte, []int) {
	return fileDescriptor_5c6ac9b241082464, []int{26}
}

func (m *GetTxIDsSubmittedByQuery) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTxIDsSubmittedByQuery.Unmarshal(m, b)
}
func (m *GetTxIDsSubmittedByQuery) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTxIDsSubmittedByQuery.Marshal(b, m, deterministic)
}
func (m *GetTxIDsSubmittedByQuery) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTxIDsSubmittedByQuery.Merge(m, src)
}
func (m *GetTxIDsSubmittedByQuery) XXX_Size() int {
	return xxx_messageInfo_GetTxIDsSubmittedByQuery.Size(m)
}
func (m *GetTxIDsSubmittedByQuery) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTxIDsSubmittedByQuery.DiscardUnknown(m)
}

var xxx_messageInfo_GetTxIDsSubmittedByQuery proto.InternalMessageInfo

func (m *GetTxIDsSubmittedByQuery) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *GetTxIDsSubmittedByQuery) GetTargetUserID() string {
	if m != nil {
		return m.TargetUserID
	}
	return ""
}

type GetTxIDsSubmittedByQueryEnvelope struct {
	Payload              *GetTxIDsSubmittedByQuery `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	Signature            []byte                    `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *GetTxIDsSubmittedByQueryEnvelope) Reset()         { *m = GetTxIDsSubmittedByQueryEnvelope{} }
func (m *GetTxIDsSubmittedByQueryEnvelope) String() string { return proto.CompactTextString(m) }
func (*GetTxIDsSubmittedByQueryEnvelope) ProtoMessage()    {}
func (*GetTxIDsSubmittedByQueryEnvelope) Descriptor() ([]byte, []int) {
	return fileDescriptor_5c6ac9b241082464, []int{27}
}

func (m *GetTxIDsSubmittedByQueryEnvelope) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTxIDsSubmittedByQueryEnvelope.Unmarshal(m, b)
}
func (m *GetTxIDsSubmittedByQueryEnvelope) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTxIDsSubmittedByQueryEnvelope.Marshal(b, m, deterministic)
}
func (m *GetTxIDsSubmittedByQueryEnvelope) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTxIDsSubmittedByQueryEnvelope.Merge(m, src)
}
func (m *GetTxIDsSubmittedByQueryEnvelope) XXX_Size() int {
	return xxx_messageInfo_GetTxIDsSubmittedByQueryEnvelope.Size(m)
}
func (m *GetTxIDsSubmittedByQueryEnvelope) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTxIDsSubmittedByQueryEnvelope.DiscardUnknown(m)
}

var xxx_messageInfo_GetTxIDsSubmittedByQueryEnvelope proto.InternalMessageInfo

func (m *GetTxIDsSubmittedByQueryEnvelope) GetPayload() *GetTxIDsSubmittedByQuery {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *GetTxIDsSubmittedByQueryEnvelope) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

type GetTxReceiptQuery struct {
	UserID               string   `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID,omitempty"`
	TxID                 string   `protobuf:"bytes,2,opt,name=txID,proto3" json:"txID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetTxReceiptQuery) Reset()         { *m = GetTxReceiptQuery{} }
func (m *GetTxReceiptQuery) String() string { return proto.CompactTextString(m) }
func (*GetTxReceiptQuery) ProtoMessage()    {}
func (*GetTxReceiptQuery) Descriptor() ([]byte, []int) {
	return fileDescriptor_5c6ac9b241082464, []int{28}
}

func (m *GetTxReceiptQuery) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTxReceiptQuery.Unmarshal(m, b)
}
func (m *GetTxReceiptQuery) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTxReceiptQuery.Marshal(b, m, deterministic)
}
func (m *GetTxReceiptQuery) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTxReceiptQuery.Merge(m, src)
}
func (m *GetTxReceiptQuery) XXX_Size() int {
	return xxx_messageInfo_GetTxReceiptQuery.Size(m)
}
func (m *GetTxReceiptQuery) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTxReceiptQuery.DiscardUnknown(m)
}

var xxx_messageInfo_GetTxReceiptQuery proto.InternalMessageInfo

func (m *GetTxReceiptQuery) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *GetTxReceiptQuery) GetTxID() string {
	if m != nil {
		return m.TxID
	}
	return ""
}

type GetTxReceiptQueryEnvelope struct {
	Payload              *GetTxReceiptQuery `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	Signature            []byte             `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *GetTxReceiptQueryEnvelope) Reset()         { *m = GetTxReceiptQueryEnvelope{} }
func (m *GetTxReceiptQueryEnvelope) String() string { return proto.CompactTextString(m) }
func (*GetTxReceiptQueryEnvelope) ProtoMessage()    {}
func (*GetTxReceiptQueryEnvelope) Descriptor() ([]byte, []int) {
	return fileDescriptor_5c6ac9b241082464, []int{29}
}

func (m *GetTxReceiptQueryEnvelope) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTxReceiptQueryEnvelope.Unmarshal(m, b)
}
func (m *GetTxReceiptQueryEnvelope) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTxReceiptQueryEnvelope.Marshal(b, m, deterministic)
}
func (m *GetTxReceiptQueryEnvelope) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTxReceiptQueryEnvelope.Merge(m, src)
}
func (m *GetTxReceiptQueryEnvelope) XXX_Size() int {
	return xxx_messageInfo_GetTxReceiptQueryEnvelope.Size(m)
}
func (m *GetTxReceiptQueryEnvelope) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTxReceiptQueryEnvelope.DiscardUnknown(m)
}

var xxx_messageInfo_GetTxReceiptQueryEnvelope proto.InternalMessageInfo

func (m *GetTxReceiptQueryEnvelope) GetPayload() *GetTxReceiptQuery {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *GetTxReceiptQueryEnvelope) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

func init() {
	proto.RegisterType((*GetDBStatusQueryEnvelope)(nil), "types.GetDBStatusQueryEnvelope")
	proto.RegisterType((*GetDBStatusQuery)(nil), "types.GetDBStatusQuery")
	proto.RegisterType((*GetDataQueryEnvelope)(nil), "types.GetDataQueryEnvelope")
	proto.RegisterType((*GetDataQuery)(nil), "types.GetDataQuery")
	proto.RegisterType((*GetUserQueryEnvelope)(nil), "types.GetUserQueryEnvelope")
	proto.RegisterType((*GetUserQuery)(nil), "types.GetUserQuery")
	proto.RegisterType((*GetConfigQueryEnvelope)(nil), "types.GetConfigQueryEnvelope")
	proto.RegisterType((*GetConfigQuery)(nil), "types.GetConfigQuery")
	proto.RegisterType((*GetNodeConfigQueryEnvelope)(nil), "types.GetNodeConfigQueryEnvelope")
	proto.RegisterType((*GetNodeConfigQuery)(nil), "types.GetNodeConfigQuery")
	proto.RegisterType((*GetBlockQuery)(nil), "types.GetBlockQuery")
	proto.RegisterType((*GetBlockQueryEnvelope)(nil), "types.GetBlockQueryEnvelope")
	proto.RegisterType((*GetLedgerPathQuery)(nil), "types.GetLedgerPathQuery")
	proto.RegisterType((*GetLedgerPathQueryEnvelope)(nil), "types.GetLedgerPathQueryEnvelope")
	proto.RegisterType((*GetTxProofQuery)(nil), "types.GetTxProofQuery")
	proto.RegisterType((*GetTxProofQueryEnvelope)(nil), "types.GetTxProofQueryEnvelope")
	proto.RegisterType((*GetHistoricalDataQuery)(nil), "types.GetHistoricalDataQuery")
	proto.RegisterType((*GetHistoricalDataQueryEnvelope)(nil), "types.GetHistoricalDataQueryEnvelope")
	proto.RegisterType((*GetDataReadersQuery)(nil), "types.GetDataReadersQuery")
	proto.RegisterType((*GetDataReadersQueryEnvelope)(nil), "types.GetDataReadersQueryEnvelope")
	proto.RegisterType((*GetDataWritersQuery)(nil), "types.GetDataWritersQuery")
	proto.RegisterType((*GetDataWritersQueryEnvelope)(nil), "types.GetDataWritersQueryEnvelope")
	proto.RegisterType((*GetDataReadByQuery)(nil), "types.GetDataReadByQuery")
	proto.RegisterType((*GetDataReadByQueryEnvelope)(nil), "types.GetDataReadByQueryEnvelope")
	proto.RegisterType((*GetDataWrittenByQuery)(nil), "types.GetDataWrittenByQuery")
	proto.RegisterType((*GetDataWrittenByQueryEnvelope)(nil), "types.GetDataWrittenByQueryEnvelope")
	proto.RegisterType((*GetTxIDsSubmittedByQuery)(nil), "types.GetTxIDsSubmittedByQuery")
	proto.RegisterType((*GetTxIDsSubmittedByQueryEnvelope)(nil), "types.GetTxIDsSubmittedByQueryEnvelope")
	proto.RegisterType((*GetTxReceiptQuery)(nil), "types.GetTxReceiptQuery")
	proto.RegisterType((*GetTxReceiptQueryEnvelope)(nil), "types.GetTxReceiptQueryEnvelope")
}

func init() { proto.RegisterFile("query.proto", fileDescriptor_5c6ac9b241082464) }

var fileDescriptor_5c6ac9b241082464 = []byte{
	// 752 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x96, 0xdb, 0x6f, 0x12, 0x41,
	0x14, 0xc6, 0x83, 0xbd, 0xd9, 0x53, 0x5a, 0x71, 0x7b, 0xdb, 0xde, 0xb4, 0xae, 0x2f, 0xc4, 0x28,
	0x68, 0x6b, 0x34, 0x3e, 0x99, 0x20, 0x06, 0x69, 0x4c, 0xd3, 0x6e, 0xab, 0x4d, 0x7c, 0x21, 0x03,
	0x7b, 0x4a, 0x27, 0x85, 0x19, 0x3a, 0x3b, 0x5b, 0x21, 0xbe, 0xfa, 0x97, 0xf8, 0x97, 0x9a, 0x1d,
	0x96, 0xdd, 0x65, 0x0a, 0x64, 0x1a, 0xf1, 0x8d, 0x39, 0x9c, 0xef, 0xdb, 0xdf, 0x37, 0xc3, 0x9e,
	0x01, 0x96, 0x6e, 0x02, 0x14, 0xbd, 0x42, 0x47, 0x70, 0xc9, 0xad, 0x39, 0xd9, 0xeb, 0xa0, 0xbf,
	0xbd, 0x53, 0x6f, 0xf1, 0xc6, 0x75, 0x8d, 0x30, 0xaf, 0x26, 0x05, 0x61, 0x3e, 0x69, 0x48, 0xca,
	0x59, 0xbf, 0xc7, 0xb9, 0x06, 0xbb, 0x82, 0xb2, 0x5c, 0x3a, 0x93, 0x44, 0x06, 0xfe, 0x69, 0xa8,
	0xfe, 0xcc, 0x6e, 0xb1, 0xc5, 0x3b, 0x68, 0xbd, 0x81, 0x85, 0x0e, 0xe9, 0xb5, 0x38, 0xf1, 0xec,
	0xcc, 0x7e, 0x26, 0xbf, 0x74, 0xb0, 0x59, 0x50, 0x8e, 0x05, 0x5d, 0xe1, 0x0e, 0xfa, 0xac, 0x5d,
	0x58, 0xf4, 0x69, 0x93, 0x11, 0x19, 0x08, 0xb4, 0x1f, 0xec, 0x67, 0xf2, 0x59, 0x37, 0x29, 0x38,
	0x25, 0xc8, 0xe9, 0x52, 0x6b, 0x03, 0xe6, 0x03, 0x1f, 0x45, 0xb5, 0xac, 0x9e, 0xb1, 0xe8, 0x46,
	0xab, 0xb0, 0x5e, 0x2e, 0x1d, 0x93, 0x76, 0xdf, 0x66, 0xd1, 0x8d, 0x56, 0x4e, 0x03, 0xd6, 0x42,
	0x0f, 0x22, 0xc9, 0x30, 0xec, 0x2b, 0x1d, 0x76, 0x35, 0x05, 0x3b, 0xe8, 0x36, 0x05, 0x3d, 0x81,
	0x6c, 0x5a, 0x76, 0x5f, 0x48, 0x2b, 0x07, 0x33, 0xd7, 0xd8, 0xb3, 0x67, 0x54, 0x31, 0xfc, 0x18,
	0x61, 0x7f, 0xf3, 0x51, 0x98, 0x63, 0xc7, 0xdd, 0xa6, 0xd8, 0x47, 0x0a, 0x3b, 0x96, 0x8d, 0xc5,
	0x76, 0x20, 0x2b, 0x89, 0x68, 0xf6, 0x5b, 0xab, 0xe5, 0x08, 0x7e, 0xa8, 0xe6, 0x34, 0x61, 0xa3,
	0x82, 0xf2, 0x13, 0x67, 0x97, 0xb4, 0x39, 0x8c, 0x5c, 0xd4, 0x91, 0xd7, 0x13, 0xe4, 0x54, 0xbf,
	0x29, 0x74, 0x1e, 0x56, 0x86, 0x85, 0xe3, 0xb0, 0x1d, 0x0e, 0xdb, 0x15, 0x94, 0xc7, 0xdc, 0xc3,
	0x51, 0x58, 0x87, 0x3a, 0xd6, 0x56, 0x82, 0xa5, 0x69, 0x4c, 0xd1, 0xca, 0x60, 0xdd, 0x15, 0x4f,
	0xfa, 0x31, 0x30, 0xee, 0x61, 0xbc, 0x9f, 0xd1, 0xca, 0x39, 0x82, 0xe5, 0x0a, 0xca, 0x52, 0xf8,
	0x12, 0x4e, 0x36, 0x78, 0x06, 0xd9, 0xfe, 0xab, 0xca, 0x82, 0x76, 0x1d, 0x85, 0xb2, 0x99, 0x75,
	0x97, 0x54, 0xed, 0x58, 0x95, 0x1c, 0x84, 0xf5, 0x21, 0xaf, 0x38, 0x7d, 0x41, 0x4f, 0xbf, 0x96,
	0xa4, 0x4f, 0xda, 0x4d, 0x83, 0xff, 0xce, 0xa8, 0xe4, 0x5f, 0xd1, 0x6b, 0xa2, 0x38, 0x21, 0xf2,
	0x6a, 0x32, 0xf8, 0x4b, 0xb0, 0x7c, 0x49, 0x84, 0xac, 0x8d, 0xc0, 0xcf, 0xa9, 0x6f, 0x4a, 0x49,
	0x06, 0x2b, 0x0f, 0x39, 0x64, 0xde, 0x70, 0xef, 0x8c, 0xea, 0x5d, 0x41, 0xe6, 0xa5, 0x3a, 0xa3,
	0x03, 0xd7, 0x28, 0x8c, 0x0e, 0x5c, 0xd3, 0x98, 0xe6, 0x6e, 0xc2, 0xa3, 0x0a, 0xca, 0xf3, 0xee,
	0x89, 0xe0, 0xfc, 0xf2, 0x5f, 0x0f, 0xcb, 0xda, 0x82, 0x87, 0xb2, 0x5b, 0xa3, 0xcc, 0xc3, 0x6e,
	0x14, 0x70, 0x41, 0x76, 0xab, 0xe1, 0xd2, 0xa1, 0xb0, 0xa9, 0x3d, 0x28, 0x8e, 0xf5, 0x5a, 0x8f,
	0xb5, 0x91, 0xc4, 0x4a, 0x0b, 0x4c, 0x33, 0xfd, 0xc9, 0xa8, 0x37, 0xf9, 0x0b, 0xf5, 0x25, 0x17,
	0xb4, 0x41, 0x5a, 0x53, 0x1c, 0x6b, 0x56, 0x1e, 0x16, 0x6e, 0x51, 0xf8, 0x94, 0x33, 0x7b, 0x56,
	0xc1, 0xae, 0x44, 0xb0, 0xdf, 0xfb, 0x55, 0x77, 0xf0, 0x75, 0x08, 0xe9, 0x51, 0x81, 0xea, 0xee,
	0xb1, 0xe7, 0x94, 0x43, 0x52, 0x70, 0x7e, 0xc2, 0x93, 0xd1, 0x8c, 0xf1, 0xb6, 0xbc, 0xd7, 0xb7,
	0x65, 0x2f, 0xd9, 0x96, 0x11, 0x3a, 0xd3, 0xdd, 0xb9, 0x80, 0xd5, 0x68, 0xd2, 0xbb, 0x48, 0x3c,
	0x14, 0xfe, 0xb4, 0x06, 0xfe, 0x0d, 0xec, 0x8c, 0x30, 0x8e, 0xe3, 0xbc, 0xd5, 0xe3, 0x6c, 0x0f,
	0x5f, 0x57, 0x69, 0xd1, 0xfd, 0xb3, 0x5c, 0x08, 0x2a, 0xff, 0x4b, 0x96, 0xb4, 0xb1, 0x71, 0x96,
	0xb4, 0xc8, 0x34, 0xcb, 0xa9, 0x1a, 0x40, 0x83, 0x9d, 0x28, 0xf5, 0x26, 0x47, 0x79, 0x0e, 0xcb,
	0xfd, 0xcb, 0xab, 0x16, 0x8c, 0xbf, 0xd1, 0xfa, 0xd3, 0x44, 0xb3, 0x34, 0x9a, 0x26, 0x9a, 0xc6,
	0x34, 0xc3, 0xb9, 0x1a, 0xd6, 0x83, 0x1d, 0x90, 0xc8, 0xa6, 0x12, 0x23, 0x80, 0xbd, 0x91, 0xae,
	0x71, 0x92, 0x77, 0x7a, 0x92, 0xdd, 0xbb, 0xc7, 0x91, 0xc8, 0xcc, 0x7f, 0x5c, 0xb6, 0x1a, 0x40,
	0xd5, 0xb2, 0x7f, 0x16, 0xd4, 0xdb, 0xa1, 0xc5, 0x74, 0x8e, 0xe5, 0x17, 0xec, 0x8f, 0x33, 0x8e,
	0x23, 0x7d, 0xd0, 0x23, 0x3d, 0x4d, 0xcf, 0xc4, 0x11, 0x4a, 0xd3, 0x54, 0x1f, 0xe1, 0xb1, 0xb2,
	0x70, 0xb1, 0x81, 0xb4, 0x23, 0x27, 0xc7, 0xb1, 0x60, 0x56, 0x76, 0xe3, 0x14, 0xea, 0xb3, 0xd3,
	0x86, 0xad, 0x3b, 0x06, 0x31, 0xf6, 0x81, 0x8e, 0x6d, 0xa7, 0xb1, 0xd3, 0x12, 0x43, 0xde, 0xd2,
	0x8b, 0x1f, 0xf9, 0x26, 0x95, 0x57, 0x41, 0xbd, 0x40, 0xeb, 0xed, 0x42, 0x83, 0xb7, 0x8b, 0xea,
	0xc2, 0x69, 0x5c, 0x11, 0xca, 0xbc, 0x7a, 0x51, 0xfd, 0xa7, 0xf7, 0x8b, 0xea, 0x21, 0xf5, 0x79,
	0xb5, 0x3a, 0xfc, 0x1b, 0x00, 0x00, 0xff, 0xff, 0xa6, 0xf0, 0x0c, 0x32, 0x14, 0x0c, 0x00, 0x00,
}
