// Code generated by protoc-gen-go. DO NOT EDIT.
// source: query_and_response.proto

package types

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Flag int32

const (
	Flag_VALID                                      Flag = 0
	Flag_INVALID_MVCC_CONFLICT_WITHIN_BLOCK         Flag = 1
	Flag_INVALID_MVCC_CONFLICT_WITH_COMMITTED_STATE Flag = 2
	Flag_INVALID_DATABASE_DOES_NOT_EXIST            Flag = 3
	Flag_INVALID_NO_PERMISSION                      Flag = 4
	Flag_INVALID_INCORRECT_ENTRIES                  Flag = 5
)

var Flag_name = map[int32]string{
	0: "VALID",
	1: "INVALID_MVCC_CONFLICT_WITHIN_BLOCK",
	2: "INVALID_MVCC_CONFLICT_WITH_COMMITTED_STATE",
	3: "INVALID_DATABASE_DOES_NOT_EXIST",
	4: "INVALID_NO_PERMISSION",
	5: "INVALID_INCORRECT_ENTRIES",
}

var Flag_value = map[string]int32{
	"VALID":                              0,
	"INVALID_MVCC_CONFLICT_WITHIN_BLOCK": 1,
	"INVALID_MVCC_CONFLICT_WITH_COMMITTED_STATE": 2,
	"INVALID_DATABASE_DOES_NOT_EXIST":            3,
	"INVALID_NO_PERMISSION":                      4,
	"INVALID_INCORRECT_ENTRIES":                  5,
}

func (x Flag) String() string {
	return proto.EnumName(Flag_name, int32(x))
}

func (Flag) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_998b839b037f2547, []int{0}
}

type GetDBStatusQueryEnvelope struct {
	Payload              *GetDBStatusQuery `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	Signature            []byte            `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *GetDBStatusQueryEnvelope) Reset()         { *m = GetDBStatusQueryEnvelope{} }
func (m *GetDBStatusQueryEnvelope) String() string { return proto.CompactTextString(m) }
func (*GetDBStatusQueryEnvelope) ProtoMessage()    {}
func (*GetDBStatusQueryEnvelope) Descriptor() ([]byte, []int) {
	return fileDescriptor_998b839b037f2547, []int{0}
}

func (m *GetDBStatusQueryEnvelope) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDBStatusQueryEnvelope.Unmarshal(m, b)
}
func (m *GetDBStatusQueryEnvelope) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDBStatusQueryEnvelope.Marshal(b, m, deterministic)
}
func (m *GetDBStatusQueryEnvelope) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDBStatusQueryEnvelope.Merge(m, src)
}
func (m *GetDBStatusQueryEnvelope) XXX_Size() int {
	return xxx_messageInfo_GetDBStatusQueryEnvelope.Size(m)
}
func (m *GetDBStatusQueryEnvelope) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDBStatusQueryEnvelope.DiscardUnknown(m)
}

var xxx_messageInfo_GetDBStatusQueryEnvelope proto.InternalMessageInfo

func (m *GetDBStatusQueryEnvelope) GetPayload() *GetDBStatusQuery {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *GetDBStatusQueryEnvelope) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

type GetDBStatusQuery struct {
	UserID               string   `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID,omitempty"`
	DBName               string   `protobuf:"bytes,2,opt,name=DBName,proto3" json:"DBName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetDBStatusQuery) Reset()         { *m = GetDBStatusQuery{} }
func (m *GetDBStatusQuery) String() string { return proto.CompactTextString(m) }
func (*GetDBStatusQuery) ProtoMessage()    {}
func (*GetDBStatusQuery) Descriptor() ([]byte, []int) {
	return fileDescriptor_998b839b037f2547, []int{1}
}

func (m *GetDBStatusQuery) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDBStatusQuery.Unmarshal(m, b)
}
func (m *GetDBStatusQuery) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDBStatusQuery.Marshal(b, m, deterministic)
}
func (m *GetDBStatusQuery) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDBStatusQuery.Merge(m, src)
}
func (m *GetDBStatusQuery) XXX_Size() int {
	return xxx_messageInfo_GetDBStatusQuery.Size(m)
}
func (m *GetDBStatusQuery) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDBStatusQuery.DiscardUnknown(m)
}

var xxx_messageInfo_GetDBStatusQuery proto.InternalMessageInfo

func (m *GetDBStatusQuery) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *GetDBStatusQuery) GetDBName() string {
	if m != nil {
		return m.DBName
	}
	return ""
}

type GetDBStatusResponseEnvelope struct {
	Payload              *GetDBStatusResponse `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	Signature            []byte               `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *GetDBStatusResponseEnvelope) Reset()         { *m = GetDBStatusResponseEnvelope{} }
func (m *GetDBStatusResponseEnvelope) String() string { return proto.CompactTextString(m) }
func (*GetDBStatusResponseEnvelope) ProtoMessage()    {}
func (*GetDBStatusResponseEnvelope) Descriptor() ([]byte, []int) {
	return fileDescriptor_998b839b037f2547, []int{2}
}

func (m *GetDBStatusResponseEnvelope) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDBStatusResponseEnvelope.Unmarshal(m, b)
}
func (m *GetDBStatusResponseEnvelope) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDBStatusResponseEnvelope.Marshal(b, m, deterministic)
}
func (m *GetDBStatusResponseEnvelope) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDBStatusResponseEnvelope.Merge(m, src)
}
func (m *GetDBStatusResponseEnvelope) XXX_Size() int {
	return xxx_messageInfo_GetDBStatusResponseEnvelope.Size(m)
}
func (m *GetDBStatusResponseEnvelope) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDBStatusResponseEnvelope.DiscardUnknown(m)
}

var xxx_messageInfo_GetDBStatusResponseEnvelope proto.InternalMessageInfo

func (m *GetDBStatusResponseEnvelope) GetPayload() *GetDBStatusResponse {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *GetDBStatusResponseEnvelope) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

type GetDBStatusResponse struct {
	Header               *ResponseHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Exist                bool            `protobuf:"varint,2,opt,name=exist,proto3" json:"exist,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *GetDBStatusResponse) Reset()         { *m = GetDBStatusResponse{} }
func (m *GetDBStatusResponse) String() string { return proto.CompactTextString(m) }
func (*GetDBStatusResponse) ProtoMessage()    {}
func (*GetDBStatusResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_998b839b037f2547, []int{3}
}

func (m *GetDBStatusResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDBStatusResponse.Unmarshal(m, b)
}
func (m *GetDBStatusResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDBStatusResponse.Marshal(b, m, deterministic)
}
func (m *GetDBStatusResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDBStatusResponse.Merge(m, src)
}
func (m *GetDBStatusResponse) XXX_Size() int {
	return xxx_messageInfo_GetDBStatusResponse.Size(m)
}
func (m *GetDBStatusResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDBStatusResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetDBStatusResponse proto.InternalMessageInfo

func (m *GetDBStatusResponse) GetHeader() *ResponseHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *GetDBStatusResponse) GetExist() bool {
	if m != nil {
		return m.Exist
	}
	return false
}

type GetDataQueryEnvelope struct {
	Payload              *GetDataQuery `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	Signature            []byte        `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *GetDataQueryEnvelope) Reset()         { *m = GetDataQueryEnvelope{} }
func (m *GetDataQueryEnvelope) String() string { return proto.CompactTextString(m) }
func (*GetDataQueryEnvelope) ProtoMessage()    {}
func (*GetDataQueryEnvelope) Descriptor() ([]byte, []int) {
	return fileDescriptor_998b839b037f2547, []int{4}
}

func (m *GetDataQueryEnvelope) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDataQueryEnvelope.Unmarshal(m, b)
}
func (m *GetDataQueryEnvelope) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDataQueryEnvelope.Marshal(b, m, deterministic)
}
func (m *GetDataQueryEnvelope) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDataQueryEnvelope.Merge(m, src)
}
func (m *GetDataQueryEnvelope) XXX_Size() int {
	return xxx_messageInfo_GetDataQueryEnvelope.Size(m)
}
func (m *GetDataQueryEnvelope) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDataQueryEnvelope.DiscardUnknown(m)
}

var xxx_messageInfo_GetDataQueryEnvelope proto.InternalMessageInfo

func (m *GetDataQueryEnvelope) GetPayload() *GetDataQuery {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *GetDataQueryEnvelope) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

type GetDataQuery struct {
	UserID               string   `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID,omitempty"`
	DBName               string   `protobuf:"bytes,2,opt,name=DBName,proto3" json:"DBName,omitempty"`
	Key                  string   `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetDataQuery) Reset()         { *m = GetDataQuery{} }
func (m *GetDataQuery) String() string { return proto.CompactTextString(m) }
func (*GetDataQuery) ProtoMessage()    {}
func (*GetDataQuery) Descriptor() ([]byte, []int) {
	return fileDescriptor_998b839b037f2547, []int{5}
}

func (m *GetDataQuery) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDataQuery.Unmarshal(m, b)
}
func (m *GetDataQuery) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDataQuery.Marshal(b, m, deterministic)
}
func (m *GetDataQuery) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDataQuery.Merge(m, src)
}
func (m *GetDataQuery) XXX_Size() int {
	return xxx_messageInfo_GetDataQuery.Size(m)
}
func (m *GetDataQuery) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDataQuery.DiscardUnknown(m)
}

var xxx_messageInfo_GetDataQuery proto.InternalMessageInfo

func (m *GetDataQuery) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *GetDataQuery) GetDBName() string {
	if m != nil {
		return m.DBName
	}
	return ""
}

func (m *GetDataQuery) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type GetDataResponseEnvelope struct {
	Payload              *GetDataResponse `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	Signature            []byte           `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *GetDataResponseEnvelope) Reset()         { *m = GetDataResponseEnvelope{} }
func (m *GetDataResponseEnvelope) String() string { return proto.CompactTextString(m) }
func (*GetDataResponseEnvelope) ProtoMessage()    {}
func (*GetDataResponseEnvelope) Descriptor() ([]byte, []int) {
	return fileDescriptor_998b839b037f2547, []int{6}
}

func (m *GetDataResponseEnvelope) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDataResponseEnvelope.Unmarshal(m, b)
}
func (m *GetDataResponseEnvelope) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDataResponseEnvelope.Marshal(b, m, deterministic)
}
func (m *GetDataResponseEnvelope) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDataResponseEnvelope.Merge(m, src)
}
func (m *GetDataResponseEnvelope) XXX_Size() int {
	return xxx_messageInfo_GetDataResponseEnvelope.Size(m)
}
func (m *GetDataResponseEnvelope) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDataResponseEnvelope.DiscardUnknown(m)
}

var xxx_messageInfo_GetDataResponseEnvelope proto.InternalMessageInfo

func (m *GetDataResponseEnvelope) GetPayload() *GetDataResponse {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *GetDataResponseEnvelope) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

type GetDataResponse struct {
	Header               *ResponseHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Value                []byte          `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Metadata             *Metadata       `protobuf:"bytes,3,opt,name=metadata,proto3" json:"metadata,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *GetDataResponse) Reset()         { *m = GetDataResponse{} }
func (m *GetDataResponse) String() string { return proto.CompactTextString(m) }
func (*GetDataResponse) ProtoMessage()    {}
func (*GetDataResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_998b839b037f2547, []int{7}
}

func (m *GetDataResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDataResponse.Unmarshal(m, b)
}
func (m *GetDataResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDataResponse.Marshal(b, m, deterministic)
}
func (m *GetDataResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDataResponse.Merge(m, src)
}
func (m *GetDataResponse) XXX_Size() int {
	return xxx_messageInfo_GetDataResponse.Size(m)
}
func (m *GetDataResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDataResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetDataResponse proto.InternalMessageInfo

func (m *GetDataResponse) GetHeader() *ResponseHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *GetDataResponse) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *GetDataResponse) GetMetadata() *Metadata {
	if m != nil {
		return m.Metadata
	}
	return nil
}

type GetUserQueryEnvelope struct {
	Payload              *GetUserQuery `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	Signature            []byte        `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *GetUserQueryEnvelope) Reset()         { *m = GetUserQueryEnvelope{} }
func (m *GetUserQueryEnvelope) String() string { return proto.CompactTextString(m) }
func (*GetUserQueryEnvelope) ProtoMessage()    {}
func (*GetUserQueryEnvelope) Descriptor() ([]byte, []int) {
	return fileDescriptor_998b839b037f2547, []int{8}
}

func (m *GetUserQueryEnvelope) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserQueryEnvelope.Unmarshal(m, b)
}
func (m *GetUserQueryEnvelope) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserQueryEnvelope.Marshal(b, m, deterministic)
}
func (m *GetUserQueryEnvelope) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserQueryEnvelope.Merge(m, src)
}
func (m *GetUserQueryEnvelope) XXX_Size() int {
	return xxx_messageInfo_GetUserQueryEnvelope.Size(m)
}
func (m *GetUserQueryEnvelope) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserQueryEnvelope.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserQueryEnvelope proto.InternalMessageInfo

func (m *GetUserQueryEnvelope) GetPayload() *GetUserQuery {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *GetUserQueryEnvelope) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

type GetUserQuery struct {
	UserID               string   `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID,omitempty"`
	TargetUserID         string   `protobuf:"bytes,2,opt,name=targetUserID,proto3" json:"targetUserID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserQuery) Reset()         { *m = GetUserQuery{} }
func (m *GetUserQuery) String() string { return proto.CompactTextString(m) }
func (*GetUserQuery) ProtoMessage()    {}
func (*GetUserQuery) Descriptor() ([]byte, []int) {
	return fileDescriptor_998b839b037f2547, []int{9}
}

func (m *GetUserQuery) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserQuery.Unmarshal(m, b)
}
func (m *GetUserQuery) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserQuery.Marshal(b, m, deterministic)
}
func (m *GetUserQuery) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserQuery.Merge(m, src)
}
func (m *GetUserQuery) XXX_Size() int {
	return xxx_messageInfo_GetUserQuery.Size(m)
}
func (m *GetUserQuery) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserQuery.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserQuery proto.InternalMessageInfo

func (m *GetUserQuery) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *GetUserQuery) GetTargetUserID() string {
	if m != nil {
		return m.TargetUserID
	}
	return ""
}

type GetUserResponseEnvelope struct {
	Payload              *GetUserResponse `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	Signature            []byte           `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *GetUserResponseEnvelope) Reset()         { *m = GetUserResponseEnvelope{} }
func (m *GetUserResponseEnvelope) String() string { return proto.CompactTextString(m) }
func (*GetUserResponseEnvelope) ProtoMessage()    {}
func (*GetUserResponseEnvelope) Descriptor() ([]byte, []int) {
	return fileDescriptor_998b839b037f2547, []int{10}
}

func (m *GetUserResponseEnvelope) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserResponseEnvelope.Unmarshal(m, b)
}
func (m *GetUserResponseEnvelope) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserResponseEnvelope.Marshal(b, m, deterministic)
}
func (m *GetUserResponseEnvelope) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserResponseEnvelope.Merge(m, src)
}
func (m *GetUserResponseEnvelope) XXX_Size() int {
	return xxx_messageInfo_GetUserResponseEnvelope.Size(m)
}
func (m *GetUserResponseEnvelope) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserResponseEnvelope.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserResponseEnvelope proto.InternalMessageInfo

func (m *GetUserResponseEnvelope) GetPayload() *GetUserResponse {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *GetUserResponseEnvelope) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

type GetUserResponse struct {
	Header               *ResponseHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	User                 *User           `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	Metadata             *Metadata       `protobuf:"bytes,3,opt,name=metadata,proto3" json:"metadata,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *GetUserResponse) Reset()         { *m = GetUserResponse{} }
func (m *GetUserResponse) String() string { return proto.CompactTextString(m) }
func (*GetUserResponse) ProtoMessage()    {}
func (*GetUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_998b839b037f2547, []int{11}
}

func (m *GetUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserResponse.Unmarshal(m, b)
}
func (m *GetUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserResponse.Marshal(b, m, deterministic)
}
func (m *GetUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserResponse.Merge(m, src)
}
func (m *GetUserResponse) XXX_Size() int {
	return xxx_messageInfo_GetUserResponse.Size(m)
}
func (m *GetUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserResponse proto.InternalMessageInfo

func (m *GetUserResponse) GetHeader() *ResponseHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *GetUserResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *GetUserResponse) GetMetadata() *Metadata {
	if m != nil {
		return m.Metadata
	}
	return nil
}

type GetConfigQueryEnvelope struct {
	Payload              *GetConfigQuery `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	Signature            []byte          `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *GetConfigQueryEnvelope) Reset()         { *m = GetConfigQueryEnvelope{} }
func (m *GetConfigQueryEnvelope) String() string { return proto.CompactTextString(m) }
func (*GetConfigQueryEnvelope) ProtoMessage()    {}
func (*GetConfigQueryEnvelope) Descriptor() ([]byte, []int) {
	return fileDescriptor_998b839b037f2547, []int{12}
}

func (m *GetConfigQueryEnvelope) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetConfigQueryEnvelope.Unmarshal(m, b)
}
func (m *GetConfigQueryEnvelope) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetConfigQueryEnvelope.Marshal(b, m, deterministic)
}
func (m *GetConfigQueryEnvelope) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetConfigQueryEnvelope.Merge(m, src)
}
func (m *GetConfigQueryEnvelope) XXX_Size() int {
	return xxx_messageInfo_GetConfigQueryEnvelope.Size(m)
}
func (m *GetConfigQueryEnvelope) XXX_DiscardUnknown() {
	xxx_messageInfo_GetConfigQueryEnvelope.DiscardUnknown(m)
}

var xxx_messageInfo_GetConfigQueryEnvelope proto.InternalMessageInfo

func (m *GetConfigQueryEnvelope) GetPayload() *GetConfigQuery {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *GetConfigQueryEnvelope) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

type GetConfigQuery struct {
	UserID               string   `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetConfigQuery) Reset()         { *m = GetConfigQuery{} }
func (m *GetConfigQuery) String() string { return proto.CompactTextString(m) }
func (*GetConfigQuery) ProtoMessage()    {}
func (*GetConfigQuery) Descriptor() ([]byte, []int) {
	return fileDescriptor_998b839b037f2547, []int{13}
}

func (m *GetConfigQuery) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetConfigQuery.Unmarshal(m, b)
}
func (m *GetConfigQuery) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetConfigQuery.Marshal(b, m, deterministic)
}
func (m *GetConfigQuery) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetConfigQuery.Merge(m, src)
}
func (m *GetConfigQuery) XXX_Size() int {
	return xxx_messageInfo_GetConfigQuery.Size(m)
}
func (m *GetConfigQuery) XXX_DiscardUnknown() {
	xxx_messageInfo_GetConfigQuery.DiscardUnknown(m)
}

var xxx_messageInfo_GetConfigQuery proto.InternalMessageInfo

func (m *GetConfigQuery) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

type GetConfigResponseEnvelope struct {
	Payload              *GetConfigResponse `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	Signature            []byte             `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *GetConfigResponseEnvelope) Reset()         { *m = GetConfigResponseEnvelope{} }
func (m *GetConfigResponseEnvelope) String() string { return proto.CompactTextString(m) }
func (*GetConfigResponseEnvelope) ProtoMessage()    {}
func (*GetConfigResponseEnvelope) Descriptor() ([]byte, []int) {
	return fileDescriptor_998b839b037f2547, []int{14}
}

func (m *GetConfigResponseEnvelope) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetConfigResponseEnvelope.Unmarshal(m, b)
}
func (m *GetConfigResponseEnvelope) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetConfigResponseEnvelope.Marshal(b, m, deterministic)
}
func (m *GetConfigResponseEnvelope) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetConfigResponseEnvelope.Merge(m, src)
}
func (m *GetConfigResponseEnvelope) XXX_Size() int {
	return xxx_messageInfo_GetConfigResponseEnvelope.Size(m)
}
func (m *GetConfigResponseEnvelope) XXX_DiscardUnknown() {
	xxx_messageInfo_GetConfigResponseEnvelope.DiscardUnknown(m)
}

var xxx_messageInfo_GetConfigResponseEnvelope proto.InternalMessageInfo

func (m *GetConfigResponseEnvelope) GetPayload() *GetConfigResponse {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *GetConfigResponseEnvelope) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

type GetConfigResponse struct {
	Header               *ResponseHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Config               *ClusterConfig  `protobuf:"bytes,2,opt,name=config,proto3" json:"config,omitempty"`
	Metadata             *Metadata       `protobuf:"bytes,3,opt,name=metadata,proto3" json:"metadata,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *GetConfigResponse) Reset()         { *m = GetConfigResponse{} }
func (m *GetConfigResponse) String() string { return proto.CompactTextString(m) }
func (*GetConfigResponse) ProtoMessage()    {}
func (*GetConfigResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_998b839b037f2547, []int{15}
}

func (m *GetConfigResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetConfigResponse.Unmarshal(m, b)
}
func (m *GetConfigResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetConfigResponse.Marshal(b, m, deterministic)
}
func (m *GetConfigResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetConfigResponse.Merge(m, src)
}
func (m *GetConfigResponse) XXX_Size() int {
	return xxx_messageInfo_GetConfigResponse.Size(m)
}
func (m *GetConfigResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetConfigResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetConfigResponse proto.InternalMessageInfo

func (m *GetConfigResponse) GetHeader() *ResponseHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *GetConfigResponse) GetConfig() *ClusterConfig {
	if m != nil {
		return m.Config
	}
	return nil
}

func (m *GetConfigResponse) GetMetadata() *Metadata {
	if m != nil {
		return m.Metadata
	}
	return nil
}

type Metadata struct {
	Version              *Version       `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	AccessControl        *AccessControl `protobuf:"bytes,2,opt,name=access_control,json=accessControl,proto3" json:"access_control,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Metadata) Reset()         { *m = Metadata{} }
func (m *Metadata) String() string { return proto.CompactTextString(m) }
func (*Metadata) ProtoMessage()    {}
func (*Metadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_998b839b037f2547, []int{16}
}

func (m *Metadata) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Metadata.Unmarshal(m, b)
}
func (m *Metadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Metadata.Marshal(b, m, deterministic)
}
func (m *Metadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Metadata.Merge(m, src)
}
func (m *Metadata) XXX_Size() int {
	return xxx_messageInfo_Metadata.Size(m)
}
func (m *Metadata) XXX_DiscardUnknown() {
	xxx_messageInfo_Metadata.DiscardUnknown(m)
}

var xxx_messageInfo_Metadata proto.InternalMessageInfo

func (m *Metadata) GetVersion() *Version {
	if m != nil {
		return m.Version
	}
	return nil
}

func (m *Metadata) GetAccessControl() *AccessControl {
	if m != nil {
		return m.AccessControl
	}
	return nil
}

type Version struct {
	BlockNum             uint64   `protobuf:"varint,1,opt,name=block_num,json=blockNum,proto3" json:"block_num,omitempty"`
	TxNum                uint64   `protobuf:"varint,2,opt,name=tx_num,json=txNum,proto3" json:"tx_num,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Version) Reset()         { *m = Version{} }
func (m *Version) String() string { return proto.CompactTextString(m) }
func (*Version) ProtoMessage()    {}
func (*Version) Descriptor() ([]byte, []int) {
	return fileDescriptor_998b839b037f2547, []int{17}
}

func (m *Version) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Version.Unmarshal(m, b)
}
func (m *Version) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Version.Marshal(b, m, deterministic)
}
func (m *Version) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Version.Merge(m, src)
}
func (m *Version) XXX_Size() int {
	return xxx_messageInfo_Version.Size(m)
}
func (m *Version) XXX_DiscardUnknown() {
	xxx_messageInfo_Version.DiscardUnknown(m)
}

var xxx_messageInfo_Version proto.InternalMessageInfo

func (m *Version) GetBlockNum() uint64 {
	if m != nil {
		return m.BlockNum
	}
	return 0
}

func (m *Version) GetTxNum() uint64 {
	if m != nil {
		return m.TxNum
	}
	return 0
}

type AccessControl struct {
	ReadUsers            map[string]bool `protobuf:"bytes,1,rep,name=read_users,json=readUsers,proto3" json:"read_users,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	ReadWriteUsers       map[string]bool `protobuf:"bytes,2,rep,name=read_write_users,json=readWriteUsers,proto3" json:"read_write_users,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *AccessControl) Reset()         { *m = AccessControl{} }
func (m *AccessControl) String() string { return proto.CompactTextString(m) }
func (*AccessControl) ProtoMessage()    {}
func (*AccessControl) Descriptor() ([]byte, []int) {
	return fileDescriptor_998b839b037f2547, []int{18}
}

func (m *AccessControl) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccessControl.Unmarshal(m, b)
}
func (m *AccessControl) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccessControl.Marshal(b, m, deterministic)
}
func (m *AccessControl) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccessControl.Merge(m, src)
}
func (m *AccessControl) XXX_Size() int {
	return xxx_messageInfo_AccessControl.Size(m)
}
func (m *AccessControl) XXX_DiscardUnknown() {
	xxx_messageInfo_AccessControl.DiscardUnknown(m)
}

var xxx_messageInfo_AccessControl proto.InternalMessageInfo

func (m *AccessControl) GetReadUsers() map[string]bool {
	if m != nil {
		return m.ReadUsers
	}
	return nil
}

func (m *AccessControl) GetReadWriteUsers() map[string]bool {
	if m != nil {
		return m.ReadWriteUsers
	}
	return nil
}

type Digest struct {
	// Ledger merkle tree root
	RootHash []byte `protobuf:"bytes,1,opt,name=root_hash,json=rootHash,proto3" json:"root_hash,omitempty"`
	// Ledger height
	Height               uint64   `protobuf:"varint,2,opt,name=height,proto3" json:"height,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Digest) Reset()         { *m = Digest{} }
func (m *Digest) String() string { return proto.CompactTextString(m) }
func (*Digest) ProtoMessage()    {}
func (*Digest) Descriptor() ([]byte, []int) {
	return fileDescriptor_998b839b037f2547, []int{19}
}

func (m *Digest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Digest.Unmarshal(m, b)
}
func (m *Digest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Digest.Marshal(b, m, deterministic)
}
func (m *Digest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Digest.Merge(m, src)
}
func (m *Digest) XXX_Size() int {
	return xxx_messageInfo_Digest.Size(m)
}
func (m *Digest) XXX_DiscardUnknown() {
	xxx_messageInfo_Digest.DiscardUnknown(m)
}

var xxx_messageInfo_Digest proto.InternalMessageInfo

func (m *Digest) GetRootHash() []byte {
	if m != nil {
		return m.RootHash
	}
	return nil
}

func (m *Digest) GetHeight() uint64 {
	if m != nil {
		return m.Height
	}
	return 0
}

type ResponseHeader struct {
	NodeID               string   `protobuf:"bytes,1,opt,name=nodeID,proto3" json:"nodeID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResponseHeader) Reset()         { *m = ResponseHeader{} }
func (m *ResponseHeader) String() string { return proto.CompactTextString(m) }
func (*ResponseHeader) ProtoMessage()    {}
func (*ResponseHeader) Descriptor() ([]byte, []int) {
	return fileDescriptor_998b839b037f2547, []int{20}
}

func (m *ResponseHeader) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResponseHeader.Unmarshal(m, b)
}
func (m *ResponseHeader) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResponseHeader.Marshal(b, m, deterministic)
}
func (m *ResponseHeader) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponseHeader.Merge(m, src)
}
func (m *ResponseHeader) XXX_Size() int {
	return xxx_messageInfo_ResponseHeader.Size(m)
}
func (m *ResponseHeader) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponseHeader.DiscardUnknown(m)
}

var xxx_messageInfo_ResponseHeader proto.InternalMessageInfo

func (m *ResponseHeader) GetNodeID() string {
	if m != nil {
		return m.NodeID
	}
	return ""
}

type Response struct {
	Header               *ResponseHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Txid                 []byte          `protobuf:"bytes,2,opt,name=txid,proto3" json:"txid,omitempty"`
	Status               bool            `protobuf:"varint,3,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_998b839b037f2547, []int{21}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetHeader() *ResponseHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *Response) GetTxid() []byte {
	if m != nil {
		return m.Txid
	}
	return nil
}

func (m *Response) GetStatus() bool {
	if m != nil {
		return m.Status
	}
	return false
}

type ResponseEnvelope struct {
	Data                 *Response `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Signature            []byte    `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ResponseEnvelope) Reset()         { *m = ResponseEnvelope{} }
func (m *ResponseEnvelope) String() string { return proto.CompactTextString(m) }
func (*ResponseEnvelope) ProtoMessage()    {}
func (*ResponseEnvelope) Descriptor() ([]byte, []int) {
	return fileDescriptor_998b839b037f2547, []int{22}
}

func (m *ResponseEnvelope) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResponseEnvelope.Unmarshal(m, b)
}
func (m *ResponseEnvelope) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResponseEnvelope.Marshal(b, m, deterministic)
}
func (m *ResponseEnvelope) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponseEnvelope.Merge(m, src)
}
func (m *ResponseEnvelope) XXX_Size() int {
	return xxx_messageInfo_ResponseEnvelope.Size(m)
}
func (m *ResponseEnvelope) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponseEnvelope.DiscardUnknown(m)
}

var xxx_messageInfo_ResponseEnvelope proto.InternalMessageInfo

func (m *ResponseEnvelope) GetData() *Response {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *ResponseEnvelope) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

type ValidationInfo struct {
	Flag                 Flag     `protobuf:"varint,1,opt,name=flag,proto3,enum=types.Flag" json:"flag,omitempty"`
	ReasonIfInvalid      string   `protobuf:"bytes,2,opt,name=reason_if_invalid,json=reasonIfInvalid,proto3" json:"reason_if_invalid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ValidationInfo) Reset()         { *m = ValidationInfo{} }
func (m *ValidationInfo) String() string { return proto.CompactTextString(m) }
func (*ValidationInfo) ProtoMessage()    {}
func (*ValidationInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_998b839b037f2547, []int{23}
}

func (m *ValidationInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ValidationInfo.Unmarshal(m, b)
}
func (m *ValidationInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ValidationInfo.Marshal(b, m, deterministic)
}
func (m *ValidationInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValidationInfo.Merge(m, src)
}
func (m *ValidationInfo) XXX_Size() int {
	return xxx_messageInfo_ValidationInfo.Size(m)
}
func (m *ValidationInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ValidationInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ValidationInfo proto.InternalMessageInfo

func (m *ValidationInfo) GetFlag() Flag {
	if m != nil {
		return m.Flag
	}
	return Flag_VALID
}

func (m *ValidationInfo) GetReasonIfInvalid() string {
	if m != nil {
		return m.ReasonIfInvalid
	}
	return ""
}

func init() {
	proto.RegisterEnum("types.Flag", Flag_name, Flag_value)
	proto.RegisterType((*GetDBStatusQueryEnvelope)(nil), "types.GetDBStatusQueryEnvelope")
	proto.RegisterType((*GetDBStatusQuery)(nil), "types.GetDBStatusQuery")
	proto.RegisterType((*GetDBStatusResponseEnvelope)(nil), "types.GetDBStatusResponseEnvelope")
	proto.RegisterType((*GetDBStatusResponse)(nil), "types.GetDBStatusResponse")
	proto.RegisterType((*GetDataQueryEnvelope)(nil), "types.GetDataQueryEnvelope")
	proto.RegisterType((*GetDataQuery)(nil), "types.GetDataQuery")
	proto.RegisterType((*GetDataResponseEnvelope)(nil), "types.GetDataResponseEnvelope")
	proto.RegisterType((*GetDataResponse)(nil), "types.GetDataResponse")
	proto.RegisterType((*GetUserQueryEnvelope)(nil), "types.GetUserQueryEnvelope")
	proto.RegisterType((*GetUserQuery)(nil), "types.GetUserQuery")
	proto.RegisterType((*GetUserResponseEnvelope)(nil), "types.GetUserResponseEnvelope")
	proto.RegisterType((*GetUserResponse)(nil), "types.GetUserResponse")
	proto.RegisterType((*GetConfigQueryEnvelope)(nil), "types.GetConfigQueryEnvelope")
	proto.RegisterType((*GetConfigQuery)(nil), "types.GetConfigQuery")
	proto.RegisterType((*GetConfigResponseEnvelope)(nil), "types.GetConfigResponseEnvelope")
	proto.RegisterType((*GetConfigResponse)(nil), "types.GetConfigResponse")
	proto.RegisterType((*Metadata)(nil), "types.Metadata")
	proto.RegisterType((*Version)(nil), "types.Version")
	proto.RegisterType((*AccessControl)(nil), "types.AccessControl")
	proto.RegisterMapType((map[string]bool)(nil), "types.AccessControl.ReadUsersEntry")
	proto.RegisterMapType((map[string]bool)(nil), "types.AccessControl.ReadWriteUsersEntry")
	proto.RegisterType((*Digest)(nil), "types.Digest")
	proto.RegisterType((*ResponseHeader)(nil), "types.ResponseHeader")
	proto.RegisterType((*Response)(nil), "types.Response")
	proto.RegisterType((*ResponseEnvelope)(nil), "types.ResponseEnvelope")
	proto.RegisterType((*ValidationInfo)(nil), "types.ValidationInfo")
}

func init() { proto.RegisterFile("query_and_response.proto", fileDescriptor_998b839b037f2547) }

var fileDescriptor_998b839b037f2547 = []byte{
	// 999 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x56, 0x5f, 0x73, 0xda, 0x46,
	0x10, 0xaf, 0x30, 0xc6, 0xb0, 0x76, 0xb0, 0x72, 0xfe, 0x13, 0xec, 0xb4, 0x13, 0x8f, 0x3c, 0xd3,
	0x61, 0xdc, 0x06, 0xb7, 0x6e, 0x1f, 0x3a, 0x6d, 0xf3, 0x00, 0x42, 0x89, 0xd5, 0xda, 0x22, 0x3d,
	0x14, 0xa7, 0x93, 0x99, 0x8e, 0xe6, 0x8c, 0xce, 0xa0, 0x31, 0x48, 0x58, 0x77, 0x72, 0xcd, 0x73,
	0xdf, 0xfb, 0x0d, 0xfa, 0xde, 0x8f, 0xd2, 0x8f, 0xd5, 0xd1, 0xe9, 0x84, 0x91, 0xb0, 0x27, 0x90,
	0x37, 0x76, 0xf7, 0xb7, 0xbf, 0xdb, 0xbd, 0xdf, 0xed, 0x22, 0xa8, 0xdd, 0x44, 0x34, 0x9c, 0x38,
	0xc4, 0x77, 0x9d, 0x90, 0xb2, 0x71, 0xe0, 0x33, 0xda, 0x18, 0x87, 0x01, 0x0f, 0xd0, 0x2a, 0x9f,
	0x8c, 0x29, 0xdb, 0xdf, 0xea, 0x05, 0xfe, 0x95, 0xd7, 0x8f, 0x42, 0xc2, 0xbd, 0xc0, 0x4f, 0x62,
	0xda, 0x35, 0xd4, 0xde, 0x50, 0xde, 0x6e, 0x75, 0x39, 0xe1, 0x11, 0xfb, 0x2d, 0xa6, 0x30, 0xfc,
	0x5b, 0x3a, 0x0c, 0xc6, 0x14, 0x7d, 0x0b, 0x6b, 0x63, 0x32, 0x19, 0x06, 0xc4, 0xad, 0x29, 0x07,
	0x4a, 0x7d, 0xfd, 0xe4, 0x59, 0x43, 0x30, 0x35, 0xf2, 0x19, 0x38, 0xc5, 0xa1, 0xcf, 0xa1, 0xc2,
	0xbc, 0xbe, 0x4f, 0x78, 0x14, 0xd2, 0x5a, 0xe1, 0x40, 0xa9, 0x6f, 0xe0, 0x7b, 0x87, 0xd6, 0x02,
	0x35, 0x9f, 0x8a, 0x76, 0xa1, 0x14, 0x31, 0x1a, 0x9a, 0x6d, 0x71, 0x46, 0x05, 0x4b, 0x2b, 0xf6,
	0xb7, 0x5b, 0x16, 0x19, 0x25, 0x34, 0x15, 0x2c, 0x2d, 0xed, 0x06, 0x9e, 0xcf, 0x70, 0x60, 0xd9,
	0xe9, 0xb4, 0xe6, 0xef, 0xf3, 0x35, 0xef, 0xcf, 0xd7, 0x9c, 0x26, 0x2d, 0x5a, 0xf6, 0x07, 0xd8,
	0x7a, 0x20, 0x1b, 0xbd, 0x84, 0xd2, 0x80, 0x12, 0x97, 0x86, 0xf2, 0xa4, 0x1d, 0x79, 0x52, 0x0a,
	0x38, 0x15, 0x41, 0x2c, 0x41, 0x68, 0x1b, 0x56, 0xe9, 0x9d, 0xc7, 0xb8, 0xe0, 0x2f, 0xe3, 0xc4,
	0xd0, 0x7a, 0xb0, 0x1d, 0x73, 0x13, 0x4e, 0xb2, 0x77, 0xff, 0x32, 0xdf, 0xc7, 0xd6, 0x4c, 0x1f,
	0x29, 0x7a, 0xd1, 0x06, 0xde, 0xc2, 0xc6, 0x6c, 0xda, 0xb2, 0x77, 0x8e, 0x54, 0x58, 0xb9, 0xa6,
	0x93, 0xda, 0x8a, 0x70, 0xc6, 0x3f, 0x35, 0x0f, 0x9e, 0x49, 0xc6, 0x39, 0x05, 0xbe, 0xc9, 0x57,
	0xbe, 0x9b, 0xad, 0x7c, 0xd9, 0xdb, 0xff, 0x4b, 0x81, 0xcd, 0x5c, 0xea, 0x27, 0x5c, 0xfd, 0x2d,
	0x19, 0x46, 0x29, 0x79, 0x62, 0xa0, 0xaf, 0xa0, 0x3c, 0xa2, 0x9c, 0xb8, 0x84, 0x13, 0xd1, 0xda,
	0xfa, 0xc9, 0xa6, 0xa4, 0x39, 0x97, 0x6e, 0x3c, 0x05, 0x48, 0x9d, 0xde, 0x31, 0x1a, 0x2e, 0xae,
	0xd3, 0x14, 0xbd, 0x68, 0xab, 0xbf, 0x08, 0x9d, 0xa6, 0x69, 0x8f, 0xea, 0xa4, 0xc1, 0x06, 0x27,
	0x61, 0x3f, 0x81, 0x9a, 0x6d, 0xa9, 0x56, 0xc6, 0x27, 0x15, 0x8a, 0x8d, 0xa5, 0x14, 0x9a, 0x4d,
	0x58, 0xb4, 0xec, 0xbf, 0x13, 0x85, 0x66, 0x53, 0x97, 0x55, 0xe8, 0x05, 0x14, 0xe3, 0xde, 0x04,
	0xf7, 0xfa, 0xc9, 0xba, 0x04, 0x0b, 0x46, 0x11, 0x58, 0x4e, 0xac, 0x3e, 0xec, 0xbe, 0xa1, 0x5c,
	0x17, 0xeb, 0x2e, 0x2b, 0xd7, 0x71, 0xbe, 0xf5, 0x9d, 0xfb, 0xd6, 0x67, 0xf0, 0x8b, 0x76, 0x5e,
	0x87, 0x6a, 0x36, 0xf1, 0x31, 0xc9, 0xb4, 0x11, 0xec, 0x4d, 0x91, 0x73, 0x82, 0x9c, 0xe4, 0xab,
	0xaa, 0xe5, 0xab, 0x5a, 0x56, 0x92, 0x7f, 0x14, 0x78, 0x3a, 0x97, 0xbc, 0xac, 0x28, 0x5f, 0x43,
	0x29, 0xf9, 0xcb, 0x90, 0xb2, 0x6c, 0x4b, 0xb8, 0x3e, 0x8c, 0x18, 0xa7, 0xa1, 0x24, 0x97, 0x98,
	0xe5, 0x14, 0xba, 0x81, 0x72, 0xea, 0x45, 0x75, 0x58, 0xbb, 0xa5, 0x21, 0xf3, 0x02, 0x5f, 0x96,
	0x55, 0x95, 0x79, 0x17, 0x89, 0x17, 0xa7, 0x61, 0xf4, 0x13, 0x54, 0x49, 0xaf, 0x47, 0x19, 0x73,
	0x7a, 0x81, 0xcf, 0xc3, 0x60, 0x98, 0x2b, 0xac, 0x29, 0x82, 0x7a, 0x12, 0xc3, 0x4f, 0xc8, 0xac,
	0xa9, 0xbd, 0x82, 0x35, 0x49, 0x88, 0x9e, 0x43, 0xe5, 0x72, 0x18, 0xf4, 0xae, 0x1d, 0x3f, 0x1a,
	0x89, 0x33, 0x8b, 0xb8, 0x2c, 0x1c, 0x56, 0x34, 0x42, 0x3b, 0x50, 0xe2, 0x77, 0x22, 0x52, 0x10,
	0x91, 0x55, 0x7e, 0x67, 0x45, 0x23, 0xed, 0xdf, 0x02, 0x3c, 0xc9, 0xf0, 0xa3, 0x16, 0x40, 0x48,
	0x89, 0xeb, 0xc4, 0x0a, 0xb3, 0x9a, 0x72, 0xb0, 0x52, 0x5f, 0x3f, 0x39, 0x7c, 0xa8, 0x92, 0x06,
	0xa6, 0xc4, 0x8d, 0xdf, 0x32, 0x33, 0x7c, 0x1e, 0x4e, 0x70, 0x25, 0x4c, 0x6d, 0x84, 0x41, 0x15,
	0x1c, 0x7f, 0x86, 0x1e, 0xa7, 0x92, 0xa9, 0x20, 0x98, 0xea, 0x8f, 0x32, 0xbd, 0x8f, 0xb1, 0x33,
	0x74, 0xd5, 0x30, 0xe3, 0xdc, 0xff, 0x19, 0xaa, 0xd9, 0x03, 0xd3, 0xfd, 0xad, 0x4c, 0xf7, 0x77,
	0x76, 0x23, 0x96, 0xe5, 0x46, 0xfc, 0xb1, 0xf0, 0x83, 0xb2, 0xdf, 0x84, 0xad, 0x07, 0x0e, 0x59,
	0x86, 0x42, 0x7b, 0x05, 0xa5, 0xb6, 0xd7, 0xa7, 0x8c, 0xc7, 0x17, 0x1d, 0x06, 0x01, 0x77, 0x06,
	0x84, 0x0d, 0x44, 0xee, 0x06, 0x2e, 0xc7, 0x8e, 0x53, 0xc2, 0x06, 0xf1, 0xa8, 0x0c, 0xa8, 0xd7,
	0x1f, 0x70, 0x79, 0xd1, 0xd2, 0x8a, 0x87, 0x2a, 0xfb, 0x20, 0x63, 0xa4, 0x1f, 0xb8, 0xf4, 0x7e,
	0xa8, 0x12, 0x4b, 0xa3, 0x50, 0xfe, 0xd4, 0xb7, 0x8d, 0xa0, 0xc8, 0xef, 0x3c, 0x57, 0x4e, 0x8e,
	0xf8, 0x1d, 0x1f, 0xc3, 0xc4, 0x5f, 0xbc, 0x78, 0xbf, 0x65, 0x2c, 0x2d, 0xed, 0x1d, 0xa8, 0x73,
	0x23, 0x7b, 0x08, 0x45, 0xf1, 0xd2, 0x95, 0xcc, 0x4b, 0x9f, 0x8e, 0xa9, 0x08, 0x7e, 0x64, 0x46,
	0xff, 0x80, 0xea, 0x05, 0x19, 0x7a, 0xae, 0xf8, 0x1c, 0x33, 0xfd, 0xab, 0x20, 0xde, 0x82, 0x57,
	0x43, 0xd2, 0x17, 0xa4, 0xd5, 0xe9, 0x16, 0x7c, 0x3d, 0x24, 0x7d, 0x2c, 0x02, 0xe8, 0x08, 0x9e,
	0x86, 0x94, 0xb0, 0xc0, 0x77, 0xbc, 0x2b, 0xc7, 0xf3, 0x6f, 0xe3, 0x74, 0xb9, 0xfd, 0x37, 0x93,
	0x80, 0x79, 0x65, 0x26, 0xee, 0xa3, 0xff, 0x14, 0x28, 0xc6, 0xa9, 0xa8, 0x02, 0xab, 0x17, 0xcd,
	0x33, 0xb3, 0xad, 0x7e, 0x86, 0xbe, 0x04, 0xcd, 0xb4, 0x84, 0xe1, 0x9c, 0x5f, 0xe8, 0xba, 0xa3,
	0x77, 0xac, 0xd7, 0x67, 0xa6, 0x6e, 0x3b, 0xef, 0x4d, 0xfb, 0xd4, 0xb4, 0x9c, 0xd6, 0x59, 0x47,
	0xff, 0x55, 0x55, 0x50, 0x03, 0x8e, 0x1e, 0xc7, 0x39, 0x7a, 0xe7, 0xfc, 0xdc, 0xb4, 0x6d, 0xa3,
	0xed, 0x74, 0xed, 0xa6, 0x6d, 0xa8, 0x05, 0x74, 0x08, 0x2f, 0x52, 0x7c, 0xbb, 0x69, 0x37, 0x5b,
	0xcd, 0xae, 0xe1, 0xb4, 0x3b, 0x46, 0xd7, 0xb1, 0x3a, 0xb6, 0x63, 0xfc, 0x6e, 0x76, 0x6d, 0x75,
	0x05, 0xed, 0xc1, 0x4e, 0x0a, 0xb2, 0x3a, 0xce, 0x5b, 0x03, 0x9f, 0x9b, 0xdd, 0xae, 0xd9, 0xb1,
	0xd4, 0x22, 0xfa, 0x02, 0xf6, 0xd2, 0x90, 0x69, 0xe9, 0x1d, 0x8c, 0x0d, 0xdd, 0x76, 0x0c, 0xcb,
	0xc6, 0xa6, 0xd1, 0x55, 0x57, 0x5b, 0x47, 0x1f, 0xea, 0x7d, 0x8f, 0x0f, 0xa2, 0xcb, 0x86, 0x77,
	0x39, 0x6a, 0xf4, 0x82, 0xd1, 0xb1, 0x98, 0xd6, 0xde, 0x80, 0x78, 0xbe, 0x7b, 0x79, 0x2c, 0xbe,
	0x64, 0xd9, 0xb1, 0xb8, 0xad, 0xcb, 0x92, 0xb0, 0xbe, 0xfb, 0x3f, 0x00, 0x00, 0xff, 0xff, 0xb8,
	0xf4, 0x61, 0xa6, 0x0f, 0x0b, 0x00, 0x00,
}
