// Code generated by protoc-gen-go. DO NOT EDIT.
// source: transaction.proto

package api

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

func init() { proto.RegisterFile("transaction.proto", fileDescriptor_2cc4e03d2c28c490) }

var fileDescriptor_2cc4e03d2c28c490 = []byte{
	// 168 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x8e, 0x41, 0x0a, 0xc2, 0x30,
	0x10, 0x45, 0x29, 0x82, 0x8b, 0x8a, 0x42, 0x8b, 0x0b, 0xe9, 0x01, 0xa4, 0xab, 0x54, 0xf4, 0x02,
	0x22, 0x78, 0x81, 0xd6, 0x95, 0x9b, 0x92, 0xc4, 0xc1, 0x0e, 0xb6, 0x99, 0x21, 0x99, 0x16, 0xbd,
	0xbd, 0x50, 0x17, 0x66, 0xf9, 0xdf, 0xe3, 0xc3, 0x4b, 0x33, 0xf1, 0xda, 0x05, 0x6d, 0x05, 0xc9,
	0x29, 0xf6, 0x24, 0x94, 0x2f, 0x34, 0x63, 0xb1, 0x35, 0x3d, 0xd9, 0x57, 0x2b, 0xef, 0x56, 0x3e,
	0x0c, 0xe1, 0xa7, 0x8a, 0x55, 0x34, 0x8e, 0x75, 0xba, 0xb9, 0xfd, 0xcf, 0xcd, 0x64, 0xf3, 0x73,
	0x9a, 0x35, 0xa3, 0x19, 0x50, 0x22, 0x9e, 0xef, 0x94, 0x66, 0x54, 0x11, 0xb9, 0xba, 0x09, 0x7a,
	0x62, 0x28, 0xd6, 0xb3, 0xa9, 0x21, 0x30, 0xb9, 0x00, 0x65, 0x72, 0x48, 0x2e, 0xe5, 0x7d, 0xff,
	0x44, 0xe9, 0x46, 0xa3, 0xd0, 0x0c, 0xca, 0xd2, 0x50, 0xcd, 0x1d, 0xb6, 0xd3, 0xe8, 0x1e, 0xa6,
	0x0a, 0xe0, 0x27, 0xf0, 0x95, 0x66, 0x34, 0xcb, 0x39, 0xe2, 0xf4, 0x0d, 0x00, 0x00, 0xff, 0xff,
	0xd9, 0x0d, 0xb2, 0x5b, 0xc1, 0x00, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// TransactionSvcClient is the client API for TransactionSvc service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TransactionSvcClient interface {
	SubmitTransaction(ctx context.Context, opts ...grpc.CallOption) (TransactionSvc_SubmitTransactionClient, error)
}

type transactionSvcClient struct {
	cc *grpc.ClientConn
}

func NewTransactionSvcClient(cc *grpc.ClientConn) TransactionSvcClient {
	return &transactionSvcClient{cc}
}

func (c *transactionSvcClient) SubmitTransaction(ctx context.Context, opts ...grpc.CallOption) (TransactionSvc_SubmitTransactionClient, error) {
	stream, err := c.cc.NewStream(ctx, &_TransactionSvc_serviceDesc.Streams[0], "/api.TransactionSvc/SubmitTransaction", opts...)
	if err != nil {
		return nil, err
	}
	x := &transactionSvcSubmitTransactionClient{stream}
	return x, nil
}

type TransactionSvc_SubmitTransactionClient interface {
	Send(*TransactionEnvelope) error
	Recv() (*Response, error)
	grpc.ClientStream
}

type transactionSvcSubmitTransactionClient struct {
	grpc.ClientStream
}

func (x *transactionSvcSubmitTransactionClient) Send(m *TransactionEnvelope) error {
	return x.ClientStream.SendMsg(m)
}

func (x *transactionSvcSubmitTransactionClient) Recv() (*Response, error) {
	m := new(Response)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// TransactionSvcServer is the server API for TransactionSvc service.
type TransactionSvcServer interface {
	SubmitTransaction(TransactionSvc_SubmitTransactionServer) error
}

// UnimplementedTransactionSvcServer can be embedded to have forward compatible implementations.
type UnimplementedTransactionSvcServer struct {
}

func (*UnimplementedTransactionSvcServer) SubmitTransaction(srv TransactionSvc_SubmitTransactionServer) error {
	return status.Errorf(codes.Unimplemented, "method SubmitTransaction not implemented")
}

func RegisterTransactionSvcServer(s *grpc.Server, srv TransactionSvcServer) {
	s.RegisterService(&_TransactionSvc_serviceDesc, srv)
}

func _TransactionSvc_SubmitTransaction_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(TransactionSvcServer).SubmitTransaction(&transactionSvcSubmitTransactionServer{stream})
}

type TransactionSvc_SubmitTransactionServer interface {
	Send(*Response) error
	Recv() (*TransactionEnvelope, error)
	grpc.ServerStream
}

type transactionSvcSubmitTransactionServer struct {
	grpc.ServerStream
}

func (x *transactionSvcSubmitTransactionServer) Send(m *Response) error {
	return x.ServerStream.SendMsg(m)
}

func (x *transactionSvcSubmitTransactionServer) Recv() (*TransactionEnvelope, error) {
	m := new(TransactionEnvelope)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _TransactionSvc_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.TransactionSvc",
	HandlerType: (*TransactionSvcServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SubmitTransaction",
			Handler:       _TransactionSvc_SubmitTransaction_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "transaction.proto",
}
